### PR TITLE
[SPARK-37465][PYTHON] Bump minimum pandas version to 1.0.5

### PR DESCRIPTION
**Pull request by Yikun**
### What changes were proposed in this pull request?
Bump minimum pandas version to 1.0.5 (or a better version)

### Why are the changes needed?
Initial discussion from [SPARK-37465](https://issues.apache.org/jira/browse/SPARK-37465) and https://github.com/apache/spark/pull/34314#issuecomment-975160487 .

### Does this PR introduce _any_ user-facing change?
Yes, bump pandas minimun version.

### How was this patch tested?
PySpark test passed with pandas v1.0.5.

### CODE REVIEW

**Comment by Yikun** [comment]
Here is top 20 download from pypi stat:

By using below way according
```SQL
SELECT
  file.version AS file_version,
  COUNT(*) AS num_downloads,
FROM `the-psf.pypi.file_downloads`
WHERE file.project = 'pandas'
AND 
  -- Only query the last 3 months of history
  DATE(timestamp)
    BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH)
    AND CURRENT_DATE()
GROUP BY `file_version`
ORDER BY `num_downloads` DESC
```

  | version | number | percent
-- | -- | -- | --
1 | 0.25.3 | 35149221 | 14.28%
2 | 1.1.5 | 28722806 | 11.67%
3 | 1.3.4 | 20944236 | 8.51%
4 | 1.3.3 | 16861573 | 6.85%
5 | 0.24.2 | 13235233 | 5.38%
6 | 1.0.5 | 9201989 | 3.74%
7 | 1.3.2 | 9077326 | 3.69%
8 | 1.2.5 | 7902532 | 3.21%
9 | 1.2.4 | 5754284 | 2.34%
10 | 1.1.4 | 5710439 | 2.32%
11 | 1.1.0 | 4760847 | 1.93%
12 | 1.1.2 | 4621441 | 1.88%
13 | 1.2.3 | 4607043 | 1.87%
14 | 1.0.3 | 4601230 | 1.87%
15 | 0.23.4 | 4251044 | 1.73%
16 | 0.25.0 | 3862673 | 1.57%
17 | 1.2.1 | 2952346 | 1.20%
18 | 1.0.1 | 2690006 | 1.09%
19 | 0.22.0 | 2680710 | 1.09%
20 | 1.2.0 | 2645339 | 1.07%
21 | 0.24.1 | 2635411 | 1.07%

[1] https://packaging.python.org/guides/analyzing-pypi-package-downloads/

**Comment by HyukjinKwon** [comment]
cc @ueshin @xinrong-databricks @itholic  FYI

**Comment by HyukjinKwon** [comment]
Let's also update https://github.com/apache/spark/blob/master/python/docs/source/getting_started/install.rst#dependencies

**Review by srowen — COMMENTED** [review]
Seems OK to go ahead and require the stable-r 1.x release

**Review by HyukjinKwon — COMMENTED** [review]
+1. cc @ueshin @BryanCutler @viirya @xinrong-databricks @itholic FYI

**Comment by rshkv** [comment]
I noticed that `IntegralExtensionOpsTest.test_invert` fails on Pandas 1.0.0 and succeeds on 1.0.1 (error below). So Maybe safer to recommend that version. Otherwise everything seems to work with 1.0.0.

<details>
<summary>Test failure</summary>

```
======================================================================
ERROR [0.404s]: test_invert (pyspark.pandas.tests.data_type_ops.test_num_ops.IntegralExtensionOpsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/project/python/pyspark/testing/pandasutils.py", line 122, in assertPandasEqual
    **kwargs
  File "/opt/pyenv/versions/3.7.3/lib/python3.7/site-packages/pandas/_testing.py", line 1137, in assert_series_equal
    assert_attr_equal("dtype", left, right, obj=f"Attributes of {obj}")
  File "/opt/pyenv/versions/3.7.3/lib/python3.7/site-packages/pandas/_testing.py", line 772, in assert_attr_equal
    raise_assert_detail(obj, msg, left_attr, right_attr)
  File "/opt/pyenv/versions/3.7.3/lib/python3.7/site-packages/pandas/_testing.py", line 915, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Attributes of Series are different

Attribute "dtype" are different
[left]:  object
[right]: Int8

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/circleci/project/python/pyspark/pandas/tests/data_type_ops/test_num_ops.py", line 498, in test_invert
    self.check_extension(~pser, ~psser)
  File "/home/circleci/project/python/pyspark/pandas/tests/data_type_ops/testing_utils.py", line 248, in check_extension
    self.assert_eq(left, right)
  File "/home/circleci/project/python/pyspark/testing/pandasutils.py", line 223, in assert_eq
    self.assertPandasEqual(lobj, robj, check_exact=check_exact)
  File "/home/circleci/project/python/pyspark/testing/pandasutils.py", line 130, in assertPandasEqual
    raise AssertionError(msg) from e
AssertionError: Attributes of Series are different

Attribute "dtype" are different
[left]:  object
[right]: Int8

Left:
dtype: object
object

Right:
dtype: Int8
Int8
```
</details>

**Comment by itholic** [comment]
> I noticed that `IntegralExtensionOpsTest.test_invert` fails on Pandas 1.0.0 and succeeds on 1.0.1 (error below). So maybe safer to recommend that version. Otherwise everything seems to work with 1.0.0.

Yeah, it seems the bug in pandas 1.0.0.

- pandas 1.0.0
```python
>>> pser = pd.Series([1, 2, 3, None], dtype="Int8")
>>> pser
0       1
1       2
2       3
3    <NA>
dtype: Int8
>>> ~pser
0      -2
1      -3
2      -4
3    <NA>
dtype: object  # this should've been `Int8`
```

Resolved in pandas 1.0.1.

- pandas 1.0.1
```python
>>> pser = pd.Series([1, 2, 3, None], dtype="Int8")
>>> pser
0       1
1       2
2       3
3    <NA>
dtype: Int8
>>> ~pser
0      -2
1      -3
2      -4
3    <NA>
dtype: Int8
```

For addressing this,

1. manually separate this test for pandas 1.0.0.
2. set the minimum pandas to version 1.0.1.

Not sure which way is better, but I think we can just go with `2` if there is no reason to stick with the 1.0.0.

**Comment by srowen** [comment]
Yeah just require 1.0.1 for this reason

**Comment by xinrong-databricks** [comment]
Thanks @Yikun, how do you think about bumping to `1.0.1`?

**Comment by Yikun** [comment]
Sure, thanks for your suggestion, I'd like to update. and I added a simple test to install pandas v1.0.1 and run test on https://github.com/apache/spark/pull/34730 , wait for the result.

**Comment by Yikun** [comment]
Complete all `pyspark-pandas-slow` test with:
```
python/run-tests --modules=pyspark-pandas --parallelism=2 --python-executable=python3
```

Serveral test cases failed in 1.0.1 due to `AttributeError: type object 'object' has no attribute 'dtype'` and **passed with pandas v1.0.5**.


<details>
  <summary>Test failure details</summary>

```
======================================================================
ERROR: test_astype (pyspark.pandas.tests.data_type_ops.test_categorical_ops.CategoricalOpsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jiangyikun/spark/spark/python/pyspark/pandas/tests/data_type_ops/test_categorical_ops.py", line 204, in test_astype
    self.assert_eq(pser.astype(int), psser.astype(int))
  File "/Users/jiangyikun/spark/spark/python/pyspark/testing/pandasutils.py", line 224, in assert_eq
    robj = self._to_pandas(right)
  File "/Users/jiangyikun/spark/spark/python/pyspark/testing/pandasutils.py", line 245, in _to_pandas
    return obj.to_pandas()
  File "/Users/jiangyikun/spark/spark/python/pyspark/pandas/series.py", line 1588, in to_pandas
    return self._to_pandas()
  File "/Users/jiangyikun/spark/spark/python/pyspark/pandas/series.py", line 1594, in _to_pandas
    return self._to_internal_pandas().copy()
  File "/Users/jiangyikun/spark/spark/python/pyspark/pandas/series.py", line 6349, in _to_internal_pandas
    return self._psdf._internal.to_pandas_frame[self.name]
  File "/Users/jiangyikun/spark/spark/python/pyspark/pandas/utils.py", line 584, in wrapped_lazy_property
    setattr(self, attr_name, fn(self))
  File "/Users/jiangyikun/spark/spark/python/pyspark/pandas/internal.py", line 1049, in to_pandas_frame
    pdf = sdf.toPandas()
  File "/Users/jiangyikun/spark/spark/python/pyspark/sql/pandas/conversion.py", line 185, in toPandas
    pdf = pd.DataFrame(columns=tmp_column_names).astype(
  File "/Users/jiangyikun/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 435, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/Users/jiangyikun/venv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 239, in init_dict
    val = construct_1d_arraylike_from_scalar(np.nan, len(index), nan_dtype)
  File "/Users/jiangyikun/venv/lib/python3.8/site-packages/pandas/core/dtypes/cast.py", line 1449, in construct_1d_arraylike_from_scalar
    dtype = dtype.dtype
AttributeError: type object 'object' has no attribute 'dtype'

======================================================================
ERROR: test_read_csv (pyspark.pandas.tests.test_csv.CsvTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jiangyikun/spark/spark/python/pyspark/pandas/tests/test_csv.py", line 151, in test_read_csv
    check(usecols=[])
  File "/Users/jiangyikun/spark/spark/python/pyspark/pandas/tests/test_csv.py", line 138, in check
    self.assert_eq(expected, actual, almost=True)
  File "/Users/jiangyikun/spark/spark/python/pyspark/testing/pandasutils.py", line 224, in assert_eq
    robj = self._to_pandas(right)
  File "/Users/jiangyikun/spark/spark/python/pyspark/testing/pandasutils.py", line 245, in _to_pandas
    return obj.to_pandas()
  File "/Users/jiangyikun/spark/spark/python/pyspark/pandas/frame.py", line 4856, in to_pandas
    return self._to_pandas()
  File "/Users/jiangyikun/spark/spark/python/pyspark/pandas/frame.py", line 4862, in _to_pandas
    return self._internal.to_pandas_frame.copy()
  File "/Users/jiangyikun/spark/spark/python/pyspark/pandas/utils.py", line 584, in wrapped_lazy_property
    setattr(self, attr_name, fn(self))
  File "/Users/jiangyikun/spark/spark/python/pyspark/pandas/internal.py", line 1049, in to_pandas_frame
    pdf = sdf.toPandas()
  File "/Users/jiangyikun/spark/spark/python/pyspark/sql/pandas/conversion.py", line 185, in toPandas
    pdf = pd.DataFrame(columns=tmp_column_names).astype(
  File "/Users/jiangyikun/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 435, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/Users/jiangyikun/venv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 239, in init_dict
    val = construct_1d_arraylike_from_scalar(np.nan, len(index), nan_dtype)
  File "/Users/jiangyikun/venv/lib/python3.8/site-packages/pandas/core/dtypes/cast.py", line 1449, in construct_1d_arraylike_from_scalar
    dtype = dtype.dtype
AttributeError: type object 'object' has no attribute 'dtype'

======================================================================
ERROR: test_kde_plot (pyspark.pandas.tests.plot.test_frame_plot_plotly.DataFramePlotPlotlyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jiangyikun/spark/spark/python/pyspark/pandas/tests/plot/test_frame_plot_plotly.py", line 262, in test_kde_plot
    actual = psdf.plot.kde(bw_method=5, ind=3)
  File "/Users/jiangyikun/spark/spark/python/pyspark/pandas/plot/core.py", line 946, in kde
    return self(kind="kde", bw_method=bw_method, ind=ind, **kwargs)
  File "/Users/jiangyikun/spark/spark/python/pyspark/pandas/plot/core.py", line 498, in __call__
    return plot_backend.plot_pandas_on_spark(plot_data, kind=kind, **kwargs)
  File "/Users/jiangyikun/spark/spark/python/pyspark/pandas/plot/plotly.py", line 44, in plot_pandas_on_spark
    return plot_kde(data, **kwargs)
  File "/Users/jiangyikun/spark/spark/python/pyspark/pandas/plot/plotly.py", line 202, in plot_kde
    pd.DataFrame(
  File "/Users/jiangyikun/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 435, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/Users/jiangyikun/venv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 254, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/Users/jiangyikun/venv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 69, in arrays_to_mgr
    arrays = _homogenize(arrays, index, dtype)
  File "/Users/jiangyikun/venv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 322, in _homogenize
    val = sanitize_array(
  File "/Users/jiangyikun/venv/lib/python3.8/site-packages/pandas/core/construction.py", line 465, in sanitize_array
    subarr = construct_1d_arraylike_from_scalar(value, len(index), dtype)
  File "/Users/jiangyikun/venv/lib/python3.8/site-packages/pandas/core/dtypes/cast.py", line 1461, in construct_1d_arraylike_from_scalar
    subarr = np.empty(length, dtype=dtype)
TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

======================================================================
ERROR: test_kde_plot (pyspark.pandas.tests.plot.test_series_plot_plotly.SeriesPlotPlotlyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jiangyikun/spark/spark/python/pyspark/pandas/tests/plot/test_series_plot_plotly.py", line 231, in test_kde_plot
    actual = psdf.a.plot.kde(bw_method=5, ind=3)
  File "/Users/jiangyikun/spark/spark/python/pyspark/pandas/plot/core.py", line 946, in kde
    return self(kind="kde", bw_method=bw_method, ind=ind, **kwargs)
  File "/Users/jiangyikun/spark/spark/python/pyspark/pandas/plot/core.py", line 498, in __call__
    return plot_backend.plot_pandas_on_spark(plot_data, kind=kind, **kwargs)
  File "/Users/jiangyikun/spark/spark/python/pyspark/pandas/plot/plotly.py", line 44, in plot_pandas_on_spark
    return plot_kde(data, **kwargs)
  File "/Users/jiangyikun/spark/spark/python/pyspark/pandas/plot/plotly.py", line 202, in plot_kde
    pd.DataFrame(
  File "/Users/jiangyikun/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 435, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/Users/jiangyikun/venv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 254, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/Users/jiangyikun/venv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 69, in arrays_to_mgr
    arrays = _homogenize(arrays, index, dtype)
  File "/Users/jiangyikun/venv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 322, in _homogenize
    val = sanitize_array(
  File "/Users/jiangyikun/venv/lib/python3.8/site-packages/pandas/core/construction.py", line 465, in sanitize_array
    subarr = construct_1d_arraylike_from_scalar(value, len(index), dtype)
  File "/Users/jiangyikun/venv/lib/python3.8/site-packages/pandas/core/dtypes/cast.py", line 1461, in construct_1d_arraylike_from_scalar
    subarr = np.empty(length, dtype=dtype)
TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

```
</details>

At this time, I prefer to update to **1.0.5**, I'm going to run `pyspark-pandas-slow` now.

**Comment by Yikun** [comment]
There are only a precision error of `pyspark-pandas-slow` testcase, we could add almost flag:

<details>
  <summary>Test failure details</summary>

```
======================================================================
FAIL: test_mad (pyspark.pandas.tests.test_series.SeriesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jiangyikun/spark/spark/python/pyspark/pandas/tests/test_series.py", line 2235, in test_mad
    self.assert_eq(pser.mad(), psser.mad())
  File "/Users/jiangyikun/spark/spark/python/pyspark/testing/pandasutils.py", line 240, in assert_eq
    self.assertEqual(lobj, robj)
AssertionError: 21.555555555555554 != 21.555555555555557

----------------------------------------------------------------------
```
</details>

**Comment by Yikun** [comment]
As a conclusion in here:
- before v1.0.1: test failed due to https://github.com/apache/spark/pull/34717#issuecomment-981182023 https://github.com/apache/spark/pull/34717#issuecomment-981182023
- before v1.0.5: test failed due to https://github.com/apache/spark/pull/34717#issuecomment-981463864
- There are only a precision problem on v1.0.5, so just add `almost=True` to `assert_eq`, we can fix the testcase

So, I bump minimum pandas version to v1.0.5, the v1.0.5 is also the latest version of [Pandas verions 1.0](https://pandas.pydata.org/docs/whatsnew/index.html#version-1-0).

File: python/docs/source/user_guide/sql/arrow_pandas.rst [hunk 1]
```diff
@@ -387,7 +387,7 @@ working with timestamps in ``pandas_udf``\s to get the best performance, see
 Recommended Pandas and PyArrow Versions
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
-For usage with pyspark.sql, the minimum supported versions of Pandas is 0.23.2 and PyArrow is 1.0.0.
+For usage with pyspark.sql, the minimum supported versions of Pandas is 1.0.5 and PyArrow is 1.0.0.
```
Comment (viirya) [inline python/docs/source/user_guide/sql/arrow_pandas.rst:390]: Should we mention there are some issues with versions like 1.0.0, 1.0.1?

**Review by viirya — COMMENTED** [review]
Seems okay. One comment about the doc.

File: python/pyspark/pandas/tests/test_series.py [hunk 2]
```diff
@@ -2209,12 +2209,12 @@ def test_mad(self):
         pser = pd.Series([1, 2, 3, 4], name="Koalas")
         psser = ps.from_pandas(pser)
 
-        self.assert_eq(pser.mad(), psser.mad())
+        self.assert_eq(pser.mad(), psser.mad(), almost=True)
```
Comment (ueshin) [inline python/pyspark/pandas/tests/test_series.py:2212]: Could you try with `check_exact=False` instead of `almost=True`?
If it works, it's better because it still checks the internal structure of the Series / DataFrame; otherwise `almost=True` checks only values.

**Review by BryanCutler — APPROVED** [review]
LGTM, I think v1.0.5 is a reasonable minimum

**Comment by itholic** [comment]
LGTM if remaining comments are resolved.

**Review by itholic — APPROVED** [review]

File: python/pyspark/pandas/tests/test_series.py (hunk 2 above)
Comment (Yikun) [reply python/pyspark/pandas/tests/test_series.py:2212]: Yep, I tried `self.assert_eq(pser.mad(), psser.mad(), check_exact=False)`, it failed again. Because the test.mad() result value type is a numpy.float64 scalar, it would be matched to:

https://github.com/apache/spark/blob/c38c617bcd04429e50310e4c7e0bd989c6555836/python/pyspark/testing/pandasutils.py#L237-L240

So, only `almost=True` work.

And I know your concern it's make sure the type is right in here, but not only to check value. I notice that only last check is failed in my env, so we can keep top 3 check as original, and just make last check as almost=True.

Comment (Yikun) [reply python/pyspark/pandas/tests/test_series.py:2212]: And one more thing, this test case failed in my env always, even the latest pandas v1.3.4, so looks like a precision issue cross platfroms.

**Review by HyukjinKwon — APPROVED** [review]

File: python/docs/source/user_guide/sql/arrow_pandas.rst (hunk 1 above)
Comment (Yikun) [reply python/docs/source/user_guide/sql/arrow_pandas.rst:390]: How about?

For usage with pyspark.sql, the minimum supported versions of Pandas is 1.0.5 and PyArrow is 1.0.0. Lower versions (such as there are some known issue under with v1.0.0, v1.0.1, see more in [link](https://github.com/apache/spark/pull/34717)) or higher versions may be used, however, compatibility and data correctness can not be guaranteed and should be verified by the user.

Maybe need more suggestion from native speaker. T_T

File: python/pyspark/pandas/tests/test_series.py (hunk 2 above)
Comment (Yikun) [reply python/pyspark/pandas/tests/test_series.py]: Addressed.

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

File: python/pyspark/pandas/tests/test_series.py (hunk 2 above)
Comment (ueshin) [reply python/pyspark/pandas/tests/test_series.py]: Ah, got it. The result was not `DataFrame` or `Series`, then `almost=True` should be fine. Thanks.
