### PR TITLE
[SPARK-27176][FOLLOW-UP][SQL] Upgrade Hive parquet to 1.10.1 for hadoop-3.2

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

When we compile and test Hadoop 3.2, we will hint the following two issues:
1. JobSummaryLevel is not a member of object org.apache.parquet.hadoop.ParquetOutputFormat. Fixed by [PARQUET-381](https://issues.apache.org/jira/browse/PARQUET-381)(Parquet 1.9.0)
2. java.lang.NoSuchFieldError: BROTLI
    at org.apache.parquet.hadoop.metadata.CompressionCodecName.<clinit>(CompressionCodecName.java:31). Fixed by [PARQUET-1143](https://issues.apache.org/jira/browse/PARQUET-1143)(Parquet 1.10.0)

The reason is that the `parquet-hadoop-bundle-1.8.1.jar` conflicts with Parquet 1.10.1.
I think it would be safe to upgrade Hive's parquet to 1.10.1 to workaround this issue.

This is what Hive did when upgrading Parquet 1.8.1 to 1.10.0: [HIVE-17000](https://issues.apache.org/jira/browse/HIVE-17000) and [HIVE-19464](https://issues.apache.org/jira/browse/HIVE-19464). We can see that all changes are related to vectors, and vectors are disabled by default: see [HIVE-14826](https://issues.apache.org/jira/browse/HIVE-14826) and [HiveConf.java#L2723](https://github.com/apache/hive/blob/rel/release-2.3.4/common/src/java/org/apache/hadoop/hive/conf/HiveConf.java#L2723).

This pr removes [parquet-hadoop-bundle-1.8.1.jar](https://github.com/apache/parquet-mr/tree/master/parquet-hadoop-bundle) , so Hive serde will use [parquet-common-1.10.1.jar, parquet-column-1.10.1.jar and parquet-hadoop-1.10.1.jar](https://github.com/apache/spark/blob/master/dev/deps/spark-deps-hadoop-3.2#L185-L189).

## How was this patch tested?

1. manual tests
2. [upgrade Hive Parquet to 1.10.1 annd run Hadoop 3.2 test on jenkins](https://github.com/apache/spark/pull/24044#commits-pushed-0c3f962)

### CODE REVIEW

**Comment by tgravescs** [comment]
taking a look, it looks like the only code changes were in HIVE-19464 and its changing from the ByteBuffer to a ByteBufferInputStream which gets passed into the ValueReader.  The ByteBuffer interface however does look like they removed in 1.10:

https://github.com/apache/parquet-mr/blob/apache-parquet-1.10.1/parquet-column/src/main/java/org/apache/parquet/column/values/ValuesReader.java

But it looks like they have fixed it in master and 1.11.0:
https://github.com/apache/parquet-mr/commit/345e2d541128471641e76aaa44dd5046f199197d#diff-b2cc86057b0544e21c20f481c95a8851

So maybe we should look at upgrading to 1.11? I'm not sure what all else that will require though.  I'm not sure how many people are using the vectorization in hive. Seems reasonable to do this for now and followup with 1.11 or wait for someone to request that.

**Comment by wangyum** [comment]
cc @gatorsmile

**Comment by felixcheung** [comment]
Hive on vectorized reader is quite common AFAIK. Spark seems to be generally ok with upgrading parquet, (in fact there's already a PR) can we move to 1.11?

**Comment by tooptoop4** [comment]
@wangyum really appreciate the work on the hive upgrade. Just wanted to check with your upgraded tests if on the same machine you are able to run HiveServer2 (on Spark exec engine) and SparkThriftServer with a non-local Spark Master and successfully run select count(*) queries? For it to work for me I had to revert SPARK-23972, SPARK-21276, SPARK-19112. I'm using Hive 2.3.4 and Spark 2.3.3

File: pom.xml [hunk 1]
```diff
@@ -2809,7 +2809,7 @@
         <hive.version>${hive23.version}</hive.version>
         <hive.version.short>2.3.4</hive.version.short>
         <hive.parquet.group>org.apache.parquet</hive.parquet.group>
-        <hive.parquet.version>1.8.1</hive.parquet.version>
```
Comment (cloud-fan) [inline pom.xml]: do you know why we did it at the first place?

**Comment by gatorsmile** [comment]
I do not think we can upgrade the Parquet to 1.11 just after its release, since Parquet is our default format. The quality of Parquet releases directly impacts our release quality. Thus, I would propose to hold it until more companies try the new release in the production systems. Thanks!

File: pom.xml (hunk 1 above)
Comment (gatorsmile) [reply pom.xml]: This was suggested by me since Hive parquet version is different from ours.

**Comment by gatorsmile** [comment]
> Hive on vectorized reader is quite common AFAIK

@felixcheung How about upgrading Parquet to 1.11 in Spark 3.1 release, if the new release of Parquet becomes table. In the current stage, let us try to use 1.10.1 first and disable the Hive's vectorized Parquet readers. [You know, our Spark native Parquet reader is also vectorized. I assume our reader is either faster or as fast as Hive vectorized reader.] If we do not hit any issue using 1.10.1, we can avoid shading our Parquet version in sql/core.

**Comment by gatorsmile** [comment]
@wangyum We do need to add a new test suite in sql/hive for testing the new features of Hive (e.g., the Hive's native vectorized reader). Could you create an umbrallel JIRA and list all these new features? The community can help add these test cases?

**Comment by wangyum** [comment]
@gatorsmile Ok, I have created it: [SPARK-27500](https://issues.apache.org/jira/browse/SPARK-27500).

**Comment by wangyum** [comment]
It seems we can't support Hive's native vectorized reader and even enable `hive.vectorized.execution.enabled`. Hive's native vectorized reader needs set [setPlanPath(conf, hiveScratchDir)](https://github.com/apache/hive/blob/rel/release-2.3.4/ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java#L559) first and [getPlanPath(conf)](https://github.com/apache/hive/blob/rel/release-2.3.4/ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java#L3398) when running task on the executor. 
Case 1: `spark.sql(...)` does not  set it, so `getPlanPath` is always null.
Case 2: `hiveClient.runSqlHive(...)` sets it on the driver side, executor still can't get this value.
So [Utilities.getUseVectorizedInputFileFormat](https://github.com/apache/hive/blob/rel/release-2.3.4/ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java#L3386) is always false.

**Comment by tgravescs** [comment]
Unfortunately I don't see the 1.11 parquet version for all the packages yet: https://mvnrepository.com/artifact/org.apache.parquet/parquet-column. so I guess maybe its not officially released yet.

**Comment by wangyum** [comment]
Yes. It's still in voting.
https://issues.apache.org/jira/browse/PARQUET-1434
https://mail-archives.apache.org/mod_mbox/parquet-dev/201904.mbox/%3C61EAEB3E-E68F-4DD5-8A5D-38489A48B9D7%40rms.com%3E

**Comment by tgravescs** [comment]
Right now the Hadoop 3.2 profile doesn't even build, I would vote for changing it to 1.10.1 for now and file a followup, thoughts?

**Comment by gatorsmile** [comment]
@tgravescs +1

**Review by tgravescs — APPROVED** [review]

File: pom.xml [hunk 2]
```diff
@@ -2809,7 +2809,7 @@
...
+        <hive.parquet.version>${parquet.version}</hive.parquet.version>
```
Comment (cloud-fan) [inline pom.xml]: then we can remove the `hive.parquet.version` property?

Comment (wangyum) [reply pom.xml]: Good suggestion.

**Review by gatorsmile — COMMENTED** [review]
LGTM 

Thanks! Merged to master.
