### PR TITLE
[HOTFIX][SPARK-14402] Fix ExpressionDescription annotation

### PR DESCRIPTION
**Pull request by jaceklaskowski**
## What changes were proposed in this pull request?

Fix for the error introduced in https://github.com/apache/spark/commit/c59abad052b7beec4ef550049413e95578e545be:

```
/Users/jacek/dev/oss/spark/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/stringExpressions.scala:626: error: annotation argument needs to be a constant; found: "_FUNC_(str) - ".+("Returns str, with the first letter of each word in uppercase, all other letters in ").+("lowercase. Words are delimited by white space.")
    "Returns str, with the first letter of each word in uppercase, all other letters in " +
                                                                                          ^
```
## How was this patch tested?

Local build

### CODE REVIEW

**Comment by marmbrus** [comment]
ok to test

**Comment by jaceklaskowski** [comment]
Is this really the patch to cause the issue or is this more an interim hiccup?

**Comment by marmbrus** [comment]
@tdas another streaming failure

**Comment by dongjoon-hyun** [comment]
Hi, @jaceklaskowski and @marmbrus . 
Thank you for fixing this. I didn't notice there is such a problem.
Sorry for late response!
I have another PR having the same syntax. I will fix that, too. 
Thank you again.

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by dongjoon-hyun** [comment]
Hi, All. 
The original code is made by me, so I feel guilty. :)

I think Jenkins build does not show additional information for this PR since our Jenkins build on master branches works fine.
- https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/  (JDK8 + Scala 2.11)
- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Compile/job/spark-master-compile-maven-scala-2.10/ (JDK8 + Scala 2.10).

And, we know the JDK7 does not have this issue according to the Spark mailing list. So, I ran the following command and found the current master branch compiles without problem. This seems not a Scala compilation problem.
```
spark:master$ git clean -fdx
spark:master$ java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
spark:master$ ./build/mvn -Pyarn -Phadoop-2.6 -Dhadoop.version=2.7.2 -Phive -Phive-thriftserver -DskipTests clean compile
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:38 min
[INFO] Finished at: 2016-04-07T10:29:20-07:00
[INFO] Final Memory: 76M/871M
[INFO] ------------------------------------------------------------------------
```

After that, just `package` also works fine.
```
spark:master$ ./build/mvn -Pyarn -Phadoop-2.6 -Dhadoop.version=2.7.2 -Phive -Phive-thriftserver -DskipTests package
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:02 min
[INFO] Finished at: 2016-04-07T10:50:44-07:00
[INFO] Final Memory: 79M/853M
[INFO] ------------------------------------------------------------------------
```

The real root cause of this error occurs during Scala doc generation by **doc-jar** plugin. Is it possible to solve the real root cause by changing `pom.xml` to reorder the plugin execution stages or something else? I've already changed my another PR #12185 (`DESC FUNCTION` implementation)  according this PR's approach, but it's a little too limited approach for me.

**Comment by dongjoon-hyun** [comment]
Just for a record, here is the current error message from **doc-jar**. (The version of doc-jar is the latest.)
```
[INFO] <<< scala-maven-plugin:3.2.2:doc-jar (attach-scaladocs) < generate-sources @ spark-catalyst_2.11 <<<
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:doc-jar (attach-scaladocs) @ spark-catalyst_2.11 ---
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=64m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
/Users/dongjoon/spark/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/stringExpressions.scala:626: error: annotation argument needs to be a constant; found: "_FUNC_(str) - ".+("Returns str, with the first letter of each word in uppercase, all other letters in ").+("lowercase. Words are delimited by white space.")
    "Returns str, with the first letter of each word in uppercase, all other letters in " +
                                                                                          ^
```

**Comment by srowen** [comment]
I agree it's a bit of a strange problem. @dongjoon-hyun do you agree that this change is worth merging? it seems like it fixes the immediate symptom of a problem, even if we're not sure why the problem exists in the first place. It's not hacky so seems worth merging.

**Comment by dongjoon-hyun** [comment]
Sure. I agree for merging.
The underlying problem will be investigated and resolved someday.

**Comment by jaceklaskowski** [comment]
Please please merge it as soon as possible as I'm suffering from not having it in master every time I do the build :(

**Comment by srowen** [comment]
Merged to master
