### PR TITLE
[SPARK-49183][SQL][FOLLOWUP][3.5] Fix compilation

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

fix compilation error caused by https://github.com/apache/spark/pull/47684 . Seems scala 2.12 has some subtle differences in the import priority.

### Why are the changes needed?

N/A

### Does this PR introduce _any_ user-facing change?

N/A

### How was this patch tested?

pass compilation

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Review by yaooqinn — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]

File: sql/core/src/test/scala/org/apache/spark/sql/connector/DataSourceV2SQLSuite.scala [hunk 1]
```diff
@@ -19,7 +19,7 @@ package org.apache.spark.sql.connector
 
 import java.sql.Timestamp
 import java.time.{Duration, LocalDate, Period}
-import java.util
+import java.{util => jutil}
```
Comment (dongjoon-hyun) [inline sql/core/src/test/scala/org/apache/spark/sql/connector/DataSourceV2SQLSuite.scala:22]: Could you fix the import order, @cloud-fan ?
```
[error] /home/runner/work/spark/spark/sql/core/src/test/scala/org/apache/spark/sql/connector/DataSourceV2SQLSuite.scala:22:0: java. is in wrong order relative to java.time..
```

Comment (dongjoon-hyun) [reply sql/core/src/test/scala/org/apache/spark/sql/connector/DataSourceV2SQLSuite.scala]: Nvm. I. updated the order.
```
$ dev/scalastyle
Using SPARK_LOCAL_IP=localhost
Scalastyle checks passed.
```

**Comment by dongjoon-hyun** [comment]
Merged to branch-3.5 to recover CIs and unblock other PRs.
