### PR TITLE
[SPARK-29883][SQL] Implement a helper method for aliasing bool_and() and bool_or()

### PR DESCRIPTION
**Pull request by amanomer**
### What changes were proposed in this pull request?
This PR introduces a method `expressionWithAlias` in class `FunctionRegistry` which is used to register function's constructor. Currently, `expressionWithAlias` is used to register `BoolAnd` & `BoolOr`.

### Why are the changes needed?
Error message is wrong when alias name is used for `BoolAnd` & `BoolOr`.

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
Tested manually.

For query,
`select every('true');`

Output before this PR,

> Error in query: cannot resolve 'bool_and('true')' due to data type mismatch: Input to function 'bool_and' should have been boolean, but it's [string].; line 1 pos 7;

After this PR,

> Error in query: cannot resolve 'every('true')' due to data type mismatch: Input to function 'every' should have been boolean, but it's [string].; line 1 pos 7;

### CODE REVIEW

**Comment by amanomer** [comment]
@gatorsmile I have now handled for `BoolAnd` and `BoolOr`. Kindly review the changes.

**Comment by amanomer** [comment]
cc @srowen @cloud-fan

File: sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala [hunk 1]
```diff
@@ -118,7 +118,7 @@ class SimpleFunctionRegistry extends FunctionRegistry with Logging {
         throw new AnalysisException(s"undefined function $name")
       }
     }
-    func(children)
+    func(children).setFuncName(name.funcName)
```
Comment (srowen) [inline sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: Hm, do functions not already have names somewhere to use, that can already be set differently per alias? it looks like that's what nodeName is for, and it's already overridden in the aliases, so I'm missing why this is different.

Comment (amanomer) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: > do functions not already have names somewhere to use, that can already be set differently per alias?

I think, No? Currently, when we use alias of bool_and (i.e, every), it will be resolved as a constructor of `BoolAnd` using `FunctionRegistry#expressions`, which sets `bool_and' as a nodeName.
https://github.com/apache/spark/blob/9351e3e76fb11e9fdaf39aef5aea86fdeccd6f28/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/UnevaluableAggs.scala#L55-L57

Comment (srowen) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: This may not make sense, I don't know this code well, but: is it not that "Exists" needs to customize its nodeName, for example? or does it never exist as such a node.

Comment (amanomer) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: `every` here does not have any node. It will be resolved as a `BoolAnd`.
https://github.com/apache/spark/blob/32af7004a254107340df908e8dd91a0bc22e068e/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala#L316-L320

Comment (srowen) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: I see. I don't know enough to evaluate the effect of changing nodeName for all implementations, which seems like a broader change than required, but it does make some sense. Maybe @liancheng or @yhuai has an opinion.

**Comment by amanomer** [comment]
@gatorsmile Kindly review this PR.

File: sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/Expression.scala [hunk 2]
```diff
@@ -286,6 +286,15 @@ abstract class Expression extends TreeNode[Expression] {
   override def simpleStringWithNodeId(): String = {
     throw new UnsupportedOperationException(s"$nodeName does not implement simpleStringWithNodeId")
   }
+
+  var functionAlias: String = ""
```
Comment (cloud-fan) [inline sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/Expression.scala]: It's a bad practice to make the `Expression` mutable for trivial things like this. How about using `RuntimeReplaceable`?

Comment (amanomer) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/Expression.scala]: Argument's data types are matched in Analysis phase of planning and its optimizer's task to replace `RuntimeReplaceable`, correct me if I'm wrong.
So, optimization rules (`ReplaceExpressions`) will never be applied on queries like `select every('true')`.
https://github.com/apache/spark/blob/85cb388ae3f25b0e6a7fc1a2d78fd1c3ec03f341/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/Optimizer.scala#L130

File: sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/UnevaluableAggs.scala [hunk 3]
```diff
@@ -53,7 +53,6 @@ abstract class UnevaluableBooleanAggBase(arg: Expression)
   """,
   since = "3.0.0")
 case class BoolAnd(arg: Expression) extends UnevaluableBooleanAggBase(arg) {
```
Comment (cloud-fan) [inline sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/UnevaluableAggs.scala]: how about
```
case class BoolAnd(functionName: String, arg: Expression) ... with MultiNamesFunction {
  def nodeName = functionName
}
```

We can update `FunctionRegistry.expression` to detect `MultiNamesFunction` and pass name to the constructor.

Comment (amanomer) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/UnevaluableAggs.scala]: Updated PR. cc @cloud-fan

**Comment by cloud-fan** [comment]
ok to test

File: sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala [hunk 4]
```diff
@@ -600,7 +600,8 @@ object FunctionRegistry {
       } else {
         // Otherwise, find a constructor method that matches the number of arguments, and use that.
         val params = Seq.fill(expressions.size)(classOf[Expression])
-        val f = constructors.find(_.getParameterTypes.toSeq == params).getOrElse {
+        val f = constructors.find(e => e.getParameterTypes.toSeq == params
+            || e.getParameterTypes.head == classOf[String]).getOrElse {
```
Comment (cloud-fan) [inline sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: Seems like it's less hacky to create a new `expressionWithAlias` method, with only the necessary logic
```
def expressionWithAlias ... = {
  val constructors = tag.runtimeClass.getConstructors.filter(c => e.getParameterTypes.head == classOf[String])
  assert(constructors.length == 1)
  try {
    constructors.head.newInstance(name, expressions : _*).asInstanceOf[Expression]
  } ...
}
```

Comment (cloud-fan) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: then we don't even need the `MultiNamedExpression` trait. We just need to register `bool_and`, `bool_or` with `expressionWithAlias`

Comment (amanomer) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: @cloud-fan updated as per your suggestions.

File: sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala [hunk 5]
```diff
@@ -631,6 +631,24 @@ object FunctionRegistry {
     (name, (expressionInfo[T](name), builder))
   }
 
+  private def expressionWithAlias[T <: Expression](name: String)
+      (implicit tag: ClassTag[T]): (String, (ExpressionInfo, FunctionBuilder)) = {
+    val constructors = tag.runtimeClass.getConstructors
+      .filter(_.getParameterTypes.head == classOf[String])
+    assert(constructors.length == 1)
+    val builder = (expressions: Seq[Expression]) => {
+      Try(constructors.head.newInstance(name.toString, expressions.head).asInstanceOf[Expression])
```
Comment (cloud-fan) [inline sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: seems better to use the normal try catch?
```
try {
  constructors.head.newInstance(name.toString, expressions.head).asInstanceOf[Expression]
} catch {
  // the original comment ...
  case e => throw new AnalysisException(e.getCause.getMessage)
}
```

We can update `def expression` as well.

**Review by cloud-fan — APPROVED** [review]

File: sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala (hunk 5 above)
Comment (amanomer) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: Updated in latest commit.

**Review by HyukjinKwon — APPROVED** [review]
Looks good to me too if tests pass

**Comment by cloud-fan** [comment]
retest this please

File: sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala [hunk 6]
```diff
@@ -618,19 +618,36 @@ object FunctionRegistry {
...
   }
 
+  private def expressionWithAlias[T <: Expression](name: String)
+      (implicit tag: ClassTag[T]): (String, (ExpressionInfo, FunctionBuilder)) = {
+    val constructors = tag.runtimeClass.getConstructors
+      .filter(_.getParameterTypes.head == classOf[String])
+    assert(constructors.length == 1)
+    val builder = (expressions: Seq[Expression]) => {
+      try {
+        constructors.head.newInstance(name.toString, expressions.head).asInstanceOf[Expression]
```
Comment (amanomer) [inline sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: Since, we are not validating arguments, queries like
`SELECT EVERY(true, false);` will result `true`.

Comment (amanomer) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: We can validate arguments with assert or as used in `expression`?
cc @cloud-fan @HyukjinKwon

**Comment by amanomer** [comment]
There are other function with alias name example `VarianceSamp`, `StddevSamp`. I think we should also use `expressionWithAlias` for registering them?

File: sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala (hunk 6 above)
Comment (cloud-fan) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: how is it done in `def expression`?

**Comment by cloud-fan** [comment]
> Should we change them in this PR?

I'm fine either way.

File: sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala (hunk 6 above)
Comment (amanomer) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: https://github.com/apache/spark/blob/ebd83a544e0eb9fe03e9c1c879e00b50d947a761/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala#L602-L620

Comment (amanomer) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: Since, in `expressionWithAlias` we are always passing `expressions.head` to function's constructor. We can use assert statement
```
...
val builder = (expressions: Seq[Expression]) => {
      assert(expressions.size == 1,
        s"Invalid number of arguments for function $name. " +
          s"Expected: 1; Found: ${expressions.size}")
      assert(expressions.head == classOf[Expression],
        s"Invalid arguments for function $name")
      try {
        constructors.head.newInstance(name.toString, expressions.head).asInstanceOf[Expression]
      }
...
```

**Comment by amanomer** [comment]
Ok, I will handle them in different PR with new JIRA.

File: sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala (hunk 6 above)
Comment (amanomer) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: cc @cloud-fan

Comment (cloud-fan) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: SGTM

Comment (cloud-fan) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: BTW is it possible to do `newInstance(name.toString, expressions: _*)`? Then it can work for other expressions that take more than 1 parameter.

Comment (amanomer) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: > is it possible to do newInstance(name.toString, expressions: _*)?

No, compilation error.

Comment (cloud-fan) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: how about `newInstance((name.toString +: expressions): _*)`?

Comment (amanomer) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: It works

**Comment by amanomer** [comment]
cc @cloud-fan

File: sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala [hunk 7]
```diff
@@ -618,19 +618,41 @@ object FunctionRegistry {
...
   }
 
+  private def expressionWithAlias[T <: Expression](name: String)
+      (implicit tag: ClassTag[T]): (String, (ExpressionInfo, FunctionBuilder)) = {
+    val constructors = tag.runtimeClass.getConstructors
+      .filter(_.getParameterTypes.head == classOf[String])
+    assert(constructors.length == 1)
+    val builder = (expressions: Seq[Expression]) => {
+      val params = classOf[String] +: Seq.fill(expressions.size)(classOf[Expression])
+      val f = constructors.find(_.getParameterTypes.toSeq == params).getOrElse {
```
Comment (cloud-fan) [inline sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: here we not only check the # of arguments, but also argument types. Shall we only check the # of arguments and leave the type check to the `newInstance` call?

Comment (amanomer) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: Here we are checking only # of arguments. Because till here, every argument is of type Expression and also every function's constructor takes Expression(s) as argument. Except `BoolAnd` and `BoolOr`, for which `classOf[String]` is prepended to Seq.

`expression` is also checking only # of arguments. Validating arguments types is done by `checkInputDataTypes()`.

Comment (cloud-fan) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: > also every function's constructor takes Expression(s) as argument

We don't guarantee it. And we should fail with meaningful error message if it happens, instead of "Invalid number of arguments"

Comment (amanomer) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: Okay. I will update.

**Comment by amanomer** [comment]
cc @cloud-fan

**Review by cloud-fan — APPROVED** [review]

**Comment by amanomer** [comment]
@srowen Kindly review.

**Comment by srowen** [comment]
I'm OK with it if @cloud-fan is.

File: sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala [hunk 8]
```diff
@@ -590,12 +590,12 @@ object FunctionRegistry {
     val builder = (expressions: Seq[Expression]) => {
       if (varargCtor.isDefined) {
         // If there is an apply method that accepts Seq[Expression], use that one.
-        Try(varargCtor.get.newInstance(expressions).asInstanceOf[Expression]) match {
-          case Success(e) => e
-          case Failure(e) =>
-            // the exception is an invocation exception. To get a meaningful message, we need the
-            // cause.
-            throw new AnalysisException(e.getCause.getMessage)
```
Comment (dongjoon-hyun) [inline sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: Hi, @amanomer . I'm wondering if this change is required in this PR.

File: sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala [hunk 9]
```diff
@@ -618,19 +618,55 @@ object FunctionRegistry {
           }
           throw new AnalysisException(invalidArgumentsMsg)
         }
-        Try(f.newInstance(expressions : _*).asInstanceOf[Expression]) match {
-          case Success(e) => e
-          case Failure(e) =>
-            // the exception is an invocation exception. To get a meaningful message, we need the
-            // cause.
-            throw new AnalysisException(e.getCause.getMessage)
```
Comment (dongjoon-hyun) [inline sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: ditto.

File: sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala (hunk 8 above)
Comment (amanomer) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: This reformatting of try-catch block can be raised in different PR.

Comment (srowen) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: FWIW I think this is fine and cleaner, so think it's OK to change here.

Comment (amanomer) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala]: I think there are similar try-catch block format on other files too, which can be reformatted like this.

**Review by maropu — APPROVED** [review]
Can you make the title clearer like `Implement a helper method for aliasing registered functions`?

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by amanomer** [comment]
Thanks @cloud-fan
