### PR TITLE
[SPARK-45452][SQL][FOLLOWUP] Do not fail too early if FileSystem does not implement getSchema

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

This is a small followup of https://github.com/apache/spark/pull/43261 . When a `FileSystem` does not implement `getSchema`, we fail earlier than before after https://github.com/apache/spark/pull/43261  . This PR restores the timing of throwing exception by skipping the new optimization if `getSchema` fails.

### Why are the changes needed?

fix small behavior change

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

revert the tests changes in https://github.com/apache/spark/pull/43261 and tests still pass

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @dongjoon-hyun @viirya

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @cloud-fan .

**Review by viirya — COMMENTED** [review]
Looks good to me.
