### PR TITLE
[SPARK-40179][BUILD] Downgrade maven-dependency-plugin to 3.1.1

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr downgrade `maven-dependency-plugin` to 3.1.1 to restore Scala 2.13 CI.

### Why are the changes needed?
Pass Scala 2.13 CI.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
All GA pass

### CODE REVIEW

**Comment by LuciferYang** [comment]
`Run / Scala 2.13 build with SBT` GA failed, I suspect that the `httpcores` jar file corrupt. Upgrade a version to verify the idea

**Comment by HyukjinKwon** [comment]
cc @Yikun FYI

**Comment by LuciferYang** [comment]
```
[error] /home/runner/work/spark/spark/sql/hive-thriftserver/src/main/java/org/apache/hive/service/auth/HttpAuthUtils.java:36:1:  error: package org.apache.http.protocol does not exist
[error] import org.apache.http.protocol.BasicHttpContext;
[error]                                ^
[error] /home/runner/work/spark/spark/sql/hive-thriftserver/src/main/java/org/apache/hive/service/auth/HttpAuthUtils.java:156:1:  error: cannot find symbol
[error]     private final HttpContext httpContext;
[error]                   ^  symbol:   class HttpContext
[error]   location: class HttpKerberosClientAction
[error] 3 errors
```

doesn't look like jar file corrupt

**Comment by Yikun** [comment]
This error is a bit strange, the only possibility I can think of is that for some reason, the cache is not flushed, resulting in a certain error not being caught by CI.

According investigation, I found that this https://github.com/Yikun/spark/commit/3ed382f391911ec4a79fb204f4986728017dfa4a might the real first bad commit:

I just found there were some unexpected behaviror:
https://github.com/panbingkun/spark/runs/7938361118?check_suite_focus=true

The [cache key key: build-f655f4b01719806a657a56bf60547b9f11d9d4ccb88d5655ba18e247ca8897f1](https://github.com/panbingkun/spark/runs/7938361118?check_suite_focus=true#step:4:8) missed, but GA were still using the [old cache key build-2adc4904ccefab084e3f3b8bbd8f62734d9d2636744981017445eaea3bdce355](https://github.com/panbingkun/spark/runs/7938361118?check_suite_focus=true#step:4:17).

**Comment by Yikun** [comment]
I submit the revert PR: https://github.com/apache/spark/pull/37618
