### PR TITLE
[SPARK-32792][SQL][FOLLOWUP] Fix conflict with SPARK-34661

### PR DESCRIPTION
**Pull request by wangyum**
### What changes were proposed in this pull request?

This fixes the compilation error due to the logical conflicts between https://github.com/apache/spark/pull/31776 and https://github.com/apache/spark/pull/29642 .

### Why are the changes needed?

To recover compilation.

### Does this PR introduce _any_ user-facing change?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Thank you!

File: sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFilters.scala [hunk 1]
```diff
@@ -300,7 +300,7 @@ class ParquetFilters(
       (n: Array[String], v: Any) =>
         FilterApi.lt(longColumn(n), decimalToInt64(v.asInstanceOf[JBigDecimal]))
     case ParquetSchemaType(_: DecimalLogicalTypeAnnotation, FIXED_LEN_BYTE_ARRAY, length)
-      if pushDownDecimal =>
+        if pushDownDecimal =>
```
Comment (dongjoon-hyun) [inline sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFilters.scala:303]: Although this is HOTFIX, okay.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. I also verified this manually.

**Comment by dongjoon-hyun** [comment]
Thank you so much, @wangyum and @HyukjinKwon . Merged to master to recover `master` branch.

**Comment by HyukjinKwon** [comment]
Nice!
