### PR TITLE
[SPARK-29250][BUILD] Upgrade to Hadoop 3.3.1

### PR DESCRIPTION
**Pull request by sunchao**
### What changes were proposed in this pull request?

This upgrade default Hadoop version from 3.2.1 to 3.3.1. The changes here are simply update the version number and dependency file.

### Why are the changes needed?

Hadoop 3.3.1 just came out, which comes with many client-side improvements such as for S3A/ABFS (20% faster when accessing S3). These are important for users who want to use Spark in a cloud environment.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

- Existing unit tests in Spark
- Manually tested using my S3 bucket for event log dir:
```
bin/spark-shell \
  -c spark.hadoop.fs.s3a.access.key=$AWS_ACCESS_KEY_ID \
  -c spark.hadoop.fs.s3a.secret.key=$AWS_SECRET_ACCESS_KEY \
  -c spark.eventLog.enabled=true
  -c spark.eventLog.dir=s3a://<my-bucket>
```
- Manually tested against docker-based YARN dev cluster, by running `SparkPi`.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
The failure seems to be relevant since they are YARN test suite.
```
Error:  Error: Total 118, Failed 0, Errors 3, Passed 115, Canceled 1
Error:  Error during tests:
Error:  	org.apache.spark.deploy.yarn.YarnClusterSuite
Error:  	org.apache.spark.deploy.yarn.YarnShuffleAuthSuite
Error:  	org.apache.spark.deploy.yarn.YarnShuffleIntegrationSuite
```

**Comment by dongjoon-hyun** [comment]
BTW, thank you so much, @sunchao !

**Comment by sunchao** [comment]
Yes the test failures are new. It seems to be related to #29843 but I'm not sure why I've never seen it before in all the previous runs.

**Comment by sunchao** [comment]
And all the tests in jenkins are passing. This is weird ...

**Comment by dongjoon-hyun** [comment]
Oh..

**Comment by dongjoon-hyun** [comment]
I retriggered GitHub Action. Let's see.

**Comment by dongjoon-hyun** [comment]
cc @srowen , @dbtsai

**Comment by dongjoon-hyun** [comment]
This seems to hit `bouncycastle`.
```
$ build/sbt "yarn/testOnly *.YarnClusterSuite" -Pyarn -Phadoop-3.2
...
[info] YarnClusterSuite:
[info] org.apache.spark.deploy.yarn.YarnClusterSuite *** ABORTED *** (580 milliseconds)
[info]   java.lang.NoClassDefFoundError: org/apache/hadoop/shaded/org/bouncycastle/operator/OperatorCreationException
```

**Comment by srowen** [comment]
What does it imply for compatibility with clusters? it works with Hadoop 3.2, earlier? we may need to rename the profile eventually to "hadoop-3" or something. Implicitly it's "Hadoop 3.2+"

**Comment by sunchao** [comment]
Yeah it should work with Hadoop 3.2+ clusters since [Hadoop maintains wire compatibility across minor releases. ](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/AdminCompatibilityGuide.html). +1 on renaming this to hadoop-3 (and probably rename `hadoop-2.7` to `hadoop-2` as well).

**Comment by dongjoon-hyun** [comment]
I retriggered GitHub Action once more.

@srowen and @sunchao . For renaming, shall we do in another PR because it will touch many scripts, too.
- `hadoop-3.2` -> `hadoop-3`
- `hadoop-2.7` -> `hadoop-2`.

**Comment by sunchao** [comment]
This is staled because Spark can't use Hadoop 3.3.0 as it is (see HADOOP-16080). The work may be resumed once Hadoop 3.3.1 is released.

**Comment by dongjoon-hyun** [comment]
Thank you for keeping working on this area.

**Comment by HyukjinKwon** [comment]
👍

**Comment by sunchao** [comment]
Sine Hadoop 3.3.1 RC1 is out, I'm going to revive this PR and test it here.

**Comment by dbtsai** [comment]
Reopening this RP.

**Review by srowen — COMMENTED** [review]
Seems reasonable - just calls into question the "hadoop-3.2" profile name. We could just document that it means "Hadoop 3.2, and later" for now. We could deprecate it and make a new "hadoop-3" profile. Or "hadoop-3.3" separately. I think I'd opt for the former?

**Comment by sunchao** [comment]
@srowen Yes I think we can just document it for now. If the upgrade is successful, I'm inclined to make a new "hadoop-3" profile for the next release (3.2.0?) - probably will send an email to dev first to gather opinions on this.

**Comment by dongjoon-hyun** [comment]
Yay! Thank you, @sunchao .

File: dev/deps/spark-deps-hadoop-3.2-hive-2.3 [hunk 1]
```diff
@@ -58,9 +58,10 @@ flatbuffers-java/1.9.0//flatbuffers-java-1.9.0.jar
 generex/1.0.2//generex-1.0.2.jar
 gson/2.2.4//gson-2.2.4.jar
 guava/14.0.1//guava-14.0.1.jar
-hadoop-client-api/3.2.2//hadoop-client-api-3.2.2.jar
-hadoop-client-runtime/3.2.2//hadoop-client-runtime-3.2.2.jar
-hadoop-yarn-server-web-proxy/3.2.2//hadoop-yarn-server-web-proxy-3.2.2.jar
+hadoop-client-api/3.3.1//hadoop-client-api-3.3.1.jar
+hadoop-client-runtime/3.3.1//hadoop-client-runtime-3.3.1.jar
+hadoop-shaded-guava/1.1.0//hadoop-shaded-guava-1.1.0.jar
```
Comment (dongjoon-hyun) [inline dev/deps/spark-deps-hadoop-3.2-hive-2.3:63]: This is a new dependency?

Comment (sunchao) [reply dev/deps/spark-deps-hadoop-3.2-hive-2.3:63]: Yes - Hadoop 3.3.1 has switched to shaded guava.

Comment (viirya) [reply dev/deps/spark-deps-hadoop-3.2-hive-2.3:63]: nice!

**Comment by viirya** [comment]
We need to remove "Stale" label, otherwise the bot will close it. :)

**Comment by sunchao** [comment]
Thanks @viirya . I was scratching my head on why this happened.

File: core/pom.xml [hunk 2]
```diff
@@ -413,6 +413,16 @@
...
+    <dependency>
+      <groupId>org.bouncycastle</groupId>
+      <artifactId>bcprov-jdk15on</artifactId>
+      <scope>test</scope>
+    </dependency>
+    <dependency>
+      <groupId>org.bouncycastle</groupId>
+      <artifactId>bcpkix-jdk15on</artifactId>
+      <scope>test</scope>
+    </dependency>
```
Comment (dongjoon-hyun) [inline core/pom.xml:425]: Just a question. What happens for `hadoop-2.7` profile? Can we put this under `hadoop-3.2` profile?

File: pom.xml [hunk 3]
```diff
@@ -197,6 +197,7 @@
     <maven-antrun.version>1.8</maven-antrun.version>
     <commons-crypto.version>1.1.0</commons-crypto.version>
     <commons-cli.version>1.2</commons-cli.version>
+    <bouncycastle.version>1.52</bouncycastle.version>
```
Comment (dongjoon-hyun) [inline pom.xml:200]: Although this is a test case, this looks like too old because it's released on Mar, 2015. Do we need to align with to Hadoop 3.3.1? Can we use the latest one `1.68`?
- https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15on

File: core/pom.xml (hunk 2 above)
Comment (sunchao) [reply core/pom.xml:425]: Oops forgot it. Yes I should put it under `hadoop-3.2`.

File: pom.xml (hunk 3 above)
Comment (sunchao) [reply pom.xml:200]: You're right - will change to `1.68`

Comment (sunchao) [reply pom.xml:200]: Actually Hadoop is reverting the change in https://issues.apache.org/jira/browse/HADOOP-17563 so we'll need to wait a bit. cc @steveloughran .

Comment (dbtsai) [reply pom.xml:200]: Wonder why hadoop doesn't shade bouncycastle?

Comment (dongjoon-hyun) [reply pom.xml:200]: Thank you for the pointer, @sunchao . It seems that they found CNFE with HBase due to the incompatibility across that library.

Comment (sunchao) [reply pom.xml:200]: bouncycastle was unshaded in https://issues.apache.org/jira/browse/HADOOP-15832. Reason is: "Leave bouncycastle unshaded because it's signed with a special Oracle certificate so it can be a custom JCE security provider"

Comment (sunchao) [reply pom.xml:200]: To be clear, bouncycastle was also unshaded in Hadoop 3.2.2 which Spark currently use, but since https://issues.apache.org/jira/browse/YARN-8448 it becomes a runtime dependency for RM and therefore required by Spark tests (e.g., `MiniYARNCluster`).

**Comment by dongjoon-hyun** [comment]
Thank you for updates, @sunchao !

**Comment by dongjoon-hyun** [comment]
Interesting. The same test fails in both Jenkins and GitHub Action. Is something changed at this new RC?
- `ClientSuite.distribute jars archive`
```
org.apache.hadoop.fs.PathOperationException: `Source (file:/home/jenkins/workspace/SparkPullRequestBuilder/target/tmp/spark-8a380e11-5074-471e-b9c8-f3f764e2c4e6/testJar948737110654121459.jar) and destination (/home/jenkins/workspace/SparkPullRequestBuilder/target/tmp/spark-8a380e11-5074-471e-b9c8-f3f764e2c4e6/testJar948737110654121459.jar) are equal in the copy command.': Operation not supported
```

**Comment by sunchao** [comment]
@dongjoon-hyun interesting. This is related to https://issues.apache.org/jira/browse/HADOOP-16878, and I thought it's already reverted from RC3 so I reverted my earlier change of handling it in Spark code. Let me check later.

File: pom.xml (hunk 3 above)
Comment (steveloughran) [reply pom.xml]: we rolled back the latest bouncy castle update as some internal spark builds with some extra modules were failing as the asm JAR couldn't handle the changes. Tried to fiddle with the spark settings there to use an updated asm JAR and gave up

**Comment by steveloughran** [comment]
> reverted from RC3 so I reverted my earlier change of handling it in Spark code. Let me check later.

maybe the build is picking up the old RC.

FWIW I'm surprised about this regression...add as much as you can to the test, as in "what is the test trying to do?". Gabor's patch is trying to stop "hadoop fs" copy command from copying a file onto itself, which can be, well, lossy, depending on the OS and things.

**Comment by sunchao** [comment]
> maybe the build is picking up the old RC

Yes that's exactly what happened :)

For the regression, don't know the full context behind the original change but seems like a good thing to do, although a boolean flag returned might be less disruptive IMO :). Either way it is a simple fix from Spark side.

**Comment by steveloughran** [comment]
> For the regression, don't know the full context behind the original change but seems like a good thing to do, although a boolean flag returned might be less disruptive IMO :). Either way it is a simple fix from Spark side.

we didn't think it was going to break things. a big issue is that in come cases the data was being destroyed. I think partly its cleanup code which attempts to delete the dest file on any form of failure, so any kind of transient problem and the shell overreacts by destroying the source.

**Comment by dongjoon-hyun** [comment]
Thank you for updating, @sunchao !

**Comment by dongjoon-hyun** [comment]
Please run `dev/test-dependencies.sh --replace-manifest`. The following is changed.
```
-hadoop-shaded-guava/1.1.0//hadoop-shaded-guava-1.1.0.jar
+hadoop-shaded-guava/1.1.1//hadoop-shaded-guava-1.1.1.jar
```

**Comment by sunchao** [comment]
Thanks. I did run that command but somehow it didn't update the file perhaps due to maven cache. Just updated.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @sunchao , @steveloughran , and all.
GitHub Action passed. Merged to master for Apache Spark 3.2.0.

**Comment by sunchao** [comment]
Thanks @dongjoon-hyun for merging!

**Comment by dongjoon-hyun** [comment]
Hi, All. FYI,

From Apache Hadoop 3.3.1, we reverted HADOOP-16878 as the last commit on `branch-3.3.1`.
- https://github.com/apache/hadoop/commit/a3b9c37a397ad4188041dd80621bdeefc46885f2

However, Apache Spark Jenkins seems to hit a flakiness issue.
- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-master-test-maven-hadoop-3.2/lastCompletedBuild/testReport/org.apache.spark.deploy.yarn/ClientSuite/distribute_jars_archive/history/

```
org.apache.hadoop.fs.PathOperationException: `Source (file:/home/jenkins/workspace/spark-master-test-maven-hadoop-3.2/resource-managers/yarn/target/tmp/spark-703b8e99-63cc-4ba6-a9bc-25c7cae8f5f9/testJar9120517778809167117.jar) and destination (/home/jenkins/workspace/spark-master-test-maven-hadoop-3.2/resource-managers/yarn/target/tmp/spark-703b8e99-63cc-4ba6-a9bc-25c7cae8f5f9/testJar9120517778809167117.jar) are equal in the copy command.': Operation not supported
```

**Comment by dongjoon-hyun** [comment]
Since Apache Hadoop trunk has this behavior, I made a PR in order to be more robust on the underlying behavior difference.
- https://github.com/apache/spark/pull/32983

**Comment by gengliangwang** [comment]
@dongjoon-hyun Thanks for taking care of the error!

**Comment by arghya18** [comment]
What's the latest on this? Any issue to use Hadoop 3.3.1 with Spark?

**Comment by dongjoon-hyun** [comment]
We are preparing Apache Spark 3.2.0 with Hadoop 3.3.1, @arghya18 .
- SPARK-35831 is fixed.
- SPARK-35868 is also fixed.
- SPARK-35878 has the PR from @steveloughran , too.

**Comment by arghya18** [comment]
@dongjoon-hyun Thanks for the info. Actually we are having some major issue related to s3a [HADOOP-17755](https://issues.apache.org/jira/browse/HADOOP-17755) with orc which seems to be solved in Hadoop 3.3.0 for parquet but seems its a common issue . [HADOOP-16109](https://issues.apache.org/jira/browse/HADOOP-16109) . Currently we are working around it using fs.s3a.readahead.range": "1G" which is not a good idea.

I am using Spark on k8s and magic committer, so wanted to check if the above issues mentioned will impact me if I manually build Spark 3.1.1 with Hadoop 3.3.0/3.3.1?

**Comment by dongjoon-hyun** [comment]
Thank you for sharing, @arghya18 . 
HADOOP-17755 sounds like read-side issue and Magic committer is write-side feature. I don't think they are related. If you hit a magic committer issue, please file a JIRA at Apache Hadoop community.

**Comment by arghya18** [comment]
@dongjoon-hyun Thanks for your response. Yes I understand magic committer is not related, I just wanted to understand if I build Spark 3.1.1 with Hadoop 3.3.0/3.3.1 will the existing issues (SPARK-35831, SPARK-35868, SPARK-35878) to be merged will impact my use case? I am using s3a to read and write orc files or I have to wait for Spark 3.2.0 ?

**Comment by steveloughran** [comment]
@arghya18 
1. we havent seen  HADOOP-17755 in any of our testing, unless it is HADOOP-16109
2. still waiting on that JIRA for you to provide config details. Like I've said: no info, we close the JIRA.

> wanted to check if the above issues mentioned will impact me if I manually build Spark 3.1.1 with Hadoop 3.3.0/3.3.1?

well, what can anyone say? without info from you all we can say is WORKSFORME

The best thing you can do to help everyone is checkout and build with Hadoop 3.3.1 (which does contain a lot of changes related to the committers, including from @dongjoon-hyun), and see if the problem is still there.

**Comment by arghya18** [comment]
> The best thing you can do to help everyone is checkout and build with Hadoop 3.3.1 (which does contain a lot of changes related to the committers, including from @dongjoon-hyun), and see if the problem is still there.

@steveloughran Yes that is the plan. I will do and post the details of the result this weekend.

**Comment by steveloughran** [comment]
the parquet EOF fix is also in hadoop-3.2.2, so you could try that. However, testing with 3.3.1 is better because

1. we can do workarounds in spark before the release
2. we can fix hadoop branch-3.3;
3.  any bug you file against hadoop 3.2.x will have "try with 3.3.1" as the initial respose

**Comment by arghya18** [comment]
@steveloughran Thanks for the suggestion. 
Can anyone help me with steps (or Dockerfile) to change hadoop version in prebuilt spark docker image with Hadoop  if available handy for me to quickly progress else I will google, newbie in docker :)

Thanks a lot.

**Comment by arghya18** [comment]
@dongjoon-hyun I was able to test my use case with Hadoop 3.3.1 and posted the result [HADOOP-17755](https://issues.apache.org/jira/browse/HADOOP-17755?focusedCommentId=17373213&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17373213)
To my surprise the read is slower(with same resource and same config) in Hadoop 3.3.1 than Hadoop 3.2.0 without the mentioned issue. It is possible I am missing something.

**Comment by dongjoon-hyun** [comment]
Thank you for sharing, @arghya18 . It's interesting. The read statistic increase is also observed in my environment, but TPCDS 1TB on S3 parquet performance was faster for me. I'll keep tracking HADOOP-17755 together.

**Comment by arghya18** [comment]
@dongjoon-hyun Thanks.. I am testing more jobs for further statistics. BDW I am testing this on ORC.

**Comment by dongjoon-hyun** [comment]
Oh, if you are using ORC, please try to bring SPARK-35783. It's irrelevant to Hadoop, but it helps you reduce the traffic.
- https://github.com/apache/spark/pull/32923

**Comment by arghya18** [comment]
@dongjoon-hyun  Ok.. I will do that but I thought read and time increase is impact of s3a implemented on Hadoop 3.3.1 as that changed only after I upgraded from Hadoop 3.2.0 to Hadoop 3.3.1

**Comment by steveloughran** [comment]
> To my surprise the read is slower(with same resource and same config) in Hadoop 3.3.1 than Hadoop 3.2.0 without the mentioned issue. It is possible I am missing something.

Shouldn't happen. really shouldn't happen. We do not see that on our TCP-DS Benchmarks.

The main way I could see this happening is if the seek policy hasn't switched to random on the first backwards seek. Explicitly set it.

```
spark.hadoop.fs.s3a.experimental.fadvise random
```


Hadoop 3.3.1 has a  stats collection API (IOStatisics) for filesystems, streams, etc. 
* call toString() on a stream to get its stats, inc #of bytes discarded in seeks, streams aborted
* do the same for the FS to get the aggregate stats. 


high counts of bytes discarded and aborts are signs of bad seek policy.    

set these two logs at debug and see what they say.
```
org.apache.hadoop.fs.s3a.S3AInputStream
org.apache.hadoop.fs.s3a.S3AStorageStatistics
```

**Comment by gengliangwang** [comment]
@sunchao @dongjoon-hyun @steveloughran Are there any other known issues of Hadoop 3.3.1? Should we have this upgrade in Spark 3.2?

**Comment by dongjoon-hyun** [comment]
+1 for backporting!

**Comment by sunchao** [comment]
I'm not aware of any issue at the moment - we've already been using this (although a slightly different internal Hadoop version) for a while now. @steveloughran can offer more inputs from Hadoop/S3 side.

Besides that, I wanted to add https://github.com/apache/spark/pull/33160 so that users can build Spark with an older version of Hadoop which do not support shaded client. If people feel this is a good addition I can try to push it to the finish line. I also wanted to add some user documentation on compiling Spark against different versions of Hadoop (besides the default one).

**Comment by steveloughran** [comment]
known 3.3.1 regressions. Not AFAIK

**Comment by gengliangwang** [comment]
@steveloughran Thanks for the info!
@sunchao then let's finish #33160 and have it in 3.2. Thanks!
