### PR TITLE
[SPARK-31655][BUILD][2.4] Upgrade snappy-java to 1.1.7.5

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?

snappy-java have release v1.1.7.5, upgrade to latest version.

Fixed in v1.1.7.4
- Caching internal buffers for SnappyFramed streams #234
- Fixed the native lib for ppc64le to work with glibc 2.17 (Previously it depended on 2.22)

Fixed in v1.1.7.5
- Fixes java.lang.NoClassDefFoundError: org/xerial/snappy/pool/DefaultPoolFactory in 1.1.7.4

https://github.com/xerial/snappy-java/compare/1.1.7.3...1.1.7.5

v 1.1.7.5 release note:
https://github.com/xerial/snappy-java/commit/edc4ec28bdb15a32b6c41ca9e8b195e635bec3a3
### Why are the changes needed?
Fix bug 

### Does this PR introduce _any_ user-facing change?
No 

### How was this patch tested?
No need

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
cc @dongjoon-hyun @maropu

**Comment by HyukjinKwon** [comment]
If we're going to port this back to 2.4, we should do it for 3.0 as well.

**Comment by AngersZhuuuu** [comment]
> If we're going to port this back to 2.4, we should do it for 3.0 as well.

I think we should do that, some user have meeting this problem.

**Comment by AngersZhuuuu** [comment]
retest this please

**Review by dongjoon-hyun — COMMENTED** [review]
Do you think we can have a valid unit test case for this? (non-ppc64le part)

**Comment by maropu** [comment]
@nblxa Could you check if your query could work correctly with this fix? https://github.com/apache/spark/pull/28472

**Comment by AngersZhuuuu** [comment]
Test deps failed since https://github.com/apache/spark/pull/28509#issuecomment-627107421

**Comment by AngersZhuuuu** [comment]
Retest this please

**Comment by maropu** [comment]
retest this please

**Comment by maropu** [comment]
retest this please

**Comment by nblxa** [comment]
@maropu many thanks for backporting this fix! I wasn't expecting such a swift turnaround time :) I regret to say that at the moment I don't know yet when I can be able to test this due to certain constraints on my end. Apologies for that and many thanks again for your work put into this fix.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to branch-2.4. Thanks.

**Comment by maropu** [comment]
Thanks, all!
