### PR TITLE
[SPARK-37205][YARN] Introduce a new config 'spark.yarn.am.tokenConfRegex' to support renewing delegation tokens in a multi-cluster environment

### PR DESCRIPTION
**Pull request by sunchao**
### What changes were proposed in this pull request?

This adds a new config `spark.yarn.am.tokenConfRegex` which is similar to `mapreduce.job.send-token-conf` introduced via [YARN-5910](https://issues.apache.org/jira/browse/YARN-5910). It is used for YARN AM to pass Hadoop configs, such as `dfs.nameservices`, `dfs.ha.namenodes.`, `dfs.namenode.rpc-address.`, etc, to RM for renewing delegation tokens.

### Why are the changes needed?

[YARN-5910](https://issues.apache.org/jira/browse/YARN-5910) introduced a new config `mapreduce.job.send-token-conf` which can be used to pass a job's local configuration to RM which uses them when renewing delegation tokens. A typical use case is when a YARN cluster needs to talk to multiple HDFS clusters, where the RM may not have all the configs (e.g., `dfs.nameservices`, `dfs.ha.namenodes.<nameservice>.*`, `dfs.namenode.rpc-address`) to connect to these clusters when renewing delegation tokens. In this case, the clients can use the feature to pass their local HDFS configs to RM.

### Does this PR introduce _any_ user-facing change?

Yes, a new config `spark.yarn.am.tokenConfRegex` will be introduced to Spark users. By default it is disabled.

### How was this patch tested?

It seems difficult to come up with a unit test for this. I manually tested it against a YARN cluster with Hadoop version 3.x and it worked as expected.

```
$SPARK_HOME/bin/spark-shell --master yarn \
            --deploy-mode client \
            --conf spark.driver.extraClassPath="${HADOOP_CONF_DIR}" \
            --conf spark.executor.extraclasspath="${HADOOP_CONF_DIR}" \
            --conf spark.yarn.am.tokenConfRegex="^dfs.nameservices$|^dfs.namenode.rpc-address.*$|^dfs.ha.namenodes.*$|^dfs.client.failover.proxy.provider.*$|^dfs.namenode.kerberos.principal|^dfs.namenode.kerberos.principal.pattern" \
            --conf spark.yarn.access.hadoopFileSystems="<HDFS_URI>"
```

### CODE REVIEW

**Comment by sunchao** [comment]
cc @gaborgsomogyi @xkrogen

File: resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala [hunk 1]
```diff
@@ -78,6 +78,20 @@ package object config extends Logging {
       .booleanConf
       .createWithDefault(false)
 
+  private[spark] val AM_SEND_TOKEN_CONF =
+    ConfigBuilder("spark.yarn.am.sendTokenConf")
+        .doc("The value of this config is a regex expression used to grep a list of " +
```
Comment (dongjoon-hyun) [inline resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala:83]: indentation?

File: resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala [hunk 2]
```diff
@@ -78,6 +78,20 @@ package object config extends Logging {
...
+          "config entries from the job's configuration file (e.g., hdfs-site.xml) and send to " +
+          "RM, which uses them when renewing delegation tokens. A typical use case of " +
+          "this feature is to support delegation tokens in an environment where a YARN cluster " +
+          "needs to talk to multiple downstream HDFS clusters, where the YARN RM may not have " +
+          "configs (e.g., dfs.nameservices, dfs.ha.namenodes.*, dfs.namenode.rpc-address.*)" +
+          "to connect to these clusters. This config is very similar to " +
+          "'mapreduce.job.send-token-conf'. Please check YARN-5910 for more details.")
+        .version("3.3.0")
+        .stringConf
+        .createWithDefault("")
```
Comment (dongjoon-hyun) [inline resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala:93]: Since this is a regex expression, what does `empty string regex` mean here as a default value?

Comment (dongjoon-hyun) [reply resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala:93]: If it's not clear, shall we use `.createOptional`?

File: resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala [hunk 3]
```diff
@@ -78,6 +78,20 @@ package object config extends Logging {
...
+  private[spark] val AM_SEND_TOKEN_CONF =
+    ConfigBuilder("spark.yarn.am.sendTokenConf")
+        .doc("The value of this config is a regex expression used to grep a list of " +
+          "config entries from the job's configuration file (e.g., hdfs-site.xml) and send to " +
+          "RM, which uses them when renewing delegation tokens. A typical use case of " +
+          "this feature is to support delegation tokens in an environment where a YARN cluster " +
+          "needs to talk to multiple downstream HDFS clusters, where the YARN RM may not have " +
+          "configs (e.g., dfs.nameservices, dfs.ha.namenodes.*, dfs.namenode.rpc-address.*)" +
+          "to connect to these clusters. This config is very similar to " +
+          "'mapreduce.job.send-token-conf'. Please check YARN-5910 for more details.")
```
Comment (dongjoon-hyun) [inline resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala:90]: We had better mention explicitly that this config is ignored in Hadoop 2.7 because we still have Hadoop 2.7 distribution.

File: resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala [hunk 4]
```diff
@@ -78,6 +78,20 @@ package object config extends Logging {
       .booleanConf
       .createWithDefault(false)
 
+  private[spark] val AM_SEND_TOKEN_CONF =
+    ConfigBuilder("spark.yarn.am.sendTokenConf")
```
Comment (dongjoon-hyun) [inline resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala:82]: nit.`spark.yarn.am.tokenConf` instead `spark.yarn.am.sendTokenConf`? `sendTokenConf` sounds like a boolean config like `send` or `not send`.

File: resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/Client.scala [hunk 5]
```diff
@@ -340,6 +340,30 @@ private[spark] class Client(
...
+      val copy = new Configuration(false);
+      copy.clear();
+      hadoopConf.asScala.foreach { entry =>
+        if (entry.getKey.matches(regex)) {
+          copy.set(entry.getKey, entry.getValue)
+          logInfo(s"Captured key: ${entry.getKey} -> value: ${entry.getValue}")
+        }
+      }
+      copy.write(dob);
+      amContainer.setTokensConf(ByteBuffer.wrap(dob.getData))
```
Comment (dongjoon-hyun) [inline resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/Client.scala:363]: Just a question. The compilation works with Hadoop 2.7, right?

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you, @sunchao . It looks reasonable.

Sorry, but I need to ask if you think we can add a test coverage for this.

File: resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/Client.scala (hunk 5 above)
Comment (sunchao) [reply resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/Client.scala:363]: Oops, it won't work for Hadoop 2.7. Hmm let me think how to make it work ..

Comment (sunchao) [reply resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/Client.scala:363]: I guess we can follow `ResourceRequestHelper` and use reflection to lookup the method when using Hadoop 3.x, to avoid compilation error.

File: resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala (hunk 2 above)
Comment (sunchao) [reply resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala:93]: Good suggestion. I think `createOptional` is better.

File: resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala (hunk 1 above)
Comment (sunchao) [reply resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala:83]: Fixed.

File: resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala (hunk 3 above)
Comment (sunchao) [reply resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala:90]: Yea I missed that, added.

File: resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala (hunk 4 above)
Comment (sunchao) [reply resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala:82]: I don't know what is a good name for this and just followed the Hadoop side config name. `send` here is supposed to mean that the token conf is sent from AM to RM

**Comment by sunchao** [comment]
> Sorry, but I need to ask if you think we can add a test coverage for this.

I mentioned a bit in the PR description. It's pretty hard to come up with a e2e test for this esp. with kerberos involved. I checked a few related PRs such as #31761 and #23525 and they also didn't come with tests.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. I agree with you about the test case. Thanks, @sunchao .

File: resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/Client.scala [hunk 6]
```diff
@@ -340,6 +344,40 @@ private[spark] class Client(
...
+      copy.clear();
+      hadoopConf.asScala.foreach { entry =>
+        if (entry.getKey.matches(regex.get)) {
+          copy.set(entry.getKey, entry.getValue)
+          logInfo(s"Captured key: ${entry.getKey} -> value: ${entry.getValue}")
+        }
+      }
+      copy.write(dob);
+
+      // since this method was added in Hadoop 2.9 and 3.0, we use reflection here to avoid
```
Comment (mridulm) [inline resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/Client.scala:368]: Are we doing this only for 3.x ? If not, relax the `isHadoop3` condition ?

File: resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala [hunk 7]
```diff
@@ -78,6 +78,20 @@ package object config extends Logging {
...
+      .doc("This config is only supported for Hadoop 3.x profile. The value of this config is a " +
+        "regex expression used to grep a list of config entries from the job's configuration " +
+        "file (e.g., hdfs-site.xml) and send to RM, which uses them when renewing delegation " +
+        "tokens. A typical use case of this feature is to support delegation tokens in an " +
+        "environment where a YARN cluster needs to talk to multiple downstream HDFS clusters, " +
+        "where the YARN RM may not have configs (e.g., dfs.nameservices, dfs.ha.namenodes.*, " +
+        "dfs.namenode.rpc-address.*) to connect to these clusters. This config is very similar " +
+        "to 'mapreduce.job.send-token-conf'. Please check YARN-5910 for more details.")
```
Comment (mridulm) [inline resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala:90]: nit: In the example, also add what the config value would be for the three configs listed ? This will help users adapt the config to their env easier - something like: `(^dfs.nameservices$)|(^dfs.ha.namenodes.*$)|(^dfs.namenode.rpc-address.*$)` ...

File: resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala (hunk 4 above)
Comment (mridulm) [reply resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala:82]: Use `regexConf` ? 
Also, add `.regex` to config name ? (in addition to @dongjoon-hyun's suggestion for rename).

File: resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/Client.scala (hunk 6 above)
Comment (sunchao) [reply resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/Client.scala:368]: Yes, since Spark only supports built-in Hadoop 2.7 or 3.3, we have the check here. Do you mean support custom Hadoop version 2.9+ too with `-Phadoop.version=2.9.x`?

File: resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala (hunk 7 above)
Comment (sunchao) [reply resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala:90]: Good suggestion. Will add.

File: resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala (hunk 4 above)
Comment (sunchao) [reply resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala:82]: Thanks, I updated the config name to `spark.yarn.am.tokenConfRegex`. Let me know if this looks better.

File: resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/Client.scala (hunk 6 above)
Comment (mridulm) [reply resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/Client.scala:368]: Exactly - both 2.9 and 2.10 for example.

**Comment by dongjoon-hyun** [comment]
Could you review this once more please, @mridulm ?

File: resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/Client.scala (hunk 6 above)
Comment (sunchao) [reply resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/Client.scala:374]: Got it. I added the change.

Comment (sunchao) [reply resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/Client.scala:374]: Gently ping @mridulm . Does the latest change look good to you?

**Comment by sunchao** [comment]
@dongjoon-hyun could you help to double check the new changes and see if they look good to you? if so I'm going to merge this soon. Thanks.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. New changes look good to me, @sunchao .

**Comment by sunchao** [comment]
Merged, thanks!
