### PR TITLE
[SPARK-15515] [SQL] Error Handling in Running SQL Directly On Files

### PR DESCRIPTION
**Pull request by gatorsmile**
#### What changes were proposed in this pull request?

This PR is to address the following issues: 
- **ISSUE 1:** For ORC source format, we are reporting the strange error message when we did not enable Hive support: 

``` SQL
SQL Example: 
  select id from `org.apache.spark.sql.hive.orc`.`file_path`
Error Message:
  Table or view not found: `org.apache.spark.sql.hive.orc`.`file_path`
```

Instead, we should issue the error message like:

```
Expected Error Message:
   The ORC data source must be used with Hive support enabled
```
- **ISSUE 2:** For the Avro format, we report the strange error message like:

The example query is like

``` SQL
SQL Example: 
  select id from `avro`.`file_path`
  select id from `com.databricks.spark.avro`.`file_path`
Error Message:
  Table or view not found: `com.databricks.spark.avro`.`file_path`
```

The desired message should be like:

```
Expected Error Message:
  Failed to find data source: avro. Please use Spark package http://spark-packages.org/package/databricks/spark-avro"
```
- ~~**ISSUE 3:** Unable to detect incompatibility libraries for Spark 2.0 in Data Source Resolution. We report a strange error message:~~

**Update**: The latest code changes contains 
- For JDBC format, we added an extra checking in the rule `ResolveRelations` of `Analyzer`. Without the PR, Spark will return the error message like: `Option 'url' not specified`. Now, we are reporting `Unsupported data source type for direct query on files: jdbc` 
- Make data source format name case incensitive so that error handling behaves consistent with the normal cases. 
- Added the test cases for all the supported formats. 
#### How was this patch tested?

Added test cases to cover all the above issues

### CODE REVIEW

**Comment by gatorsmile** [comment]
Just realized this PR is related to https://github.com/apache/spark/pull/13201. Also tried to improve the exception reporting in Python through hiding the long java stack trace. 

@zsxwing @marmbrus Could you please help me review the changes? Thanks!

**Comment by rxin** [comment]
Just want to say --- this is a really cool change!

(I didn't actually look at the details. Would be great for somebody else to do a detailed review.)

**Comment by gatorsmile** [comment]
Thank you!

File: sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/DataSource.scala [hunk 1]
```diff
@@ -132,12 +131,11 @@ case class DataSource(
...
         } catch {
-          case e: NoClassDefFoundError => // This one won't be caught by Scala NonFatal
-            // NoClassDefFoundError's class name uses "/" rather than "." for packages
-            val className = e.getMessage.replaceAll("/", ".")
-            if (spark2RemovedClasses.contains(className)) {
-              throw new ClassNotFoundException(s"$className was removed in Spark 2.0. " +
-                "Please check if your library is compatible with Spark 2.0", e)
+          case e: NoClassDefFoundError =>
+            // e.getMessage is the class name of provider2. Instead, we use provider here.
+            if (spark2RemovedClasses.contains(provider)) {
```
Comment (zsxwing) [inline sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/DataSource.scala]: In my previous PR, I want to provide a better message for e.g., `org.apache.spark.sql.DataFrame` not found. It usually happens when calling some method (has a `org.apache.spark.sql.DataFrame` parameter) in a class that is compiled with an old Spark. Obviously, here `provider` won't be `org.apache.spark.sql.DataFrame`.

Comment (zsxwing) [inline sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/DataSource.scala]: You should not change this. If `provider` is not found, `loadClass` will throw `ClassNotFoundException`. If a class used by provider are not found, `NoClassDefFoundError` will be thrown.

**Comment by zsxwing** [comment]
> ISSUE 3: Unable to detect incompatibility libraries for Spark 2.0 in Data Source Resolution. We report a strange error message:
> SQL Example:
>   select id from `org.apache.spark.sql.sources.HadoopFsRelationProvider`.`file_path`
> Error Message: 
>   Table or view not found: `org.apache.spark.sql.sources.HadoopFsRelationProvider`.`file_path`

This is not an issue you need to fix. `HadoopFsRelationProvider` is just an interface in Spark 1.6. The user should not use it like this. If someone sees HadoopFsRelationProvider is not found, it's usually a link issue. E.g., `com.databricks.spark.avro.DefaultSource` extends `HadoopFsRelationProvider`, however, `HadoopFsRelationProvider` has been removed in 2.0, so when loading `com.databricks.spark.avro.DefaultSource`, it will throw `NoClassDefFoundError(HadoopFsRelationProvider)` instead of `ClassNotFoundException(com.databricks.spark.avro.DefaultSource)`

File: sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/DataSource.scala (hunk 1 above)
Comment (gatorsmile) [inline sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/DataSource.scala]: Will revert the changes for `NoClassDefFoundError`. Thanks!

**Comment by zsxwing** [comment]
@gatorsmile I saw it reports `org.apache.spark.sql.AnalysisException: Failed to find data source: mydatabase. Please find packages at http://spark-packages.org;; line 1 pos 15` for the following statement: `sql("select id from `mydatabase`.`file_path`")`. I'm not familiar with the table name resolution. Is it correct?

File: sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/DataSource.scala [hunk 2]
```diff
@@ -108,21 +108,20 @@ case class DataSource(
               dataSource
             case Failure(error) =>
               if (error.isInstanceOf[ClassNotFoundException]) {
-                val className = error.getMessage
-                if (spark2RemovedClasses.contains(className)) {
-                  throw new ClassNotFoundException(s"$className is removed in Spark 2.0. " +
+                // error.getMessage is the class name of provider2. Instead, we use provider here.
```
Comment (zsxwing) [inline sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/DataSource.scala]: In a second thought, I don't think we need this `if` branch. Could you just remove it?

Comment (zsxwing) [inline sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/DataSource.scala]: This is for link issues. But it will be `NoClassDefFoundError`

File: python/pyspark/sql/utils.py [hunk 3]
```diff
@@ -77,6 +83,8 @@ def deco(*a, **kw):
                 raise QueryExecutionException(s.split(': ', 1)[1], stackTrace)
             if s.startswith('java.lang.IllegalArgumentException: '):
                 raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace)
+            if s.startswith('java.lang.NoClassDefFoundError: '):
```
Comment (zsxwing) [inline python/pyspark/sql/utils.py]: The Python changes are not necessary. Right?

File: sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/DataSource.scala (hunk 2 above)
Comment (gatorsmile) [inline sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/DataSource.scala]: Sure, will do it. Thanks!

File: python/pyspark/sql/utils.py (hunk 3 above)
Comment (gatorsmile) [inline python/pyspark/sql/utils.py]: I think it is still helpful. This is to hide the long java stack trace for improving the error reporting. It was introduced in the PR https://github.com/apache/spark/pull/7135.

Comment (zsxwing) [inline python/pyspark/sql/utils.py]: `NoClassDefFoundError` rarely happens unless we miss something in `spark2RemovedClasses`. Hiding it makes us hard to figure out the real place quickly.

Comment (gatorsmile) [inline python/pyspark/sql/utils.py]: uh, I see. Will revert it back. Thanks!

**Comment by gatorsmile** [comment]
It sounds like we need to verify all the possible source types we can support. Let me add them. Thanks!

**Comment by gatorsmile** [comment]
**Update**: The latest code changes contains 
- For JDBC format, we added an extra checking in the rule `ResolveRelations` of `Analyzer`. Without the PR, Spark will return the error message like: `Option 'url' not specified`. Now, we are reporting `Unsupported data source type for direct query on files: jdbc` 
- Make data source format name case incensitive so that error handling behaves consistent with the normal cases. 
- Added the test cases for all the supported formats.

**Comment by gatorsmile** [comment]
@zsxwing Now, code is ready for review. Thanks!

File: sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/Analyzer.scala [hunk 4]
```diff
@@ -448,6 +448,14 @@ class Analyzer(
       }
     }
 
+    /**
+     * Data source formats that were not supported in direct query on file
+     */
+    private final val unsupportedFileQuerySource = Set(
+      "org.apache.spark.sql.jdbc",
```
Comment (zsxwing) [inline sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/Analyzer.scala]: Not sure about this. Looks hard to maintain. E.g., you forget to add `JdbcRelationProvider`. @rxin What do you think?

Comment (marmbrus) [inline sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/Analyzer.scala]: Can we just check to see if it extends `FileFormat`?

Comment (gatorsmile) [inline sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/Analyzer.scala]: @zsxwing @marmbrus Agree. It is hard to maintain the list. First, will add the missing class names to the list.

To implement what @marmbrus suggested, I think we need to do the following:

 - Users' input are not full class names. To dynamically load the class, we still need to have a list like:
https://github.com/apache/spark/blob/361ebc282b2d09dc6dcf21419a53c5c617b1b6bd/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/DataSource.scala#L80-L108
To avoid duplicating the codes, we need to move this list to a place both `Analyzer` and `DataSource` can access. Any suggestion here?

 - Dynamically loading the class and check whether the class extends `FileFormat`. We need to do something similar like https://github.com/apache/spark/blob/361ebc282b2d09dc6dcf21419a53c5c617b1b6bd/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/DataSource.scala#L128-L132

 - To avoid duplicate the codes, when unable to loading the class, we still follow the existing way to handle it. That is, returns the `UnresolvedRelation` `u`. 

Is my understanding right?

Thank you for your suggestions!

Comment (marmbrus) [inline sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/Analyzer.scala]: Couldn't the logic go in `ResolveDataSource`?

Comment (gatorsmile) [inline sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/Analyzer.scala]: : ) Yeah. Let me try it. Thank you!

**Comment by gatorsmile** [comment]
@zsxwing @marmbrus How about the latest code changes? Let me know if anything I can further improve. Thanks!

File: sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/rules.scala [hunk 5]
```diff
@@ -38,6 +38,10 @@ private[sql] class ResolveDataSource(sparkSession: SparkSession) extends Rule[Lo
           sparkSession,
           paths = u.tableIdentifier.table :: Nil,
           className = u.tableIdentifier.database.get)
+        if (dataSource.isFileFormat() == Option(false)) {
```
Comment (zsxwing) [inline sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/rules.scala]: `isFileFormat` is not necessary. You can use `providingClass` like this:

```Scala
        val notSupportDirectQuery = try {
          !classOf[FileFormat].isAssignableFrom(dataSource.providingClass)
        } catch {
          case NonFatal(e) => false
        }
        if (notSupportDirectQuery) {
          throw new AnalysisException("Unsupported data source type for direct query on files: " +
            s"${u.tableIdentifier.database.get}")
        }
```

Comment (gatorsmile) [inline sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/rules.scala]: Thank you very much! Will use your version! It is much better. Thanks again!

**Comment by gatorsmile** [comment]
@zsxwing @marmbrus Any remaining issue? Thanks!

**Comment by zsxwing** [comment]
LGTM. Merging to master and 2.0. Thanks!

File: sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/rules.scala [hunk 6]
```diff
@@ -38,6 +40,16 @@ private[sql] class ResolveDataSource(sparkSession: SparkSession) extends Rule[Lo
           sparkSession,
           paths = u.tableIdentifier.table :: Nil,
           className = u.tableIdentifier.database.get)
+
+        val notSupportDirectQuery = try {
+          !classOf[FileFormat].isAssignableFrom(dataSource.providingClass)
+        } catch {
+          case NonFatal(e) => false
```
Comment (tedyu) [inline sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/rules.scala]: When would this happen ?

Should true be returned here ?

Comment (zsxwing) [inline sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/rules.scala]: @tedyu If people use `select * from db_name.table_name`, it will throw an exception. Still need to continue for such cases.

Comment (tedyu) [inline sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/rules.scala]: Thanks Ryan.
