### PR TITLE
[SPARK-17985][CORE] Bump commons-lang3 version to 3.5.

### PR DESCRIPTION
**Pull request by ueshin**
## What changes were proposed in this pull request?

`SerializationUtils.clone()` of commons-lang3 (<3.5) has a bug that breaks thread safety, which gets stack sometimes caused by race condition of initializing hash map.
See https://issues.apache.org/jira/browse/LANG-1251.
## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by ueshin** [comment]
Jenkins, retest this please.

**Comment by srowen** [comment]
I think this is OK. The general issue is whether it will be compatible with other transitive dependencies, but I believe it would remain so.

**Review by srowen — APPROVED** [review]

**Comment by rxin** [comment]
Merging in master.

**Comment by rxin** [comment]
Actually I'm seeing the following exceptions locally as well as on Jenkins for Hadoop 2.2:

```
[error] /scratch/rxin/spark/core/src/main/scala/org/apache/spark/util/Utils.scala:1489: value read is not a member of object org.apache.commons.io.IOUtils
[error]       var numBytes = IOUtils.read(gzInputStream, buf)
[error]                              ^
[error] /scratch/rxin/spark/core/src/main/scala/org/apache/spark/util/Utils.scala:1492: value read is not a member of object org.apache.commons.io.IOUtils
[error]         numBytes = IOUtils.read(gzInputStream, buf)
[error]                            ^
```

I'm going to revert the patch for now.

**Comment by ueshin** [comment]
@rxin I think the failure is not related to this PR.
The build for hadoop-2.2 is failing after reverted.
https://amplab.cs.berkeley.edu/jenkins/job/spark-master-test-sbt-hadoop-2.2/1948/console

Looks `IOUtils` is introduced by 231f39e3f6641953a90bc4c40444ede63f363b23 (#15285), and fixing is on progress at #15537.

**Comment by rxin** [comment]
Ah alright thanks. Can you submit a new pr so I can merge it again?

**Comment by ueshin** [comment]
I see. I'll submit soon.

**Comment by ueshin** [comment]
@rxin I submitted a new pr #15548. Thanks.
