### PR TITLE
[SPARK-40598][PS] Fix plotting features work properly with pandas 1.5.0.

### PR DESCRIPTION
**Pull request by itholic**
### What changes were proposed in this pull request?

This PR proposes to fix the plotting functions working properly with pandas 1.5.0.

This includes two fixes:
- Fix the `PandasOnSpark*Plot` to get name of plot in the string format properly.
- Fix the default value of `subplots` parameter from `plot_frame` to match with latest pandas. (`None` -> `False`)

#### 1. get `_kind` from pandas class no longer possible.

We're leverage the pandas plotting classes to implement for `matplotlib` implementation, and get the class name from pandas like:
```python
>>> from pandas.plotting._matplotlib.core import AreaPlot
>>> AreaPlot._kind
'area'
```
However, since pandas 1.5.0, they convert the member variable `_kind` into `@property`, so we cannot bring the name of class properly from pandas class as below:
```python
>>> from pandas.plotting._matplotlib.core import AreaPlot
AreaPlot._kind
>>> AreaPlot._kind
<property object at 0x7fe520d749a0>
```

#### 2. `subplots` parameter no longer allow the type other than `Iterable` or `bool`.

We internally set the default value for `subplots` as `None`, but from pandas 1.5.0 only allows `Iterable` or `bool`, so the plotting function is not work properly as below:

```python
>>> psdf.plot(kind="bar")
Traceback (most recent call last):
...
ValueError: subplots should be a bool or an iterable
```

With this fixes, it work properly with pandas 1.5.0 as below:

**<For Series and DataFrame plot>**

**Before**:
```python
>>> from pyspark.pandas.config import set_option
>>> set_option("plotting.backend", "matplotlib")
>>> import pyspark.pandas as ps
>>> psdf = ps.range(10)
>>> psdf.plot(kind="bar")
Traceback (most recent call last):
...
KeyError: 'bar'
```

**After**:
```python
>>> from pyspark.pandas.config import set_option
>>> set_option("plotting.backend", "matplotlib")
>>> import pyspark.pandas as ps
>>> psdf = ps.range(10)
>>> psdf.plot(kind="bar")
<AxesSubplot:>
```

**<For DataFrame plot>**

**Before**:
```python
>>> from pyspark.pandas.config import set_option
>>> set_option("plotting.backend", "matplotlib")
>>> import pyspark.pandas as ps
>>> psdf = ps.range(10)
>>> psdf.plot(kind="bar")
Traceback (most recent call last):
...
ValueError: subplots should be a bool or an iterable
```

**After**:
```python
>>> from pyspark.pandas.config import set_option
>>> set_option("plotting.backend", "matplotlib")
>>> import pyspark.pandas as ps
>>> psdf = ps.range(10)
>>> psdf.plot(kind="bar")
<AxesSubplot:>
```

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Manually tested with pandas 1.5.0.

### CODE REVIEW

**Comment by xinrong-meng** [comment]
I am wondering if we shall rely on `super()._kind` rather than hardcode `_kind`.

**Comment by xinrong-meng** [comment]
Shall we follow pandas to make `_kind` a `property`?

**Comment by itholic** [comment]
> I am wondering if we shall rely on `super()._kind` rather than hardcode `_kind`.

Here, the parents for `PandasOnSpark*Plot` are `Pandas*Plot` and `*PlotBase`, so I think it may not possible apply the `super()`?

**Comment by zhengruifeng** [comment]
this regression is `matplotlib`-only? do we need to also fix `plotly`

after this fix, do it still works with pandas 1.4.x?

**Comment by itholic** [comment]
Yes, the regression is detected only from `matplotlib`.

`plotly` works fine :-)

And yes, it works fine with pandas 1.4.x as CI passes for now.

**Comment by xinrong-meng** [comment]
I was thinking something as below, in order to be consistent with pandas and avoid the hardcoding
```
>>> class C:
...   @property
...   def _kind(self):
...     return 'area'
... 
>>> class D:
...   pass
...
>>> class PS_C(C, D):  # pandas-on-Spark class
...   @property
...   def _kind(self):
...     return super()._kind
... 
```
Then we may change `_plot_klass = {getattr(klass(), "_kind"): klass for klass in _klasses}`

**Comment by itholic** [comment]
I think maybe this example is not working in our case because our case requires parameter when initialize the `klass` ??

It may throw the exception such as:
```python
>>> {getattr(klass(), "_kind"): klass for klass in _klasses}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <dictcomp>
TypeError: __init__() missing 1 required positional argument: 'data'
```

So, I think maybe we might need to class member because it's not able to get a class name from the property.

@xinrong-meng Could you let me know if I missing something? 🙏

**Comment by xinrong-meng** [comment]
Makes sense! Class member approach looks fine. Thanks for explaining that! LGTM.

**Review by xinrong-meng — APPROVED** [review]

**Comment by xinrong-meng** [comment]
Thanks! Merged to master.
