### PR TITLE
[SPARK-19810][BUILD][CORE] Remove support for Scala 2.10

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

- Remove Scala 2.10 build profiles and support
- Replace some 2.10 support in scripts with commented placeholders for 2.12 later
- Remove deprecated API calls from 2.10 support 
- Remove usages of deprecated context bounds where possible
- Remove Scala 2.10 workarounds like ScalaReflectionLock
- Other minor Scala warning fixes

## How was this patch tested?

Existing tests

### CODE REVIEW

File: R/pkg/DESCRIPTION [hunk 1]
```diff
@@ -54,5 +54,5 @@ Collate:
     'types.R'
     'utils.R'
     'window.R'
-RoxygenNote: 5.0.1
+RoxygenNote: 6.0.1
```
Comment (srowen) [inline R/pkg/DESCRIPTION]: (Will fix this -- need to probably make the build stop changing this)

File: core/src/main/scala/org/apache/spark/SparkContext.scala [hunk 2]
```diff
@@ -1391,8 +1391,9 @@ class SparkContext(config: SparkConf) extends Logging {
    * standard mutable collections. So you can use this with mutable Map, Set, etc.
    */
   @deprecated("use AccumulatorV2", "2.0.0")
-  def accumulableCollection[R <% Growable[T] with TraversableOnce[T] with Serializable: ClassTag, T]
-      (initialValue: R): Accumulable[R, T] = {
+  def accumulableCollection[R : ClassTag, T](initialValue: R)
```
Comment (srowen) [inline core/src/main/scala/org/apache/spark/SparkContext.scala]: This and the `SequenceFileRDDFunctions` change are the only questionable ones. This should be the equivalent declaration that context bounds desugar into, but the question is whether this actually induces an obscure API change.

File: core/src/main/scala/org/apache/spark/ui/JettyUtils.scala [hunk 3]
```diff
@@ -66,7 +66,7 @@ private[spark] object JettyUtils extends Logging {
   implicit def textResponderToServlet(responder: Responder[String]): ServletParams[String] =
     new ServletParams(responder, "text/plain")
 
-  def createServlet[T <% AnyRef](
+  def createServlet[T <: AnyRef](
```
Comment (srowen) [inline core/src/main/scala/org/apache/spark/ui/JettyUtils.scala]: These didn't need to be context bounds in the first place

File: dev/change-version-to-2.11.sh [hunk 4]
```diff
@@ -1,23 +0,0 @@
-#!/usr/bin/env bash
```
Comment (srowen) [inline dev/change-version-to-2.11.sh]: These scripts were deprecated wrappers

**Comment by srowen** [comment]
The context bound changes won't work on the two public methods:

```
[error]  * deprecated method accumulableCollection(java.lang.Object,scala.Function1,scala.reflect.ClassTag)org.apache.spark.Accumulable in class org.apache.spark.SparkContext's type is different in current version, where it is (java.lang.Object,scala.reflect.ClassTag,scala.Function1)org.apache.spark.Accumulable instead of (java.lang.Object,scala.Function1,scala.reflect.ClassTag)org.apache.spark.Accumulable
[error]    filter with: ProblemFilters.exclude[IncompatibleMethTypeProblem]("org.apache.spark.SparkContext.accumulableCollection")
[error]  * method this(org.apache.spark.rdd.RDD,java.lang.Class,java.lang.Class,scala.Function1,scala.reflect.ClassTag,scala.Function1,scala.reflect.ClassTag)Unit in class org.apache.spark.rdd.SequenceFileRDDFunctions's type is different in current version, where it is (org.apache.spark.rdd.RDD,java.lang.Class,java.lang.Class,scala.reflect.ClassTag,scala.reflect.ClassTag,scala.Function1,scala.Function1)Unit instead of (org.apache.spark.rdd.RDD,java.lang.Class,java.lang.Class,scala.Function1,scala.reflect.ClassTag,scala.Function1,scala.reflect.ClassTag)Unit
[error]    filter with: ProblemFilters.exclude[IncompatibleMethTypeProblem]("org.apache.spark.rdd.SequenceFileRDDFunctions.this")
```

Quite unfortunately, they generate signatures that take the same arguments but in differing orders. This bit is one of those tiny breaking changes that will have to wait for Spark 3.x. As I recall they still work in Scala 2.12, even though they are deprecated.

File: bin/load-spark-env.cmd [hunk 5]
```diff
@@ -35,21 +35,21 @@ if [%SPARK_ENV_LOADED%] == [] (
 
 rem Setting SPARK_SCALA_VERSION if not already set.
 
-set ASSEMBLY_DIR2="%SPARK_HOME%\assembly\target\scala-2.11"
-set ASSEMBLY_DIR1="%SPARK_HOME%\assembly\target\scala-2.10"
+rem set ASSEMBLY_DIR2="%SPARK_HOME%\assembly\target\scala-2.11"
+rem set ASSEMBLY_DIR1="%SPARK_HOME%\assembly\target\scala-2.12"
```
Comment (srowen) [inline bin/load-spark-env.cmd]: I commented bits like this out, but updated it as well for when 2.12 needs to be supported as an alternative

File: dev/create-release/release-build.sh [hunk 6]
```diff
@@ -342,16 +342,13 @@ if [[ "$1" == "publish-release" ]]; then
...
-  $MVN -DzincPort=$ZINC_PORT -Dmaven.repo.local=$tmp_repo -Dscala-2.10 \
-    -DskipTests $PUBLISH_PROFILES clean install
+  #./dev/change-scala-version.sh 2.12
+  #$MVN -DzincPort=$ZINC_PORT -Dmaven.repo.local=$tmp_repo -Pscala-2.12 \
+  #  -DskipTests $PUBLISH_PROFILES clean install
 
   # Clean-up Zinc nailgun process
   /usr/sbin/lsof -P |grep $ZINC_PORT | grep LISTEN | awk '{ print $2; }' | xargs kill
 
-  ./dev/change-version-to-2.10.sh
```
Comment (srowen) [inline dev/create-release/release-build.sh]: This was redundant with the line 8 lines above

**Comment by jiangxb1987** [comment]
gently ping @srowen

**Comment by srowen** [comment]
@jiangxb1987 this can't be merges until 2.2 is released. It is open on purpose.

**Comment by fbascheper** [comment]
I just noticed that spark 2.2.0 was released yesterday. Is this the right time to move on with this PR?

**Comment by srowen** [comment]
@fbascheper of course. I'm about to rebase this branch to prepare the final change

File: R/pkg/R/sparkR.R [hunk 7]
```diff
@@ -357,7 +357,7 @@ sparkRHive.init <- function(jsc = NULL) {
 #' sparkR.session("yarn-client", "SparkR", "/home/spark",
 #'                list(spark.executor.memory="4g"),
 #'                c("one.jar", "two.jar", "three.jar"),
-#'                c("com.databricks:spark-avro_2.10:2.0.1"))
+#'                c("com.databricks:spark-avro_2.11:2.0.1"))
```
Comment (srowen) [inline R/pkg/R/sparkR.R]: These changes to dummy artifacts used in examples aren't that important, but figured it'd be tidy

File: build/mvn [hunk 8]
```diff
@@ -91,13 +91,13 @@ install_mvn() {
 
 # Install zinc under the build/ folder
 install_zinc() {
-  local zinc_path="zinc-0.3.11/bin/zinc"
+  local zinc_path="zinc-0.3.15/bin/zinc"
```
Comment (srowen) [inline build/mvn]: I went ahead and updated zinc along the way here

File: core/src/main/scala/org/apache/spark/rpc/RpcTimeout.scala [hunk 9]
```diff
@@ -125,9 +125,9 @@ private[spark] object RpcTimeout {
     var foundProp: Option[(String, String)] = None
     while (itr.hasNext && foundProp.isEmpty) {
       val propKey = itr.next()
-      conf.getOption(propKey).foreach { prop => foundProp = Some(propKey, prop) }
+      conf.getOption(propKey).foreach { prop => foundProp = Some((propKey, prop)) }
```
Comment (srowen) [inline core/src/main/scala/org/apache/spark/rpc/RpcTimeout.scala]: Lots of the changes are of this form. Whereas scalac will still accept two args to a method that accepts one Tuple2 arg, it's a warning in Scala 2.11 in some cases. I actually also enabled all warnings of this form.

File: pom.xml [hunk 10]
```diff
@@ -1987,6 +1988,8 @@
               <arg>-unchecked</arg>
               <arg>-deprecation</arg>
               <arg>-feature</arg>
+              <arg>-explaintypes</arg>
```
Comment (srowen) [inline pom.xml]: explaintypes gives some better error messages in 2.11, so went ahead and turned it on

File: sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/ScalaReflection.scala [hunk 11]
```diff
@@ -329,8 +328,8 @@ object ScalaReflection extends ScalaReflection {
           }
         }
 
-        val companion = t.normalize.typeSymbol.companionSymbol.typeSignature
-        val cls = companion.member(newTermName("newBuilder")) match {
+        val companion = t.dealias.typeSymbol.companion.typeSignature
```
Comment (srowen) [inline sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/ScalaReflection.scala]: This should be the right replacement for the deprecated methods, given scaladoc comments, but I admit this one I am not 100% sure about

**Comment by fbascheper** [comment]
I just noticed that one test was skipped in the test build. That's on purpose I presume. See https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/79559/testReport/org.apache.spark.kvstore/

**Comment by srowen** [comment]
@fbascheper that looks like it's disabled in the source code. It's nothing to do with this branch or change

**Review by vanzin — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM, too.

**Comment by ueshin** [comment]
I guess we can also remove thread safety tests at the bottom of `org.apache.spark.sql.catalyst.ScalaReflectionSuite` ([ScalaReflectionSuite.scala#L341-L376](https://github.com/srowen/spark/blob/8e850395e3e64609f65254b7b241fb8ab121c283/sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/ScalaReflectionSuite.scala#L341-L376)).

File: core/src/main/scala/org/apache/spark/SparkContext.scala [hunk 12]
```diff
@@ -1396,6 +1387,8 @@ class SparkContext(config: SparkConf) extends Logging {
   @deprecated("use AccumulatorV2", "2.0.0")
   def accumulableCollection[R <% Growable[T] with TraversableOnce[T] with Serializable: ClassTag, T]
       (initialValue: R): Accumulable[R, T] = {
+    // TODO the context bound (<%) above should be replaced with simple type bound and implicit
+    // conversion but is a breaking change. This should be fixed in Spark 3.x.
```
Comment (cloud-fan) [inline core/src/main/scala/org/apache/spark/SparkContext.scala]: so context bound is not recommended in scala?

File: sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/ScalaReflection.scala (hunk 11 above)
Comment (cloud-fan) [inline sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/ScalaReflection.scala]: shall we do [this](https://github.com/apache/spark/pull/17473/files#diff-89643554d9757dd3e91abff1cc6096c7L310)?

File: sql/core/src/main/scala/org/apache/spark/sql/execution/python/ExtractPythonUDFs.scala [hunk 13]
```diff
@@ -133,7 +133,7 @@ object ExtractPythonUDFs extends Rule[SparkPlan] with PredicateHelper {
         val validUdfs = udfs.filter { udf =>
           // Check to make sure that the UDF can be evaluated with only the input of this child.
           udf.references.subsetOf(child.outputSet)
-        }.toArray  // Turn it into an array since iterators cannot be serialized in Scala 2.10
```
Comment (cloud-fan) [inline sql/core/src/main/scala/org/apache/spark/sql/execution/python/ExtractPythonUDFs.scala]: can we remove the `toArray`?

**Comment by cloud-fan** [comment]
LGTM, merging to master! we can address remaining comments in follow-up PR. Thanks for working on it!

**Comment by srowen** [comment]
OK, I think we could have just made the suggested changes here too, but I suspect we will find a thing or two we have to fix up along the way anyway.

File: core/src/main/scala/org/apache/spark/SparkContext.scala (hunk 12 above)
Comment (srowen) [inline core/src/main/scala/org/apache/spark/SparkContext.scala]: It generates a warning in scala 2.11, yeah

File: sql/core/src/main/scala/org/apache/spark/sql/execution/python/ExtractPythonUDFs.scala (hunk 13 above)
Comment (srowen) [inline sql/core/src/main/scala/org/apache/spark/sql/execution/python/ExtractPythonUDFs.scala]: Probably, but I stayed conservative here. At least the comment is obsolete

**Comment by cloud-fan** [comment]
BTW don't forget this comment: https://github.com/apache/spark/pull/17150#discussion_r127164260

I went ahead merging this because the scala 2.10 build is broken now :)

File: sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/ScalaReflection.scala (hunk 11 above)
Comment (srowen) [inline sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/ScalaReflection.scala]: @cloud-fan that's the code I'm replacing, because it generates deprecation warnings in 2.11

**Comment by srowen** [comment]
BTW @cloud-fan @JoshRosen can I delete the master 2.10 compile Jenkins jobs? they're going to fail from here on out. 

https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Compile/job/spark-master-compile-maven-scala-2.10/

(Not sure I have permissions to do it though.)

**Comment by JoshRosen** [comment]
@srowen, I'll disable those master branch 2.10 jobs and will update scripts to prevent them from being redeployed by accident.

**Comment by cloud-fan** [comment]
@srowen @JoshRosen After thinking more about it, will this PR make it harder to backport bug fixes PRs to the previous branch? I did a little search and seems we broke scala 2.10 a little frequent before: https://github.com/apache/spark/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed%202.10%20in%3Atitle

**Comment by srowen** [comment]
Do you mean, it'll be harder to know if a back-port broke the 2.10 build? yes. I don't think we have a choice though. We would detect the breakage eventually, and backports become rare over time.

**Comment by rxin** [comment]
Maybe do it a bit later, when the backport rate drops? E.g. it's unlikely we still do a lot of backports when 2.3 is cut.

**Comment by srowen** [comment]
Do what later? 
BTW there are still jobs that compile vs 2.10 for 2.2, 2.1, etc

**Comment by rxin** [comment]
Do the removal (i.e. this PR).

**Comment by srowen** [comment]
This is already merged though. This doesn't seem like a reason to revert -- there's not even an actual problem here. It's the same potential problem we've always had, that 2.10 breakage might only be caught by the Jenkins job. 2.10 breaks were not really common, all the less so for back-ports. I pledge to watch the compile jobs, if that helps. But we really need to get on to 2.12 support now.

**Comment by rxin** [comment]
Are you working on 2.12?

**Comment by srowen** [comment]
I do have a local branch with, I think, most of the key changes. I do want to unblock that work. But that's a little separate. Really I'm just narrowly arguing here that this change doesn't make it meaningfully harder to keep 2.10 working in older branches. It's no harder than it was previously, and I'm happy to keep an eye on it if anyone's concerned.

**Comment by HyukjinKwon** [comment]
Hi all, I did not open an JIRA because I am not very sure if it is an issue and it sounds maybe my environment problem.

However, I believe it is worth leaving a note. The build with Maven is fine (`./build/mvn clean -DskipTests package` as described in https://spark.apache.org/docs/latest/building-spark.html#buildmvn) but I am seeing the error with SBT after this commit. The build itself succeeds but it fails to run `./bin/spark-shell`. I tried the command lines as below (as described in http://spark.apache.org/developer-tools.html):

```bash
./build/sbt clean package
```

```bash
./bin/spark-shell
```

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
	at org.apache.hadoop.conf.Configuration.<clinit>(Configuration.java:173)
	at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:340)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:157)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:123)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more
```

I could reproduce this on ...

- CentOS Linux release 7.3.1611 (Core) / Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
- macOS 10.12.3 (16D32) / Java(TM) SE Runtime Environment (build 1.8.0_45-b14)


I could not reproduce this on ...

- Ubuntu 14.04 LTS / Java(TM) SE Runtime Environment (build 1.8.0_131-b11)


I checked the build with Maven is fine on ...

- CentOS Linux release 7.3.1611 (Core) / Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
- macOS 10.12.3 (16D32) / Java(TM) SE Runtime Environment (build 1.8.0_45-b14)


I checked the build before/after the commit on ...

- macOS 10.12.3 (16D32) / Java(TM) SE Runtime Environment (build 1.8.0_45-b14)

It looks this one is introduced here.

Could anyone double check this and see if I am mistaken? I just wonder if the same commands are consistently being failed on other environments (rather than the exact failure cause) ...

- CentOS Linux release 7.3.1611 (Core) / Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
- macOS 10.12.3 (16D32) / Java(TM) SE Runtime Environment (build 1.8.0_45-b14)

**Comment by srowen** [comment]
Yeah this change did change some dependencies, and it's possible something happened to have commons-logging included before and now it doesn't, and we need an explicit dependency somewhere. I'll look into it, as it ought to be pretty easy to patch if there's a gap here.

File: pom.xml [hunk 14]
```diff
@@ -498,7 +498,7 @@
         <groupId>org.slf4j</groupId>
         <artifactId>jcl-over-slf4j</artifactId>
         <version>${slf4j.version}</version>
-        <!-- <scope>runtime</scope> --> <!-- more correct, but scalac 2.10.3 doesn't like it -->
+        <scope>runtime</scope>
```
Comment (srowen) [inline pom.xml]: @HyukjinKwon it was this change. I think we need to retain it to keep commons-logging (well, the SLF4J shim for it) on the classpath. SBT isn't including it in the build somehow even though it's `runtime` scope, which is really correct. I think we've seen this with the Maven-SBT plugin before.
