### PR TITLE
[SQL][MINOR] Fix compiling for scala 2.12

### PR DESCRIPTION
**Pull request by da-liii**
## What changes were proposed in this pull request?
Introduced by #21320 and #11744

```
$ sbt
> ++2.12.6
> project sql
> compile
...
[error] [warn] spark/sql/core/src/main/scala/org/apache/spark/sql/execution/ProjectionOverSchema.scala:41: match may not be exhaustive.
[error] It would fail on the following inputs: (_, ArrayType(_, _)), (_, _)
[error] [warn]         getProjection(a.child).map(p => (p, p.dataType)).map {
[error] [warn]
[error] [warn] spark/sql/core/src/main/scala/org/apache/spark/sql/execution/ProjectionOverSchema.scala:52: match may not be exhaustive.
[error] It would fail on the following input: (_, _)
[error] [warn]         getProjection(child).map(p => (p, p.dataType)).map {
[error] [warn]
...
```

And

```
$ sbt
> ++2.12.6
> project hive
> testOnly *ParquetMetastoreSuite
...
[error] /Users/rendong/wdi/spark/sql/hive/src/test/scala/org/apache/spark/sql/hive/HiveSparkSubmitSuite.scala:22: object tools is not a member of package scala
[error] import scala.tools.nsc.Properties
[error]              ^
[error] /Users/rendong/wdi/spark/sql/hive/src/test/scala/org/apache/spark/sql/hive/HiveSparkSubmitSuite.scala:146: not found: value Properties
[error]     val version = Properties.versionNumberString match {
[error]                   ^
[error] two errors found
...
```

## How was this patch tested?
Existing tests.

### CODE REVIEW

File: sql/core/src/main/scala/org/apache/spark/sql/execution/ProjectionOverSchema.scala [hunk 1]
```diff
@@ -38,7 +38,7 @@ private[execution] case class ProjectionOverSchema(schema: StructType) {
       case GetArrayItem(child, arrayItemOrdinal) =>
         getProjection(child).map { projection => GetArrayItem(projection, arrayItemOrdinal) }
       case a: GetArrayStructFields =>
-        getProjection(a.child).map(p => (p, p.dataType)).map {
+        getProjection(a.child).map(p => (p, p.dataType)).collect {
```
Comment (maropu) [inline sql/core/src/main/scala/org/apache/spark/sql/execution/ProjectionOverSchema.scala]: How about this? IMO `.collect` can't catch illegal inputs?
```
        getProjection(a.child).map(p => (p, p.dataType)).map {
          case (projection, ArrayType(projSchema @ StructType(_), _)) =>
            GetArrayStructFields(projection,
              projSchema(a.field.name),
              projSchema.fieldIndex(a.field.name),
              projSchema.size,
              a.containsNull)
          case _ =>
            sys.error("....")
        }
```

**Comment by maropu** [comment]
Can you add `[SQL][MINOR]` in the title? Also, can you narrow down the tittle cuz it is a little obscure.

**Comment by HyukjinKwon** [comment]
ok to test

File: sql/core/src/main/scala/org/apache/spark/sql/execution/ProjectionOverSchema.scala (hunk 1 above)
Comment (sadhen) [reply sql/core/src/main/scala/org/apache/spark/sql/execution/ProjectionOverSchema.scala]: Well, there is a semantic change using `collect`. I will provide a unit test to verify the change or simply using `sys.error`

File: sql/hive/src/test/scala/org/apache/spark/sql/hive/HiveSparkSubmitSuite.scala [hunk 2]
```diff
@@ -19,7 +19,7 @@ package org.apache.spark.sql.hive
 
 import java.io.{BufferedWriter, File, FileWriter}
 
-import scala.tools.nsc.Properties
+import scala.util.Properties
```
Comment (srowen) [inline sql/hive/src/test/scala/org/apache/spark/sql/hive/HiveSparkSubmitSuite.scala]: This works in 2.11 and 2.12?

File: sql/core/src/main/scala/org/apache/spark/sql/execution/ProjectionOverSchema.scala (hunk 1 above)
Comment (srowen) [reply sql/core/src/main/scala/org/apache/spark/sql/execution/ProjectionOverSchema.scala]: Does this generate an error or just a warning in 2.12? It's an unmatched case error, right? 
We had 'fixed' this elsewhere with `case _ => throw new IllegalStateException(...)` or something. At runtime it would have caused a MatchError before, right? Because it didn't, I hope, or else tests would have failed, it matters a bit less what happens in this case. But it felt more conservative to preserve the error behavior; maybe I was wrong about that?

File: sql/hive/src/test/scala/org/apache/spark/sql/hive/HiveSparkSubmitSuite.scala (hunk 2 above)
Comment (sadhen) [reply sql/hive/src/test/scala/org/apache/spark/sql/hive/HiveSparkSubmitSuite.scala]: Yes. And

`scala.util.Properties` is better than `scala.tools.nsc.Properties` !

Comment (sadhen) [reply sql/hive/src/test/scala/org/apache/spark/sql/hive/HiveSparkSubmitSuite.scala]: `scala.tools` is part of scala-compiler

File: sql/core/src/main/scala/org/apache/spark/sql/execution/ProjectionOverSchema.scala (hunk 1 above)
Comment (sadhen) [reply sql/core/src/main/scala/org/apache/spark/sql/execution/ProjectionOverSchema.scala]: To use `collect`, one must dive into `SPARK-4502`.

This PR is intended for #22264 .

I will preserve the error behavior.

**Review by srowen — APPROVED** [review]

**Comment by maropu** [comment]
LGTM, too.

**Comment by HyukjinKwon** [comment]
Merged to master.
