### PR TITLE
[SPARK-30755][SQL] Update migration guide and add actionable exception for HIVE-15167

### PR DESCRIPTION
**Pull request by wangyum**
### What changes were proposed in this pull request?
[HIVE-15167](https://issues.apache.org/jira/browse/HIVE-15167) removed the `SerDe` interface. This may break custom `SerDe` builds for Hive 1.2. This PR update the migration guide for this change.

### Why are the changes needed?

Otherwise:
```
2020-01-27 05:11:20.446 - stderr> 20/01/27 05:11:20 INFO DAGScheduler: ResultStage 2 (main at NativeMethodAccessorImpl.java:0) failed in 1.000 s due to Job aborted due to stage failure: Task 0 in stage 2.0 failed 4 times, most recent failure: Lost task 0.3 in stage 2.0 (TID 13, 10.110.21.210, executor 1): java.lang.NoClassDefFoundError: org/apache/hadoop/hive/serde2/SerDe
  2020-01-27 05:11:20.446 - stderr>  at java.lang.ClassLoader.defineClass1(Native Method)
  2020-01-27 05:11:20.446 - stderr>  at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
  2020-01-27 05:11:20.446 - stderr>  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  2020-01-27 05:11:20.446 - stderr>  at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
  2020-01-27 05:11:20.446 - stderr>  at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
  2020-01-27 05:11:20.446 - stderr>  at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
  2020-01-27 05:11:20.446 - stderr>  at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
  2020-01-27 05:11:20.446 - stderr>  at java.security.AccessController.doPrivileged(Native Method)
  2020-01-27 05:11:20.446 - stderr>  at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
  2020-01-27 05:11:20.446 - stderr>  at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  2020-01-27 05:11:20.446 - stderr>  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
  2020-01-27 05:11:20.446 - stderr>  at java.lang.ClassLoader.loadClass(ClassLoader.java:405)
  2020-01-27 05:11:20.446 - stderr>  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  2020-01-27 05:11:20.446 - stderr>  at java.lang.Class.forName0(Native Method)
  2020-01-27 05:11:20.446 - stderr>  at java.lang.Class.forName(Class.java:348)
  2020-01-27 05:11:20.446 - stderr>  at org.apache.hadoop.hive.ql.plan.TableDesc.getDeserializerClass(TableDesc.java:76)
.....
```

### Does this PR introduce any user-facing change?
No.

### How was this patch tested?
Manual test

### CODE REVIEW

**Comment by gatorsmile** [comment]
cc @Ngone51 @cloud-fan

File: sql/hive/src/main/java/org/apache/hadoop/hive/serde2/SerDe.java [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+ *
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+
+package org.apache.hadoop.hive.serde2;
```
Comment (dongjoon-hyun) [inline sql/hive/src/main/java/org/apache/hadoop/hive/serde2/SerDe.java]: This may cause a conflict in Hive 1.2 profile. Shall we add this only for Hive 2.3 profile?

**Comment by dongjoon-hyun** [comment]
Please test with Hive 1.2, too.

File: sql/hive/src/main/java/org/apache/hadoop/hive/serde2/SerDe.java [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+ * If a developer wants his hive table to be read-only, then he just want to
+ * return
+ *
+ * both readable and writable, then
+ *
+ * All serdes should extend the abstract class AbstractSerDe, and eventually SerDe interface
+ * should be removed
+ */
+@Deprecated
+public interface SerDe extends Deserializer, Serializer {
```
Comment (gatorsmile) [inline sql/hive/src/main/java/org/apache/hadoop/hive/serde2/SerDe.java]: Could we add a customized HiveSerde JAR that directly uses this interface? Is it the only public APIs that are removed in Hive 2.3 from Hive 1.2.1?

**Comment by wangyum** [comment]
retest this please

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Hi, @wangyum .

Luckily the UT passed, but, as you know, we split this kind of source codes.
```
$ find . -name v2.3
./sql/core/v2.3
./sql/hive-thriftserver/v2.3
```

This seems to be a new case falling into `./sql/hive/v2.3`. Please move `sql/hive/src/main/java/org/apache/hadoop/hive/serde2` to `sql/hive/v2.3/src/main/java/org/apache/hadoop/hive/serde2` for consistency.

**Comment by gatorsmile** [comment]
The issue is a breaking change. I change the priority to Blocker

**Comment by dongjoon-hyun** [comment]
+1 for `Blocker`.

File: sql/hive/src/main/java/org/apache/hadoop/hive/serde2/SerDe.java (hunk 1 above)
Comment (yhuai) [reply sql/hive/src/main/java/org/apache/hadoop/hive/serde2/SerDe.java]: +1

**Comment by wangyum** [comment]
This method will have `NoSuchMethodError` exception:
```java
Error in query: java.lang.NoSuchMethodError: org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils.implicitConvertible(Lorg/apache/hadoop/hive/serde2/typeinfo/TypeInfo;Lorg/apache/hadoop/hive/serde2/typeinfo/TypeInfo;)Z;
```

**Comment by yhuai** [comment]
> ```java
> apache/hadoop/hive/serde2/typeinfo/
> ```

Seems implicitConvertible is still there (https://github.com/apache/hive/blob/rel/release-2.3.6/serde/src/java/org/apache/hadoop/hive/serde2/typeinfo/TypeInfoUtils.java#L928)? Or maybe I am missing something?

**Comment by yhuai** [comment]
Do we rely on hive to handle serde? If so, I am worried that simply adding back the interface will not work because hive does not understand how to handle it now.

**Comment by Ngone51** [comment]
Hi @wangyum , I got this error when I run `SPARK-30755: Support Hive 1.2.1's Serde after making built-in Hive to 2.3` in `HiveQuerySuite` locally using `./build/sbt -Phadoop-2.7 -Phive-2.3 -Phive-thriftserver -Phive`: 
```
[info] - SPARK-30755: Support Hive 1.2.1's Serde after making built-in Hive to 2.3 *** FAILED *** (5 seconds, 875 milliseconds)
[info]   org.apache.spark.sql.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.ClassCastException: class org.apache.spark.sql.hive.DummyHiveSerde;
[info]   at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:109)
[info]   at org.apache.spark.sql.hive.HiveExternalCatalog.createTable(HiveExternalCatalog.scala:242)
[info]   at org.apache.spark.sql.catalyst.catalog.ExternalCatalogWithListener.createTable(ExternalCatalogWithListener.scala:94)
[info]   at org.apache.spark.sql.catalyst.catalog.SessionCatalog.createTable(SessionCatalog.scala:325)
[info]   at org.apache.spark.sql.execution.command.CreateTableCommand.run(tables.scala:163)
[info]   at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
[info]   at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
[info]   at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:79)
[info]   at org.apache.spark.sql.Dataset.$anonfun$logicalPlan$1(Dataset.scala:226)
[info]   at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3497)
[info]   at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$4(SQLExecution.scala:102)
[info]   at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:162)
[info]   at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:89)
[info]   at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3495)
[info]   at org.apache.spark.sql.Dataset.<init>(Dataset.scala:226)
[info]   at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:88)
[info]   at org.apache.spark.sql.hive.test.TestHiveSparkSession.sql(TestHive.scala:238)
[info]   at org.apache.spark.sql.hive.execution.HiveQuerySuite.$anonfun$new$114(HiveQuerySuite.scala:1231)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info]   at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
[info]   at org.apache.spark.sql.test.SQLTestUtilsBase.withTable(SQLTestUtils.scala:290)
[info]   at org.apache.spark.sql.test.SQLTestUtilsBase.withTable$(SQLTestUtils.scala:288)
[info]   at org.apache.spark.sql.hive.execution.HiveQuerySuite.withTable(HiveQuerySuite.scala:49)
[info]   at org.apache.spark.sql.hive.execution.HiveQuerySuite.$anonfun$new$113(HiveQuerySuite.scala:1229)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
[info]   at org.apache.spark.SparkFunSuite.withFixture(SparkFunSuite.scala:151)
[info]   at org.scalatest.FunSuiteLike.invokeWithFixture$1(FunSuiteLike.scala:184)
[info]   at org.scalatest.FunSuiteLike.$anonfun$runTest$1(FunSuiteLike.scala:196)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
[info]   at org.scalatest.FunSuiteLike.runTest(FunSuiteLike.scala:196)
[info]   at org.scalatest.FunSuiteLike.runTest$(FunSuiteLike.scala:178)
[info]   at org.apache.spark.SparkFunSuite.org$scalatest$BeforeAndAfterEach$$super$runTest(SparkFunSuite.scala:58)
[info]   at org.scalatest.BeforeAndAfterEach.runTest(BeforeAndAfterEach.scala:221)
[info]   at org.scalatest.BeforeAndAfterEach.runTest$(BeforeAndAfterEach.scala:214)
[info]   at org.apache.spark.sql.hive.execution.HiveQuerySuite.org$scalatest$BeforeAndAfter$$super$runTest(HiveQuerySuite.scala:49)
[info]   at org.scalatest.BeforeAndAfter.runTest(BeforeAndAfter.scala:203)
[info]   at org.scalatest.BeforeAndAfter.runTest$(BeforeAndAfter.scala:192)
[info]   at org.apache.spark.sql.hive.execution.HiveQuerySuite.runTest(HiveQuerySuite.scala:49)
[info]   at org.scalatest.FunSuiteLike.$anonfun$runTests$1(FunSuiteLike.scala:229)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:393)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:376)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
[info]   at org.scalatest.FunSuiteLike.runTests(FunSuiteLike.scala:229)
[info]   at org.scalatest.FunSuiteLike.runTests$(FunSuiteLike.scala:228)
[info]   at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
[info]   at org.scalatest.Suite.run(Suite.scala:1124)
[info]   at org.scalatest.Suite.run$(Suite.scala:1106)
[info]   at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
[info]   at org.scalatest.FunSuiteLike.$anonfun$run$1(FunSuiteLike.scala:233)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:518)
[info]   at org.scalatest.FunSuiteLike.run(FunSuiteLike.scala:233)
[info]   at org.scalatest.FunSuiteLike.run$(FunSuiteLike.scala:232)
[info]   at org.apache.spark.SparkFunSuite.org$scalatest$BeforeAndAfterAll$$super$run(SparkFunSuite.scala:58)
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   at org.apache.spark.sql.hive.execution.HiveQuerySuite.org$scalatest$BeforeAndAfter$$super$run(HiveQuerySuite.scala:49)
[info]   at org.scalatest.BeforeAndAfter.run(BeforeAndAfter.scala:258)
[info]   at org.scalatest.BeforeAndAfter.run$(BeforeAndAfter.scala:256)
[info]   at org.apache.spark.sql.hive.execution.HiveQuerySuite.run(HiveQuerySuite.scala:49)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:510)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:296)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:286)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
...
```

**Comment by yhuai** [comment]
Also, how did https://github.com/apache/spark/blob/a6b91d2bf727e175d0e175295001db85647539b1/sql/hive/src/test/scala/org/apache/spark/sql/hive/HiveSparkSubmitSuite.scala#L111 pass? Is it because we are pulling in a new jar that works with 2.3.6?

**Comment by wangyum** [comment]
@Ngone51 Yes. `SPARK-30755: Support Hive 1.2.1's Serde after making built-in Hive to 2.3` can not pass. You can build this class into a new jar and add it to the classpath for testing. But it will throw `Error in query: java.lang.NoSuchMethodError: org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils.implicitConvertible(Lorg/apache/hadoop/hive/serde2/typeinfo/TypeInfo;Lorg/apache/hadoop/hive/serde2/typeinfo/TypeInfo;)Z;` error. That is to say, this is not a right way to fix this issue.

**Comment by wangyum** [comment]
@yhuai It is because we use `hive-contrib-2.3.6.jar` and `hive-hcatalog-core-2.3.6.jar`:
https://github.com/apache/spark/blob/2ceed6f32c51a0c5e535fcff37336e7d8cd87537/sql/hive/src/test/scala/org/apache/spark/sql/hive/HiveSparkSubmitSuite.scala#L115-L116

**Comment by cloud-fan** [comment]
Do we have a way to fix it?

**Comment by wangyum** [comment]
I don't have a perfect solution. Add [Hive 1.2.1's SerDe](https://github.com/apache/hive/blob/release-1.2.1/serde/src/java/org/apache/hadoop/hive/serde2/SerDe.java) to source code can fix [some custom serde](https://github.com/apache/spark/pull/27492/files#diff-e650275112313e07848c1c1013d9179aR130-R147). But can't fix [all custom serde](https://github.com/apache/spark/pull/27492/files#diff-716b853fcfc18ac51ef0ed04dd0fd4deR23-R153) .

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/client/HiveClientImpl.scala [hunk 3]
```diff
@@ -318,7 +318,14 @@ private[hive] class HiveClientImpl(
     // with the HiveConf in `state` to override the context class loader of the current
     // thread.
     shim.setCurrentSessionState(state)
-    val ret = try f finally {
```
Comment (cloud-fan) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/client/HiveClientImpl.scala]: does it cover all the cases? e.g. table insertion? This seems only cover the DDL cases.

Comment (wangyum) [reply sql/hive/src/main/scala/org/apache/spark/sql/hive/client/HiveClientImpl.scala]: Yes. It cover all the cases:
```java
20/02/17 02:55:59 ERROR SparkSQLDriver: Failed in [insert into t2 values('1', '2')]
java.lang.ClassNotFoundException: The SerDe interface removed since Hive 2.3(HIVE-15167). Please migrate your custom SerDes to Hive 2.3 or build your own Spark with hive-1.2 profile. See HIVE-15167 for more details.
	at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$withHiveState$1(HiveClientImpl.scala:328)
	at org.apache.spark.sql.hive.client.HiveClientImpl.liftedTree1$1(HiveClientImpl.scala:255)
	at org.apache.spark.sql.hive.client.HiveClientImpl.retryLocked(HiveClientImpl.scala:254)
	at org.apache.spark.sql.hive.client.HiveClientImpl.withHiveState(HiveClientImpl.scala:304)
	at org.apache.spark.sql.hive.client.HiveClientImpl.getTableOption(HiveClientImpl.scala:450)
	at org.apache.spark.sql.hive.client.HiveClient.getTable(HiveClient.scala:81)
```

```java
20/02/17 02:56:45 ERROR SparkSQLDriver: Failed in [select * from t2]
java.lang.ClassNotFoundException: The SerDe interface removed since Hive 2.3(HIVE-15167). Please migrate your custom SerDes to Hive 2.3 or build your own Spark with hive-1.2 profile. See HIVE-15167 for more details.
	at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$withHiveState$1(HiveClientImpl.scala:328)
	at org.apache.spark.sql.hive.client.HiveClientImpl.liftedTree1$1(HiveClientImpl.scala:255)
	at org.apache.spark.sql.hive.client.HiveClientImpl.retryLocked(HiveClientImpl.scala:254)
	at org.apache.spark.sql.hive.client.HiveClientImpl.withHiveState(HiveClientImpl.scala:304)
	at org.apache.spark.sql.hive.client.HiveClientImpl.getTableOption(HiveClientImpl.scala:450)
	at org.apache.spark.sql.hive.client.HiveClient.getTable(HiveClient.scala:81)
	at org.apache.spark.sql.hive.client.HiveClient.getTable$(HiveClient.scala:80)
	at org.apache.spark.sql.hive.client.HiveClientImpl.getTable(HiveClientImpl.scala:91)
	at org.apache.spark.sql.hive.HiveExternalCatalog.getRawTable(HiveExternalCatalog.scala:120)
	at org.apache.spark.sql.hive.HiveExternalCatalog.$anonfun$getTable$1(HiveExternalCatalog.scala:711)
	at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:99)
	at org.apache.spark.sql.hive.HiveExternalCatalog.getTable(HiveExternalCatalog.scala:711)
	at org.apache.spark.sql.catalyst.catalog.ExternalCatalogWithListener.getTable(ExternalCatalogWithListener.scala:138)
	at org.apache.spark.sql.catalyst.catalog.SessionCatalog.getTableMetadata(SessionCatalog.scala:445)
	at org.apache.spark.sql.execution.datasources.v2.V2SessionCatalog.loadTable(V2SessionCatalog.scala:66)
	at org.apache.spark.sql.connector.catalog.CatalogV2Util$.loadTable(CatalogV2Util.scala:281)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.loaded$1(Analyzer.scala:923)
```

```java
spark-sql> truncate table  t2;
20/02/17 02:59:19 INFO HiveMetaStore: 0: get_database: default
20/02/17 02:59:19 INFO audit: ugi=root	ip=unknown-ip-addr	cmd=get_database: default
20/02/17 02:59:19 INFO HiveMetaStore: 0: get_table : db=default tbl=t2
20/02/17 02:59:19 INFO audit: ugi=root	ip=unknown-ip-addr	cmd=get_table : db=default tbl=t2
20/02/17 02:59:19 INFO HiveMetaStore: 0: get_table : db=default tbl=t2
20/02/17 02:59:19 INFO audit: ugi=root	ip=unknown-ip-addr	cmd=get_table : db=default tbl=t2
20/02/17 02:59:19 ERROR SparkSQLDriver: Failed in [truncate table  t2]
java.lang.ClassNotFoundException: The SerDe interface removed since Hive 2.3(HIVE-15167). Please migrate your custom SerDes to Hive 2.3 or build your own Spark with hive-1.2 profile. See HIVE-15167 for more details.
	at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$withHiveState$1(HiveClientImpl.scala:328)
	at org.apache.spark.sql.hive.client.HiveClientImpl.liftedTree1$1(HiveClientImpl.scala:255)
	at org.apache.spark.sql.hive.client.HiveClientImpl.retryLocked(HiveClientImpl.scala:254)
	at org.apache.spark.sql.hive.client.HiveClientImpl.withHiveState(HiveClientImpl.scala:304)
	at org.apache.spark.sql.hive.client.HiveClientImpl.getTableOption(HiveClientImpl.scala:450)
	at org.apache.spark.sql.hive.client.HiveClient.getTable(HiveClient.scala:81)
	at org.apache.spark.sql.hive.client.HiveClient.getTable$(HiveClient.scala:80)
	at org.apache.spark.sql.hive.client.HiveClientImpl.getTable(HiveClientImpl.scala:91)
```

**Review by cloud-fan — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @wangyum , @cloud-fan , @yhuai and @gatorsmile .
Merged to master/3.0.
