### PR TITLE
[SPARK-20202][BUILD][SQL] Remove references to org.spark-project.hive (Hive 1.2.1)

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

As of today,
- SPARK-30034 Apache Spark 3.0.0 switched its default Hive execution engine from Hive 1.2 to Hive 2.3. This removes the direct dependency to the forked Hive 1.2.1 in maven repository.
- SPARK-32981 Apache Spark 3.1.0(`master` branch) removed Hive 1.2 related artifacts from Apache Spark binary distributions.

This PR(SPARK-20202) aims to remove the following usage of unofficial Apache Hive fork completely from Apache Spark master for Apache Spark 3.1.0.
```
<hive.group>org.spark-project.hive</hive.group>
<hive.version>1.2.1.spark2</hive.version>
```

For the forked Hive 1.2.1.spark2 users, Apache Spark 2.4(LTS) and 3.0 (~ 2021.12) will provide it.

### Why are the changes needed?

- First, Apache Spark community should not use the unofficial forked release of another Apache project.
- Second, Apache Hive 1.2.1 was released at 2015-06-26 and the forked Hive `1.2.1.spark2` exposed many unfixable bugs in Apache because the forked `1.2.1.spark2` is not maintained at all. Apache Hive 2.3.0 was released at 2017-07-19 and it has been used with less number of bugs compared with `1.2.1.spark2`. Many bugs still exist in `hive-1.2` profile and new Apache Spark unit tests are added with `HiveUtils.isHive23` condition so far.

### Does this PR introduce _any_ user-facing change?

No. This is a dev-only change. PRBuilder will not accept `[test-hive1.2]` on master and `branch-3.1`.

### How was this patch tested?

1. SBT/Hadoop 3.2/Hive 2.3 (https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/129366)
2. SBT/Hadoop 2.7/Hive 2.3 (https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/129382)
3. SBT/Hadoop 3.2/Hive 1.2 (This has not been supported already due to Hive 1.2 doesn't work with Hadoop 3.2.)
4. SBT/Hadoop 2.7/Hive 1.2 (https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/129383, This is rejected)

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Review by srowen — COMMENTED** [review]
I'm OK with it if Hive 1.2 is gone.

**Comment by dongjoon-hyun** [comment]
Thank you, @srowen .

**Comment by HyukjinKwon** [comment]
@wangyum can you review this? I think it's important to get your review here.

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/client/HiveClientImpl.scala [hunk 1]
```diff
@@ -296,8 +296,7 @@ private[hive] class HiveClientImpl(
       case e: NoClassDefFoundError
         if HiveUtils.isHive23 && e.getMessage.contains("org/apache/hadoop/hive/serde2/SerDe") =>
```
Comment (HyukjinKwon) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/client/HiveClientImpl.scala:297]: @dongjoon-hyun should we remove `HiveUtils.isHive23` and related changes? I see it was added when we add Hive 2.3 support at https://github.com/apache/spark/commit/33f3c48cac087e079b9c7e342c2e58b16eaaa681#diff-842e3447fc453de26c706db1cac8f2c4R59. cc @wangyum FYI

Comment (HyukjinKwon) [reply sql/hive/src/main/scala/org/apache/spark/sql/hive/client/HiveClientImpl.scala:297]: @AngersZhuuuu should we remove https://github.com/apache/spark/blob/55ce49ed28a58e0047a9680fa63f4dff54c11be4/sql/hive/src/test/scala/org/apache/spark/sql/hive/execution/HiveScriptTransformationSuite.scala#L41 too?

File: sql/hive/src/test/scala/org/apache/spark/sql/execution/benchmark/InsertIntoHiveTableBenchmark.scala [hunk 2]
```diff
@@ -28,14 +28,11 @@ import org.apache.spark.sql.hive.test.TestHive
  * {{{
```
Comment (HyukjinKwon) [inline sql/hive/src/test/scala/org/apache/spark/sql/execution/benchmark/InsertIntoHiveTableBenchmark.scala:28]: I think we can now remove this comment https://github.com/apache/spark/commit/d7755cfd07554c132b7271730102b8b68eb56b28#diff-10e604a9a9d9c4bcc9cdc01049851095R170

and enable this test https://github.com/apache/spark/commit/d7755cfd07554c132b7271730102b8b68eb56b28#diff-10e604a9a9d9c4bcc9cdc01049851095R201. Feel free to ignore back if it fails for whatever reason.

Comment (HyukjinKwon) [reply sql/hive/src/test/scala/org/apache/spark/sql/execution/benchmark/InsertIntoHiveTableBenchmark.scala:28]: Looks we can just remove this comment too:

https://github.com/apache/spark/blob/6be8b935a4f7ce0dea2d7aaaf747c2e8e1a9f47a/sql/hive/src/test/scala/org/apache/spark/sql/hive/orc/HiveOrcQuerySuite.scala#L171-L173

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/client/HiveClientImpl.scala (hunk 1 above)
Comment (wangyum) [reply sql/hive/src/main/scala/org/apache/spark/sql/hive/client/HiveClientImpl.scala:297]: +1, we can remove `HiveUtils.isHive23` and related changes.

**Comment by dongjoon-hyun** [comment]
Thank you so much for review, @HyukjinKwon and @wangyum . It's difficult to remove all conditional logics in this PR. We have more instances in the test cases, too. I want to clean up them in another PR or a follow-up carefully. Is it okay for you guys?

**Comment by dongjoon-hyun** [comment]
cc @dbtsai , @holdenk , @viirya , @sunchao

**Review by dbtsai — APPROVED** [review]
LGTM. +1 on cleaning up the rest of Hive1.2 code in followup PR as it's everywhere, and takes time to carefully remove them.

File: pom.xml [hunk 3]
```diff
@@ -3150,23 +3146,7 @@
...
-        <hive.storage.version>2.6.0</hive.storage.version>
-        <hive.storage.scope>provided</hive.storage.scope>
-        <hive.common.scope>provided</hive.common.scope>
-        <hive.llap.scope>provided</hive.llap.scope>
-        <hive.serde.scope>provided</hive.serde.scope>
-        <hive.shims.scope>provided</hive.shims.scope>
-        <orc.classifier>nohive</orc.classifier>
-        <datanucleus-core.version>3.2.10</datanucleus-core.version>
-      </properties>
+      <!-- Exists only for backward compatibility. No-op. -->
```
Comment (viirya) [inline pom.xml:3149]: So this profile is still useful?

**Comment by viirya** [comment]
Looks OK and the tests/Github Actions were passed. It is okay to clean up other Hive 1.2 related code in next PRs.

File: pom.xml (hunk 3 above)
Comment (srowen) [reply pom.xml:3149]: No, it's just that you get an error if you specify `-Phive-1.2` if it's removed entirely. Now, maybe that's a good thing? previously for Scala profiles I had left them in because, for example `-Pscala-2.12` was not the default before. When it became the default, that would have caused an error even though it was already set up for 2.12. But this case is probably different: someone selecting Hive 1.x support should see an error, probably? in which case this should be removed.

Comment (viirya) [reply pom.xml:3149]: Yeah, this sounds more correct.

Comment (dongjoon-hyun) [reply pom.xml:3149]: Got it. I'll remove this and raise error explicitly, @viirya and @srowen . :)

**Comment by dongjoon-hyun** [comment]
Thank you all. Merged to master for Apache Spark 3.1.0.

**Comment by HyukjinKwon** [comment]
Yeah, followup is fine. LGTM.
