### PR TITLE
[SPARK-29073][INFRA][2.4] Add GitHub Action to branch-2.4 for `Scala-2.11/2.12` build

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

Apache Spark community is using GitHub action to monitor `JDK8/JDK11` build on `master` branch. It's very helpful. This PR aims to monitor both `Scala-2.11/2.12` build on `branch-2.4` by using GitHub Action.

### Why are the changes needed?

Currently, Apache Spark Jenkins servers only test `Scala-2.11` on `branch-2.4`.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Manual. (This can be tested in the repositories which received GitHub Action invitation)

- https://github.com/dongjoon-hyun/action/commit/61a77a04854987dde3d5eff873edbf2625907f83/checks

### CODE REVIEW

**Comment by srowen** [comment]
Does this type of build work on master? I seem to get a failure every time I commit something. But sure it's OK to add them in general. Are these meant to try to replace Jenkins?

**Review by HyukjinKwon — APPROVED** [review]
Looks worth trying.

**Comment by dongjoon-hyun** [comment]
Thank you, @srowen and @HyukjinKwon .

For the questions,
1. Yes. This works in `master` as you see here. I detected JDK11 compilation error and fixed it by monitoring the following.
- https://github.com/apache/spark/actions
2. No. This will not replace Jenkins. This PR aims to cover the missing part from Jenkins.

BTW, where do you mean? The above link is Apache Spark master and is working now.
> I seem to get a failure every time I commit something.

**Comment by dongjoon-hyun** [comment]
Merged to branch-2.4.

**Comment by dongjoon-hyun** [comment]
For a record, it works correctly. :)
- https://github.com/apache/spark/commits/branch-2.4
