### PR TITLE
[SPARK-32916][SHUFFLE][test-maven][test-hadoop2.7] Remove the newly added YarnShuffleServiceSuite.java

### PR DESCRIPTION
**Pull request by otterc**
### What changes were proposed in this pull request?
This is a follow-up fix for the failing tests in `YarnShuffleServiceSuite.java`. This java class was introduced in https://github.com/apache/spark/pull/30062. The tests in the class fail when run with hadoop-2.7 profile:
```
[ERROR] testCreateDefaultMergedShuffleFileManagerInstance(org.apache.spark.network.yarn.YarnShuffleServiceSuite)  Time elapsed: 0.627 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
	at org.apache.spark.network.yarn.YarnShuffleServiceSuite.testCreateDefaultMergedShuffleFileManagerInstance(YarnShuffleServiceSuite.java:37)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
	at org.apache.spark.network.yarn.YarnShuffleServiceSuite.testCreateDefaultMergedShuffleFileManagerInstance(YarnShuffleServiceSuite.java:37)

[ERROR] testCreateRemoteBlockPushResolverInstance(org.apache.spark.network.yarn.YarnShuffleServiceSuite)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.network.yarn.YarnShuffleService
	at org.apache.spark.network.yarn.YarnShuffleServiceSuite.testCreateRemoteBlockPushResolverInstance(YarnShuffleServiceSuite.java:47)

[ERROR] testInvalidClassNameOfMergeManagerWillUseNoOpInstance(org.apache.spark.network.yarn.YarnShuffleServiceSuite)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.network.yarn.YarnShuffleService
	at org.apache.spark.network.yarn.YarnShuffleServiceSuite.testInvalidClassNameOfMergeManagerWillUseNoOpInstance(YarnShuffleServiceSuite.java:57)
```
A test suit for `YarnShuffleService` did exist here:
`resource-managers/yarn/src/test/scala/org/apache/spark/network/yarn/YarnShuffleServiceSuite.scala`
I missed this when I created `common/network-yarn/src/test/java/org/apache/spark/network/yarn/YarnShuffleServiceSuite.java`. Moving all the new tests to the earlier test suite fixes the failures with hadoop-2.7 even though why this happened is not clear.

### Why are the changes needed?
The newly added tests are failing when run with hadoop profile 2.7

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Ran the unit tests with the default profile as well as hadoop 2.7 profile.
`build/mvn test -Dtest=none -DwildcardSuites=org.apache.spark.network.yarn.YarnShuffleServiceSuite -Phadoop-2.7 -Pyarn`
```
Run starting. Expected test count is: 11
YarnShuffleServiceSuite:
- executor state kept across NM restart
- removed applications should not be in registered executor file
- shuffle service should be robust to corrupt registered executor file
- get correct recovery path
- moving recovery file from NM local dir to recovery path
- service throws error if cannot start
- recovery db should not be created if NM recovery is not enabled
- SPARK-31646: metrics should be registered into Node Manager's metrics system
- create default merged shuffle file manager instance
- create remote block push resolver instance
- invalid class name of merge manager will use noop instance
Run completed in 2 seconds, 572 milliseconds.
Total number of tests run: 11
Suites: completed 2, aborted 0
Tests: succeeded 11, failed 0, canceled 0, ignored 0, pending 0
All tests passed.
```

### CODE REVIEW

**Comment by otterc** [comment]
@mridulm Please take a look

**Comment by mridulm** [comment]
ok to test

**Comment by tgravescs** [comment]
it would be nice to add description as to why they need to be moved. or why moving them fixes whatever the failure is.

**Comment by HyukjinKwon** [comment]
Big +1 for @tgravescs advice.

**Comment by otterc** [comment]
@tgravescs @HyukjinKwon I am not entirely sure why these tests would fail with the errors below only for hadoop-2.7 profile. 
I see that the `network-yarn` module is build differently. The target jar of this module is a `spark-{version}-yarn-shuffle.jar`. However, that doesn't explain why this will fail only with hadoop-2.7 profile and not for hadoop 3.2. It could also be what @mridulm pointed out that some jar is missing from hadoop-2.7 profile. However, I didn't add any additional dependencies. I didn't create a new `logger` instance. Just using the existing `logger` instance in `YarnShuffleService`.

The reason I am deleting this `common/network-yarn/src/test/java/org/apache/spark/network/yarn/YarnShuffleServiceSuite.java` was that I added this with https://github.com/apache/spark/pull/30062 because I missed that  ` resource-managers/yarn/src/test/scala/org/apache/spark/network/yarn/YarnShuffleServiceSuite.scala` existed. I reckon there is no need to have 2 test classes for same class. However, it would have been better to have the test class in the same module.

I can dig deeper into why this happened but that would require more time. In the meantime just wanted to fix the failures with hadoop-2.7 build.

```
[ERROR] testCreateDefaultMergedShuffleFileManagerInstance(org.apache.spark.network.yarn.YarnShuffleServiceSuite)  Time elapsed: 0.421 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
	at org.apache.spark.network.yarn.YarnShuffleServiceSuite.testCreateDefaultMergedShuffleFileManagerInstance(YarnShuffleServiceSuite.java:37)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
	at org.apache.spark.network.yarn.YarnShuffleServiceSuite.testCreateDefaultMergedShuffleFileManagerInstance(YarnShuffleServiceSuite.java:37)

[ERROR] testCreateRemoteBlockPushResolverInstance(org.apache.spark.network.yarn.YarnShuffleServiceSuite)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.network.yarn.YarnShuffleService
	at org.apache.spark.network.yarn.YarnShuffleServiceSuite.testCreateRemoteBlockPushResolverInstance(YarnShuffleServiceSuite.java:47)

[ERROR] testInvalidClassNameOfMergeManagerWillUseNoOpInstance(org.apache.spark.network.yarn.YarnShuffleServiceSuite)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.network.yarn.YarnShuffleService
	at org.apache.spark.network.yarn.YarnShuffleServiceSuite.testInvalidClassNameOfMergeManagerWillUseNoOpInstance(YarnShuffleServiceSuite.java:57)
```

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by dongjoon-hyun** [comment]
Let see if this recovers `Hadoop 2.7` on Maven build.

**Comment by dongjoon-hyun** [comment]
Hi, @otterc , @mridulm , @tgravescs , @HyukjinKwon .
Thank you for making an effort to recover `master` branch quickly.
I'll leave this PR to you guys and hope the recovery occurs soon.

**Comment by tgravescs** [comment]
I'm fine to get something checked in quickly to fix the build but would like to understand it as well.  I kicked the build again as failure didn't look related.

**Comment by tgravescs** [comment]
yeah I didn't realize that Suite was in different module, it makes sense it put it all in one place.
it looks like ./common/network-yarn doesn't have dependencies for yarn (only Hadoop client) whereas ./resource-managers/yarn does. the tests aren't doing much with yarn it just calling your static function for newMergedShuffleFileManagerInstance and it builds with just the client so it seems like that should be enough.  If tests pass I think its fine to merge as it makes sense just to combine into single file.

**Comment by tgravescs** [comment]
test this please

**Comment by tgravescs** [comment]
failures look unrelated, I'm honestly not sure what they are:
2020-11-13T15:55:21.9268572Z [error] running /home/runner/work/spark/spark/build/sbt -Phadoop-3.2 -Phive-2.3 -Dtest.include.tags=org.apache.spark.tags.ExtendedSQLTest sql/test ; received return code 1
2020-11-13T15:55:21.9487619Z ##[error]Process completed with exit code 18.
2020-11-13T15:55:22.0775315Z ##[group]Run actions/upload-artifact@v2

@dongjoon-hyun  have you been this before? Maybe I'm missing something in the logs

**Review by tgravescs — APPROVED** [review]

**Comment by tgravescs** [comment]
I'm not sure what is going on with GitHub Action tests, but based on the Jenkins ones passing, I'm going to merge this. If we find it makes things worse we can revert it.

**Comment by tgravescs** [comment]
merged to master

**Comment by dongjoon-hyun** [comment]
Thank you, @tgravescs and all!

**Comment by mridulm** [comment]
Thanks for merging it @tgravescs.
Thanks for fixing this @otterc, and thanks for reporting it @dongjoon-hyun !
