### PR TITLE
[HOTFIX] [SQL] Fixes compilation error introduced by PR #7506

### PR DESCRIPTION
**Pull request by liancheng**
PR #7506 breaks master build because of compilation error. Note that #7506 itself looks good, but it seems that `git merge` did something stupid.

### CODE REVIEW

**Comment by liancheng** [comment]
Merging to master.
