### PR TITLE
[SPARK-5682] Reuse hadoop encrypted shuffle algorithm to enable spark en...

### PR DESCRIPTION
**Pull request by kellyzly**

### CODE REVIEW

File: pom.xml [hunk 1]
```diff
@@ -1581,9 +1581,9 @@
     </profile>
 
     <profile>
-      <id>hadoop-2.4</id>
```
Comment (JoshRosen) [inline pom.xml]: Does this imply that we'd be dropping support for Hadoop 2.4?  I don't think we can do that.

File: yarn/src/main/scala/org/apache/spark/deploy/yarn/ApplicationMaster.scala [hunk 2]
```diff
@@ -39,6 +39,14 @@ import org.apache.spark.deploy.history.HistoryServer
...
 import org.apache.spark.scheduler.cluster.CoarseGrainedClusterMessages._
 import org.apache.spark.util.{AkkaUtils, SignalLogger, Utils}
+import org.apache.hadoop.mapreduce.security.TokenCache
+import org.apache.hadoop.io.Text
+import org.apache.hadoop.security.UserGroupInformation
+import javax.crypto.{SecretKey, KeyGenerator}
+import org.apache.hadoop.mapreduce.CryptoUtils
+import org.apache.hadoop.conf.Configuration
+import org.apache.hadoop.mapreduce.MRJobConfig
+import java.security.NoSuchAlgorithmException
```
Comment (JoshRosen) [inline yarn/src/main/scala/org/apache/spark/deploy/yarn/ApplicationMaster.scala]: These imports need to be re-ordered according to Spark's code style guide: https://cwiki.apache.org/confluence/display/SPARK/Spark+Code+Style+Guide

**Comment by kellyzly** [comment]
@JoshRosen:  I have updated the patch, added the profile of hadoop 2.4 I deleted before and add a profile of hadoop2.6.

File: pom.xml [hunk 3]
```diff
@@ -1600,6 +1600,19 @@
     </profile>
 
     <profile>
+      <id>hadoop-2.6</id>
+      <properties>
+        <hadoop.version>2.6.0</hadoop.version>
+        <protobuf.version>2.5.0</protobuf.version>
+        <jets3t.version>0.9.2</jets3t.version>
```
Comment (tgravescs) [inline pom.xml]: any reason this isn't 0.9.3 like hadoop 2.4 and others?

File: pom.xml [hunk 4]
```diff
@@ -1600,6 +1600,19 @@
     </profile>
 
     <profile>
+      <id>hadoop-2.6</id>
+      <properties>
+        <hadoop.version>2.6.0</hadoop.version>
```
Comment (tgravescs) [inline pom.xml]: is something specific from hadoop 2.6 needed for this patch? ie encryption will only work when built against hadoop 2.6?

File: core/src/main/scala/org/apache/spark/storage/ShuffleBlockFetcherIterator.scala [hunk 5]
```diff
@@ -18,12 +18,22 @@
...
+import java.nio.ByteBuffer
 import java.util.concurrent.LinkedBlockingQueue
 
 import scala.collection.mutable.{ArrayBuffer, HashSet, Queue}
 import scala.util.{Failure, Success, Try}
 
+import org.apache.hadoop.conf.Configuration
+import org.apache.hadoop.crypto.CryptoCodec
+import org.apache.hadoop.crypto.CryptoInputStream
+import org.apache.hadoop.mapreduce.CryptoUtils
```
Comment (tgravescs) [inline core/src/main/scala/org/apache/spark/storage/ShuffleBlockFetcherIterator.scala]: These things are private and unstable.  We shouldn't be using private things from mapreduce/hadoop in spark.  It leads to issues when they change the api it breaks Spark.

File: pom.xml (hunk 4 above)
Comment (srowen) [inline pom.xml]: Yes, I don't see why this profile is needed. It's redundant AFAICT

File: pom.xml [hunk 6]
```diff
@@ -1600,6 +1600,19 @@
     </profile>
 
     <profile>
+      <id>hadoop-2.6</id>
```
Comment (tgravescs) [inline pom.xml]: we would want to document this in the building spark doc.

**Comment by tgravescs** [comment]
The main issue I see here is we are using private things from hadoop and mapreduce.   We've run into issues with this in the past so I think we should stay away from that.  Either that or we have to get the interfaces made public.    Many of the MapReduce references really aren't needed, just make spark configs to do the same things for configuration or for the secret key, etc.

I haven't looked at the hadoop encryption stuff in detail so would need to review that further to give more feedback.  Perhaps @sryza has looked at it.  I'm not sure if it would make sense to just copy the code or if its using a bunch of other private routines.  

We will definitely need to update some more documentation if this goes in - configuration and security docs.

What testing has been performed on this?  It affects more then just running on YARN. Did you test it with the YARN external shuffle service?

**Comment by vanzin** [comment]
I agree with @tgravescs that we should avoid using private APIs where possible. On top of that, this patch would break the build for anything < hadoop-2.6. If using these APIs, you'd have to use reflection to load them (or use shims like sql/hive does).

When I thought about this problem, the biggest issue was to distribute the encryption key securely. If we can do that using the `UserGroupInformation` and `Token` classes, adding the actual encryption to the block manager shouldn't be hard.

File: pom.xml (hunk 4 above)
Comment (kellyzly) [inline pom.xml]: @tgravescs @srowen:
org.apache.hadoop.crypto.CryptoInputStream#CryptoInputStream, org.apache.hadoop.crypto.CryptoOutputStream are two classes for encrypted shuffle which are imported since hadoop2.6.  

I used CryptoInputStream in org.apache.spark.storage.ShuffleBlockFetcherIterator and CryptoOutputStream in org.apache.spark.storage.DiskBlockObjectWriter.

Comment (srowen) [inline pom.xml]: Hm, but why does that mean a separate Hadoop profile is needed? it sounds like you're saying this change depends on Hadoop 2.6? Let's ask Jenkins to find out.

**Comment by srowen** [comment]
ok to test

**Comment by kellyzly** [comment]
@tgravescs @vanzin @srowen @JoshRosen 
I was glad to receive all the suggestions from you.
I summarized all of your suggestions:
* CryptoInputStream and CryptoOutputStream are two classes related with encrypted shuffle  and are marked as "private" in hadoop2.6. 
   We can not import classes which are marked "private". I think we can solve this problem by following way:
     Add two classes like CryptoInputStream and CryptoOutputStream in spark, the code maybe similar as what in hadoop but only import classes which are marked "public" from hadoop. Is it a better way to solve it?

**Comment by kellyzly** [comment]
@tgravescs 
 >  Did you test it with the YARN external shuffle service?"
    
Sorry, i have not tested on this situation and will test it later.

**Comment by kellyzly** [comment]
@tgravescs: I want ask a questions why org.apache.hadoop.mapreduce.MRJobConfig which marked "InterfaceAudience.Private" can be imported in org.apache.spark.deploy.yarn.Client.scala?

Line 795:
```
  private[yarn] def getDefaultMRApplicationClasspath: Option[Seq[String]] = {
    val triedDefault = Try[Seq[String]] {
      val field = classOf[MRJobConfig].getField("DEFAULT_MAPREDUCE_APPLICATION_CLASSPATH")
   ...
} 
```
org.apache.hadoop.mapreduce.MRJobConfig
```
@InterfaceAudience.Private
@InterfaceStability.Evolving
public interface MRJobConfig {
...
}
```

**Comment by kellyzly** [comment]
@srowen : the unit test fails. The error message like " /home/jenkins/workspace/SparkPullRequestBuilder/core/src/main/scala/org/apache/spark/storage/BlockObjectWriter.scala:26: object crypto is not a member of package org.apache.hadoop
[error] import org.apache.hadoop.crypto.CryptoCodec".  I guess that because $AMPLAB_JENKINS_BUILD_PROFILE in dev/run-tests is not set hadoop2.6,  how can we set the value to hadoop 2.6?

**Comment by srowen** [comment]
@kellyzly This change is a non-starter if it _requires_ Hadoop 2.6. Right now Spark works with versions back to about 1.0.4. Is this avoidable?

**Comment by tgravescs** [comment]
@kellyzly There is a jira to go cleanup anywhere we are using private interfaces. There may be a few we can't get away with but we should minimize.  In this case I don't think you really need MRJobConfig as I think you are just using it for convenience (unless I've missed something).  Its easy enough to create spark config for things like MR_ENCRYPTED_INTERMEDIATE_DATA_BUFFER_KB, DEFAULT_MR_ENCRYPTED_INTERMEDIATE_DATA_KEY_SIZE_BITS, etc..

Its also using this in common spark code whereas the other is in YARN specific code.

**Comment by tgravescs** [comment]
@kellyzly I think copying the CryptoInputStream and CryptoOutputStream classes would be more appropriate, but my question is do those class use private interfaces? do they rely on underlying hadoop functionality that was only added in hadoop 2.6 (like org.apache.hadoop.fs.crypto.CryptoFSDataInputStream)?  as mentioned if functionality only in 2.6 we either can't use it or have to use reflection to access. 

You also seem to be using CryptoCodec which is private.

**Comment by vanzin** [comment]
HI @kellyzly ,

> I want ask a questions why org.apache.hadoop.mapreduce.MRJobConfig which marked "InterfaceAudience.Private" can be imported in org.apache.spark.deploy.yarn.Client.scala?

That's hadoop's way of saying "this class is `public` because java-the-language requires it, but no one outside the hadoop project should be using it".

So you can import it and use it in your code, but hadoop may change or even delete it in the next version, and then your code will be broken.

**Comment by kellyzly** [comment]
@tgravescs: My teammates and i are trying to stripping classes like "CryptoInputStream.java" and "CryptoOutputStream.java" from package "org.apache.hadoop.crypto" in hadoop. There are 2 ways i think how to import all these codes to spark:
* create a module like "network" and all code is written in Java.
* create a package naming "org.apache.spark.crypto" in module "core", CryptoInputStream.java will be translated to scala version.

Which way do you think is more appropriate? Advice appreciated.

**Comment by srowen** [comment]
Mind closing this PR? this change can't proceed. I don't see why this code would be removed from Hadoop, or why a Spark version has to copy it.

**Comment by kellyzly** [comment]
@srowen,@tgravescs,@vanzin: Encrypted shuffle can make the process of shuffle more safer. I think it is necessary in spark. Previous design is reusing hadoop encrypted shuffle algorithm to enable spark encrypted shuffle. The design has a big problem that it imports many crypto classes like CryptoInputStream and CryptoOutputStream which is marked "private" in hadoop. Now my teammates and i decided to write the crypto classes in spark so no dependance to hadoop 2.6. Not directly copying hadoop code to spark, we only reference the crypto algorithm like JCE/AES-NI which is used in hadoop. Maybe i need rename the jira name from "Reuse hadoop encrypted shuffle algorithm to enable spark encrypted shuffle" to "Add encrypted shuffle in spark". Any advices are welcome.

**Comment by kellyzly** [comment]
@srowen,@tgravescs,@vanzin: Encrypted shuffle can make the process of shuffle more safer. I think it is necessary in spark. Previous design is reusing hadoop encrypted shuffle algorithm to enable spark encrypted shuffle. The design has a big problem that it imports many crypto classes like CryptoInputStream and CryptoOutputStream which is marked "private" in hadoop. Now my teammates and i decided to write the crypto classes in spark so no dependance to hadoop 2.6. Not directly copying hadoop code to spark, we only reference the crypto algorithm like JCE/AES-NI which is used in hadoop. Maybe i need rename the jira name from "Reuse hadoop encrypted shuffle algorithm to enable spark encrypted shuffle" to "Add encrypted shuffle in spark". Any advices are welcome.

**Comment by kellyzly** [comment]
@srowen,@tgravescs,@vanzin: Encrypted shuffle can make the process of shuffle more safer. I think it is necessary in spark. Previous design is reusing hadoop encrypted shuffle algorithm to enable spark encrypted shuffle. The design has a big problem that it imports many crypto classes like CryptoInputStream and CryptoOutputStream which is marked "private" in hadoop. Now my teammates and i decided to write the crypto classes in spark so no dependance to hadoop 2.6. Not directly copying hadoop code to spark, we only reference the crypto algorithm like JCE/AES-NI which is used in hadoop. Maybe i need rename the jira name from "Reuse hadoop encrypted shuffle algorithm to enable spark encrypted shuffle" to "Add encrypted shuffle in spark". Any advices are welcome.

**Comment by kellyzly** [comment]
@srowen,@tgravescs,@vanzin: Encrypted shuffle can make the process of shuffle more safer. I think it is necessary in spark. Previous design is reusing hadoop encrypted shuffle algorithm to enable spark encrypted shuffle. The design has a big problem that it imports many crypto classes like CryptoInputStream and CryptoOutputStream which is marked "private" in hadoop. Now my teammates and i decided to write the crypto classes in spark so no dependance to hadoop 2.6. Not directly copying hadoop code to spark, we only reference the crypto algorithm like JCE/AES-NI which is used in hadoop. Maybe i need rename the jira name from "Reuse hadoop encrypted shuffle algorithm to enable spark encrypted shuffle" to "Add encrypted shuffle in spark". Any advices are welcome.

**Comment by kellyzly** [comment]
@srowen,@tgravescs,@vanzin: Encrypted shuffle can make the process of shuffle more safer. I think it is necessary in spark. Previous design is reusing hadoop encrypted shuffle algorithm to enable spark encrypted shuffle. The design has a big problem that it imports many crypto classes like CryptoInputStream and CryptoOutputStream which is marked "private" in hadoop. Now my teammates and i decided to write the crypto classes in spark so no dependance to hadoop 2.6. Not directly copying hadoop code to spark, we only reference the crypto algorithm like JCE/AES-NI which is used in hadoop. Maybe i need rename the jira name from "Reuse hadoop encrypted shuffle algorithm to enable spark encrypted shuffle" to "Add encrypted shuffle in spark". Any advices are welcome.

**Comment by kellyzly** [comment]
@srowen,@tgravescs,@vanzin: Encrypted shuffle can make the process of shuffle more safer. I think it is necessary in spark. Previous design is reusing hadoop encrypted shuffle algorithm to enable spark encrypted shuffle. The design has a big problem that it imports many crypto classes like CryptoInputStream and CryptoOutputStream which is marked "private" in hadoop. Now my teammates and i decided to write the crypto classes in spark so no dependance to hadoop 2.6. Not directly copying hadoop code to spark, we only reference the crypto algorithm like JCE/AES-NI which is used in hadoop. Maybe i need rename the jira name from "Reuse hadoop encrypted shuffle algorithm to enable spark encrypted shuffle" to "Add encrypted shuffle in spark". Any advices are welcome.

**Comment by kellyzly** [comment]
@srowen,@tgravescs,@vanzin: Encrypted shuffle can make the process of shuffle more safer. I think it is necessary in spark. Previous design is reusing hadoop encrypted shuffle algorithm to enable spark encrypted shuffle. The design has a big problem that it imports many crypto classes like CryptoInputStream and CryptoOutputStream which is marked "private" in hadoop. Now my teammates and i decided to write the crypto classes in spark so no dependance to hadoop 2.6. Not directly copying hadoop code to spark, we only reference the crypto algorithm like JCE/AES-NI which is used in hadoop. Maybe i need rename the jira name from "Reuse hadoop encrypted shuffle algorithm to enable spark encrypted shuffle" to "Add encrypted shuffle in spark". Any advices are welcome.

**Comment by kellyzly** [comment]
@srowen,@tgravescs,@vanzin: Encrypted shuffle can make the process of shuffle more safer. I think it is necessary in spark. Previous design is reusing hadoop encrypted shuffle algorithm to enable spark encrypted shuffle. The design has a big problem that it imports many crypto classes like CryptoInputStream and CryptoOutputStream which is marked "private" in hadoop. Now my teammates and i decided to write the crypto classes in spark so no dependance to hadoop 2.6. Not directly copying hadoop code to spark, we only reference the crypto algorithm like JCE/AES-NI which is used in hadoop. Maybe i need rename the jira name from "Reuse hadoop encrypted shuffle algorithm to enable spark encrypted shuffle" to "Add encrypted shuffle in spark". Any advices are welcome.

**Comment by vanzin** [comment]
Hi @kellyzly ,

Renaming the PR sounds fine. But I see that the PR still has the old code. Are you planning on having the updated code up here soon? Otherwise, as @srowen suggests, we should close this, and you can open a new PR when you've addressed the issues with the current approach.

**Comment by kellyzly** [comment]
@vanzin:  I have renamed the jira name from "Reuse hadoop encrypted shuffle algorithm to enable spark encrypted shuffle" to "Add encrypted shuffle in spark". I will update code about 1 week later. So it is convenient for me to remain this PR.

File: core/src/main/scala/org/apache/spark/storage/BlockObjectWriter.scala [hunk 7]
```diff
@@ -123,12 +133,30 @@ private[spark] class DiskBlockObjectWriter(
...
 
+  private var sparkConf:SparkConf = null
+
   override def open(): BlockObjectWriter = {
     if (hasBeenClosed) {
       throw new IllegalStateException("Writer already closed. Cannot be reopened.")
     }
     fos = new FileOutputStream(file, true)
-    ts = new TimeTrackingOutputStream(fos)
+    val isEncryptedShuffle = sparkConf.getBoolean("spark.encrypted.shuffle", false)
```
Comment (CodingCat) [inline core/src/main/scala/org/apache/spark/storage/BlockObjectWriter.scala]: instead of implicitly suggesting that the creator of the object of this class must call setSparkConf (otherwise, it will throw a NPE), maybe we shall allow sparkConf be null here?

Comment (kellyzly) [inline core/src/main/scala/org/apache/spark/storage/BlockObjectWriter.scala]: @CodingCat , thanks for your comment, but i don't know which line will throw NPE in which situation? can you point out detaily? In BlockManager.scala#Line 654,  i have setSparkConf for DiskBlockObjectWriter

Comment (CodingCat) [inline core/src/main/scala/org/apache/spark/storage/BlockObjectWriter.scala]: I mean that is not straightforward for the client of this class to **MUST** call setSparkConf immediately after new a DiskBlockObjectWriter...otherwise this sparkConf will be null

Comment (kellyzly) [inline core/src/main/scala/org/apache/spark/storage/BlockObjectWriter.scala]: @CodingCat If we allow BlockObjectWriter#sparkConf is null, some configurations like "spark.encrypted.shuffle" and so on  can not be got.

Comment (CodingCat) [inline core/src/main/scala/org/apache/spark/storage/BlockObjectWriter.scala]: also, I'm curious about if you can pass the test case in https://github.com/apache/spark/blob/dcd1e42d6b6ac08d2c0736bf61a15f515a1f222b/core/src/test/scala/org/apache/spark/storage/BlockObjectWriterSuite.scala#L80

as in that test case, it calls open() without a call of setSparkConf before that....

Comment (CodingCat) [inline core/src/main/scala/org/apache/spark/storage/BlockObjectWriter.scala]: I mean null equals to spark.encrypted.shuffle not set....

Comment (kellyzly) [inline core/src/main/scala/org/apache/spark/storage/BlockObjectWriter.scala]: @CodingCat , thanks for your comment. I have modified https://github.com/kellyzly/spark/blob/master/core/src/main/scala/org/apache/spark/storage/BlockObjectWriter.scala#L143 as following:
```
   val isEncryptedShuffle: Boolean = if (sparkConf != null)
      sparkConf.getBoolean("spark.encrypted" +
        ".shuffle",
        false)
    else
      false
```
Later will submit the code, do you think it can solve the problem you pointed out?

Comment (CodingCat) [inline core/src/main/scala/org/apache/spark/storage/BlockObjectWriter.scala]: yeah, maybe the even better way to do this is to declare a boolean field with the default value of 'false' and a corresponding setter

the client of the class can set this value to true when necessary


BTW, according to

**Comment by kellyzly** [comment]
@tgravescs,@vanzin,@srowen,@JoshRosen,@CodingCat: I have updated code for your previous comments. Big change are made in this submission:
1.	Delete hadoop2.6 profile. We don't depend on hadoop 2.6 because I add crypto classes like CryptoInputStream.scala,CryptoOutputStream.scala and so on in core module org.apache.
Spark.crypto package.

File: core/src/main/scala/org/apache/spark/crypto/CryptoInputStream.scala [hunk 8]
```diff
@@ -0,0 +1,428 @@
...
+      super.close
+      freeBuffers
+      closed = true
+    }
+  }
+
+  /** Skip n bytes */
+  override def skip(nVal: Long): Long = {
+    var n: Long = nVal
+    Preconditions.checkArgument(n >= 0, "Negative skip length.", new Array[String](1))
```
Comment (steveloughran) [inline core/src/main/scala/org/apache/spark/crypto/CryptoInputStream.scala]: `throw new EOFException`

File: core/src/main/scala/org/apache/spark/crypto/CryptoInputStream.scala [hunk 9]
```diff
@@ -0,0 +1,428 @@
...
+    streamOffset = offset
+    inBuffer.clear
+    outBuffer.clear
+    outBuffer.limit(0)
+    updateDecryptor(decryptor, offset, iv)
+    padding = getPadding(offset)
+    inBuffer.position(padding)
+  }
+
+  override def close {
```
Comment (steveloughran) [inline core/src/main/scala/org/apache/spark/crypto/CryptoInputStream.scala]: see [https://issues.apache.org/jira/browse/HADOOP-11710](https://issues.apache.org/jira/browse/HADOOP-11710) for sync logic here & elsewhere

File: core/src/main/scala/org/apache/spark/crypto/CipherSuite.scala [hunk 10]
```diff
@@ -0,0 +1,72 @@
...
+
+  /**
+   * Returns suffix of cipher suite configuration.
+   * @return String configuration suffix
+   */
+  def getConfigSuffix(): String = {
+    val parts = name.split("/")
+    var suffix:StringBuilder = new StringBuilder()
+    parts.foreach(part =>
+      suffix.append(".").append(part.toLowerCase())
```
Comment (steveloughran) [inline core/src/main/scala/org/apache/spark/crypto/CipherSuite.scala]: `LOCALE_EN`

**Comment by steveloughran** [comment]
1. the `"InterfaceAudience.Private"` tags in Hadoop are a "please don't use` hint, although if you look at YARN AMs, they end up importing & using stuff which is tagged that way; you can't current do an AM which uses it. What it does mean is: they may be unintentionally changed, including signatures and semantics, and if they break your code, it's your responsibility to find that out and complain before the next hadoop release ships. Summary: test against hadoop trunk or at least beta releases.

2. The crypto code is still encountering a few stabilisation problems related to multithreading, stuff that doesn't show up in the unit tests. The code in 2.6 has already be supplanted by the code in branch-2/trunk. Forking off your own code means tracking those changes and keeping in sync...keeping the code in Java would aid diffing and cherry picking there. Even without trying to handle the quirks of the extended Hadoop streams, concurrency issues like [HADOOP-11710](https://issues.apache.org/jira/browse/HADOOP-11710) may matter.

3. There's also the problem that encryption performance comes from native binaries; which means for YARN deployments: either bind to the hadoop.so/.dll on the PATH , or push up a new version & extend PATH in container launch contexts, and on other deployments come up with new solutions. If you can stick to JCE routines (as this patch does) life may be simpler.

A standalone security JAR+ library would be better, with code shared by both Hadoop & other apps. You could talk to the Hadoop project about isolating it in Hadoop itself, though that will imply a separate native build & lib, etc.

The other tactic is to make the shuffle mechanism more pluggable, and on YARN clusters switch to an encrypted shuffle provided by a separate library, or use the YARN NM via whatever extension points need to be added. The latter tactic will avoid any native library path setup issues, and will allow alternative deployments (standalone, mesos) to switch to an encrypted shuffle later

**Comment by kellyzly** [comment]
@steveloughran:  Thanks for your valuables suggestions. 
 *  I will update latest crypto code in hadoop latest trunk and rewrite it to scala. I looked into HADOOP-11710 and found that it added "synchronized" in "flush", "close", "write" function in CryptoOutputStream.java to guarantee the thread safe. But I found that the outputStream ["TimeTrackingOutputStream"](https://github.com/kellyzly/spark/blob/8a74eea7d926507242c50b28c56962b1f1db256a/core/src/main/scala/org/apache/spark/storage/BlockObjectWriter.scala#L87) spark shuffle uses is not thread safe which means the situation when multi-threads write will not happen.

 > or use the YARN NM via whatever extension points need to be added.The latter tactic will avoid any native library path setup issues, and will allow alternative deployments (standalone, mesos) to switch to an encrypted shuffle later
 
 I don't understand the latter tactic, can extension points in YARN NM can resolve the native library path setup issues? if can, can you provide some links which describes more detaily?

File: core/src/main/scala/org/apache/spark/crypto/CipherSuite.scala (hunk 10 above)
Comment (kellyzly) [inline core/src/main/scala/org/apache/spark/crypto/CipherSuite.scala]: i don't understand LOCALE_EN, can you point out detaily?

File: core/src/main/scala/org/apache/spark/crypto/CryptoInputStream.scala (hunk 9 above)
Comment (kellyzly) [inline core/src/main/scala/org/apache/spark/crypto/CryptoInputStream.scala]: @steveloughran : i  updated the latest hadoop trunk code and found the CryptoInputStream.java#resetStreamOffset is same logic as what i provided in CryptoInputStream.scala#resetStreamOffset. And HADOOP-11710 relates CryptoOutputStream.java#write, CrypoOutputStream.java#flush, CryptoOutputStream.java#close.

**Comment by steveloughran** [comment]
Most of the sync changes in HADOOP-1170 was to deal with HBase's expectations. Even if you don't think it matters for its current use in spark, you should make the `close()` operation thread safe. It currently isn't.

Looking at hadoop trunk, recent changes to crypto packages include HADOOP-11674 , and HADOOP-11343 ; the latter looks like it's diverged from your code. I recommend you checkout hadoop/trunk locally , log recent changes to the crypto packages & track new ones, as things are still stabilising

w.r.t YARN NM resolving library differences: if the NM is handling the shuffle, it will have the relevant native lib for its hadoop-common.jar on its path, so will be in sync. Though that doesn't address the problem for the recipient, does it?

**Comment by kellyzly** [comment]
@steveloughran: i don't understand why need make CryptoOutputStream.scala#close safe. Is there situation when multiple threads call this function at the same time?

**Comment by kellyzly** [comment]
@steveloughran :  in hadoop, if we need add a native lib path to hadoop execution path, we need export LD_LIBRARY_PATH"
export LD_LIBRARY_PATH=xxxxx
in hadoop, LD_LIBRARY_PATH is saved in ContainerLaunchContext#environment.

so in spark, if we need add a native lib path to spark execution path, we just set the [ContainerLaunchContext#environment](https://github.com/kellyzly/spark/blob/b522f23438e119b2c987374ed6d64aa2b7317421/yarn/src/main/scala/org/apache/spark/deploy/yarn/Client.scala#l548)

**Comment by steveloughran** [comment]
@kellyzly 

> i don't understand why need make CryptoOutputStream.scala#close safe. Is there situation when
> multiple threads call this function at the same time?

It's general best practice, as you can't be confident of future uses. The current impl is re-entrant, and as it doesn't set `closed=true` in the finally clause, isn't actually guaranteed to set it.

**Comment by kellyzly** [comment]
@steveloughran: I have updated code according to your comments:[make CryptoOutputStream.scala#close safe](https://github.com/kellyzly/spark/blob/5629cc2b5308e97ce3459dbd2d2e63b4d9359f7e/core/src/main/scala/org/apache/spark/crypto/CryptoOutputStream.scala#l185). Have any other suggestions to current code?
