### PR TITLE
[SPARK-34778][BUILD] Upgrade to Avro 1.10.2

### PR DESCRIPTION
**Pull request by iemejia**
### What changes were proposed in this pull request?
Update the  Avro version to 1.10.2

### Why are the changes needed?
To stay up to date with upstream and catch compatibility issues with zstd

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Unit tests

### CODE REVIEW

File: pom.xml [hunk 1]
```diff
@@ -148,7 +148,7 @@
     the link to metrics.dropwizard.io in docs/monitoring.md.
     -->
     <codahale.metrics.version>4.1.1</codahale.metrics.version>
-    <avro.version>1.10.1</avro.version>
+    <avro.version>1.10.2</avro.version>
```
Comment (wangyum) [inline pom.xml:151]: File a new ticket for Avro 1.10.2 upgrade?

Comment (iemejia) [reply pom.xml:151]: I was thinking about reusing the existing one to avoid the duplicated message in the release notes:
[SPARK-27733] Upgrade to Avro 1.10.1
[SPARK-2XXXX] Upgrade to Avro 1.10.2

WDTY @wangyum? Should I create it still?

**Review by dongjoon-hyun — APPROVED** [review]
Thank you, @iemejia . +1, LGTM (Pending CIs).

I created a new JIRA, SPARK-34778, for this, @iemejia and @wangyum .

We are able to revert this and move back to Avro 1.10.1 (SPARK-27733) if there is a problem.

File: pom.xml (hunk 1 above)
Comment (iemejia) [reply pom.xml:151]: Ok rebasing to update the ticket number in the commit title.

**Comment by iemejia** [comment]
Rebased + Fixed the commit title. Can someone please trigger the CI, it seems not to be starting.

**Comment by dongjoon-hyun** [comment]
Thank you for update, @iemejia . However, you don't need to rebase or fix the commit title. Apache Spark community uses [the Spark merge script](https://github.com/apache/spark/blob/master/dev/merge_spark_pr.py) which brings GitHub PR title and PR description at the merge time. The original commit was okay because we don't use the existing commit title or commit message because we don't click `GitHub Merge` button.
> Rebased + Fixed the commit title. Can someone please trigger the CI, it seems not to be starting.

The GitHub Action CIs are queued. It seems to be delayed by the Apache GitHub Action capacity issue. I'll keep my eyes on it.

**Review by viirya — APPROVED** [review]

**Comment by iemejia** [comment]
Oh nice, great to know that title is auto fixed. Nice automation. Thanks also for creating the issue @dongjoon-hyun now time to wait for this to become green.

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Ur, @iemejia .
Could you check Apache Avro 1.10.2's Jackson dependency change?
- https://github.com/apache/avro/commit/4fc027521a23c8af16217f8eb9933bd1a9846c51 `Bump jackson.version from 2.11.4 to 2.12.1 in /lang/java`
- https://github.com/apache/avro/commit/aaf2f79e3258d817006f1550e8e639bc2bd061e6 `Bump jackson.version from 2.12.1 to 2.12.2 in /lang/java` (https://github.com/apache/avro/pull/1121)

Apache Spark is still on `Jackson 2.11.4`.
```
<fasterxml.jackson.version>2.11.4</fasterxml.jackson.version>
```

**Comment by dongjoon-hyun** [comment]
Well. We are in the difficult situation, @wangyum and @iemejia .

We upgraded Jackson via SPARK-33766 (#30746) for Avro and Parquet. We cannot upgrade to Avro 1.10.2 because Jackson 2.11 is not compatible with 2.12.
```
Make it easy to upgrade dependency because Jackson 2.10 is not compatible with 2.11:
- [Avro](https://issues.apache.org/jira/browse/AVRO-2967) has upgraded Jackson to 2.11.3.
- [Parquet](https://issues.apache.org/jira/browse/PARQUET-1895) has upgraded Jackson to 2.11.2.
```

**Comment by wangyum** [comment]
We can upgrade Jackson to 2.12.2: https://github.com/apache/spark/pull/31878

**Comment by dongjoon-hyun** [comment]
Could you confirm that it works with Apache Parquet 1.12.0 well, @wangyum ?

> We can upgrade Jackson to 2.12.2: #31878

**Comment by dongjoon-hyun** [comment]
FYI, Apache Parquet 1.12.0 RC4 vote started today, but it is still on `Avro 1.10.1` . The following patch is only at Apache Parquet master branch.
- https://github.com/apache/parquet-mr/pull/882 (https://issues.apache.org/jira/browse/PARQUET-2001 Bump Apache Avro to 1.10.2)

**Comment by iemejia** [comment]
For ref https://github.com/apache/parquet-mr/pull/883

**Comment by wangyum** [comment]
It seems Avro 1.10.2 has compatibility issues:
```
[info] Caused by: java.lang.NoSuchMethodError: org.apache.avro.file.CodecFactory.zstandardCodec(IZZ)Lorg/apache/avro/file/CodecFactory;
[info] 	at org.apache.avro.mapreduce.AvroOutputFormatBase.getCompressionCodec(AvroOutputFormatBase.java:77)
[info] 	at org.apache.avro.mapreduce.AvroKeyOutputFormat.getRecordWriter(AvroKeyOutputFormat.java:106)
[info] 	at org.apache.spark.sql.avro.AvroOutputWriter.<init>(AvroOutputWriter.scala:78)
```
https://github.com/apache/spark/pull/31649/checks?check_run_id=2146239842

**Comment by iemejia** [comment]
It seems that an earlier version of the Avro dependency (1.10.1 maybe) is leaking from another dependency because the method mentioned was introduced in Avro 1.10.2 by @dongjoon-hyun as part of his zstd improvements. We need to dig deeper to know where is the leaker (Parquet maybe?)

**Comment by dongjoon-hyun** [comment]
Yes, it seems that we are on the running train. BTW, AFAIK, we are using a single ZSTD JNI library (1.4.9-1) here.
- Apache Spark 3.2.0 (master): https://github.com/apache/spark/blob/master/pom.xml#L709
- Apache Parquet 1.12.0 (RC3/RC4): https://github.com/apache/parquet-mr/commit/66ac28ce232c586626f53b72110276ea45ec5fa2
- Apache Avro 1.10.2 (Optional ZSTD dependency, https://mvnrepository.com/artifact/org.apache.avro/avro/1.10.2)
- Apache Kafka 2.8.0 (https://github.com/apache/kafka/commit/893895bb9d7b87c7a4ebc6347089df431f715552)

So, I believe we can exclude out ZSTD JNI library itself.

**Comment by dongjoon-hyun** [comment]
BTW, to be clear, I agree with the above analysis.
> It seems that an earlier version of the Avro dependency (1.10.1 maybe) is leaking from another dependency.... We need to dig deeper to know where is the leaker (Parquet maybe?)

The problem is that it will be unsafe to cut Parquet's Avro transitive dependency.

**Review by wangyum — CHANGES_REQUESTED** [review]
Please also update https://github.com/apache/spark/blob/4b4bd977b14fbc279238ef02b4242da65d81dd55/project/SparkBuild.scala#L664 to 1.10.2.

**Comment by iemejia** [comment]
Done @wangyum hoping this will unblock it :crossed_fingers:

> Parquet 1.12.0 using Avro 1.10.1 can not work with Avro 1.10.2.

@dongjoon-hyun can you help us by giving the details in the Parquet thread to see if we can convince the Parquet community to add this to their release.

**Comment by dongjoon-hyun** [comment]
@iemejia . I really want to have Apache Parquet 1.12.0. However, I'm not sure if the Jackson dependency change is safe or not.

If Apache Avro and Apache Parquet are going to have that breaking changes, Apache Spark community definitely will try to embrace it in Apache Spark 3.2.0. However, if we found some issues, Apache Spark community cannot upgrade to Apache Avro 1.10.2 and Apache Parquet 1.12.0 for a long period. We will still to use old Avro and Parquet. That is the worst case I want to avoid.

**Comment by wangyum** [comment]
Jenkins, retest this please.

**Comment by wangyum** [comment]
Please also update Avro version in these files:
https://github.com/apache/spark/blob/e9e81f798fc2c4a936b967b0e5fb13fd5dfdeb69/project/plugins.sbt
https://github.com/apache/spark/blob/e9e81f798fc2c4a936b967b0e5fb13fd5dfdeb69/external/avro/src/main/scala/org/apache/spark/sql/avro/AvroOptions.scala
https://github.com/apache/spark/blob/612d52315b8476dd588d75ce3001dee5786db747/docs/sql-data-sources-avro.md

**Comment by wangyum** [comment]
ok to test.

**Comment by dongjoon-hyun** [comment]
Jackson is upgraded to 2.12.2. Could you rebase this PR to the master once more, please? @iemejia 
- https://github.com/apache/spark/commit/2888d1883ecd8dd3d26f7fee4d921fb01618a7ca

**Comment by iemejia** [comment]
Done!

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs)

**Comment by HyukjinKwon** [comment]
cc @gengliangwang FYI.

**Review by HyukjinKwon — APPROVED** [review]
LGTM2

**Comment by wangyum** [comment]
We also need to update the Avro version in these files:
https://github.com/apache/spark/blob/e9e81f798fc2c4a936b967b0e5fb13fd5dfdeb69/project/plugins.sbt
https://github.com/apache/spark/blob/e9e81f798fc2c4a936b967b0e5fb13fd5dfdeb69/external/avro/src/main/scala/org/apache/spark/sql/avro/AvroOptions.scala
https://github.com/apache/spark/blob/612d52315b8476dd588d75ce3001dee5786db747/docs/sql-data-sources-avro.md

**Review by gengliangwang — APPROVED** [review]
LGTM

**Comment by iemejia** [comment]
Added the requested files @wangyum PTAL. Sorry for not catching this before, next time I will do a `grep`. We should be good to go now.

**Review by wangyum — APPROVED** [review]

**Comment by wangyum** [comment]
Merged to master.

**Comment by dongjoon-hyun** [comment]
Thank you, @iemejia and all!
