### PR TITLE
[SPARK-6908] [SQL] Use isolated Hive client

### PR DESCRIPTION
**Pull request by marmbrus**
This PR switches Spark SQL's Hive support to use the isolated hive client interface introduced by #5851, instead of directly interacting with the client.  By using this isolated client we can now allow users to dynamically configure the version of Hive that they are connecting to by setting `spark.sql.hive.metastore.version` without the need recompile.  This also greatly reduces the surface area for our interaction with the hive libraries, hopefully making it easier to support other versions in the future.

Jars for the desired hive version can be configured using `spark.sql.hive.metastore.jars`, which accepts the following options:
- a colon-separated list of jar files or directories for hive and hadoop.
- `builtin` - attempt to discover the jars that were used to load Spark SQL and use those. This
          option is only valid when using the execution version of Hive.
- `maven` - download the correct version of hive on demand from maven.

By default, `builtin` is used for Hive 13.

This PR also removes the test step for building against Hive 12, as this will no longer be required to talk to Hive 12 metastores.  However, the full removal of the Shim is deferred until a later PR.

Remaining TODOs:
- Remove the Hive Shims and inline code for Hive 13.
- Several HiveCompatibility tests are not yet passing. 
  - `nullformatCTAS` - As detailed below, we now are handling CTAS parsing ourselves instead of hacking into the Hive semantic analyzer.  However, we currently only handle the common cases and not things like CTAS where the null format is specified.
  - `combine1` now leaks state about compression somehow, breaking all subsequent tests.  As such we currently add it to the blacklist
  - `part_inherit_tbl_props` and `part_inherit_tbl_props_with_star` do not work anymore.  We are correctly propagating the information 
  - "load_dyn_part14.*" - These tests pass when run on their own, but fail when run with all other tests.  It seems our `RESET` mechanism may not be as robust as it used to be?

Other required changes:
-  `CreateTableAsSelect` no longer carries parts of the HiveQL AST with it through the query execution pipeline.  Instead, we parse CTAS during the HiveQL conversion and construct a `HiveTable`.  The full parsing here is not yet complete as detailed above in the remaining TODOs.  Since the operator is Hive specific, it is moved to the hive package.
- `Command` is simplified to be a trait that simply acts as a marker for a LogicalPlan that should be eagerly evaluated.

### CODE REVIEW

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveQl.scala [hunk 1]
```diff
@@ -565,7 +579,62 @@ https://cwiki.apache.org/confluence/display/Hive/Enhanced+Aggregation%2C+Cube%2C
...
+          partitionColumns = Seq.empty,
+          properties = Map.empty,
+          serdeProperties = Map.empty,
+          tableType = ManagedTable,
+          location = None,
+          inputFormat = None,
+          outputFormat = None,
+          serde = None)
+
+      // TODO: Handle all the cases here...
```
Comment (marmbrus) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveQl.scala]: @chenghao-intel, do you have time to help finish the implementation here.  I had to remove your version that relied on Hive's semantic analyzer.

**Comment by chenghao-intel** [comment]
@marmbrus unit test passed. I will update the code for supporting SerDe once this merged.

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala [hunk 2]
```diff
@@ -93,9 +99,129 @@ class HiveContext(sc: SparkContext) extends SQLContext(sc) {
...
+  protected[hive] lazy val localMetastore = {
+    val temp = Utils.createTempDir()
+    temp.delete()
+    temp
+  }
+
+  @transient
+  protected[hive] lazy val executionConf = new HiveConf()
+  executionConf.set(
+    "javax.jdo.option.ConnectionURL", s"jdbc:derby:;databaseName=$localMetastore;create=true")
```
Comment (yhuai) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: We will not contact this metastore and the only purpose of it is to make the Hive used for execution happy, right?

**Comment by yhuai** [comment]
Seems we can remove the lock at https://github.com/marmbrus/spark/blob/useIsolatedClient/sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveMetastoreCatalog.scala#L73.

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala (hunk 2 above)
Comment (marmbrus) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: Correct, but some operations do instantiate the client so we need to point it at a dummy database otherwise in many cases derby will complain that more that one processes is trying to open the database.

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveMetastoreCatalog.scala [hunk 3]
```diff
@@ -144,39 +147,43 @@ private[hive] class HiveMetastoreCatalog(hive: HiveContext) extends Catalog with
...
-    val currentDatabase = client.getDatabase(hive.sessionState.getCurrentDatabase)
-
-    hiveWarehouse.getTablePath(currentDatabase, tableName).toString
+    // Code based on: hiveWarehouse.getTablePath(currentDatabase, tableName)
+    new Path(
+      new Path(client.getDatabase(client.currentDatabase).location),
+      tableName.toLowerCase).toString
   }
 
   def tableExists(tableIdentifier: Seq[String]): Boolean = synchronized {
```
Comment (yhuai) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveMetastoreCatalog.scala]: Should we remove this explicit `synchronized`? There are a few places where we still have it.

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveQl.scala [hunk 4]
```diff
@@ -1080,6 +1149,15 @@ https://cwiki.apache.org/confluence/display/Hive/Enhanced+Aggregation%2C+Cube%2C
   }
 
   protected val escapedIdentifier = "`([^`]+)`".r
+  protected val singleQuotedString = "\"([^\"]+)\"".r
+  protected val doubleQuotedString = "'([^']+)'".r
```
Comment (yhuai) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveQl.scala]: typo?
```
protected val doubleQuotedString = "\"([^\"]+)\"".r
protected val singleQuotedString = "'([^']+)'".r
```

File: sql/hive-thriftserver/src/main/scala/org/apache/spark/sql/hive/thriftserver/SparkSQLCLIDriver.scala [hunk 5]
```diff
@@ -74,7 +74,16 @@ private[hive] object SparkSQLCLIDriver {
...
     }
 
-    val sessionState = new CliSessionState(new HiveConf(classOf[SessionState]))
+    val localMetastore = {
+      val temp = Utils.createTempDir()
+      temp.delete()
+      temp
+    }
+    val cliConf = new HiveConf(classOf[SessionState])
+    // Override the location of the metastore since this is only used for local execution.
```
Comment (vanzin) [inline sql/hive-thriftserver/src/main/scala/org/apache/spark/sql/hive/thriftserver/SparkSQLCLIDriver.scala]: So, if I understand this correctly, you're creating just a "dummy" local metastore that won't actually be used; this is just to keep the Hive libraries happy, right?

File: sql/hive-thriftserver/src/main/scala/org/apache/spark/sql/hive/thriftserver/SparkSQLCLIDriver.scala [hunk 6]
```diff
@@ -74,7 +74,16 @@ private[hive] object SparkSQLCLIDriver {
       System.exit(1)
     }
 
-    val sessionState = new CliSessionState(new HiveConf(classOf[SessionState]))
+    val localMetastore = {
+      val temp = Utils.createTempDir()
+      temp.delete()
```
Comment (vanzin) [inline sql/hive-thriftserver/src/main/scala/org/apache/spark/sql/hive/thriftserver/SparkSQLCLIDriver.scala]: Instead of this I'd use "$temp/something" as the metastore directory, to avoid the "temp" directory being created by another process before Hive has a chance to do it.

File: sql/hive-thriftserver/src/main/scala/org/apache/spark/sql/hive/thriftserver/SparkSQLCLIDriver.scala [hunk 7]
```diff
@@ -91,10 +100,14 @@ private[hive] object SparkSQLCLIDriver {
...
     // Set all properties specified via command line.
     val conf: HiveConf = sessionState.getConf
-    sessionState.cmdProperties.entrySet().foreach { item: java.util.Map.Entry[Object, Object] =>
-      conf.set(item.getKey.asInstanceOf[String], item.getValue.asInstanceOf[String])
-      sessionState.getOverriddenConfigurations.put(
-        item.getKey.asInstanceOf[String], item.getValue.asInstanceOf[String])
+    sessionState.cmdProperties.entrySet().foreach { item =>
+      val key = item.getKey.asInstanceOf[String]
+      val value = item.getValue.asInstanceOf[String]
+      // We do not propogate metastore options to the execution copy of hive.
```
Comment (vanzin) [inline sql/hive-thriftserver/src/main/scala/org/apache/spark/sql/hive/thriftserver/SparkSQLCLIDriver.scala]: nit: propagate

File: sql/hive-thriftserver/src/main/scala/org/apache/spark/sql/hive/thriftserver/SparkSQLEnv.scala [hunk 8]
```diff
@@ -51,6 +52,12 @@ private[hive] object SparkSQLEnv extends Logging {
       sparkContext.addSparkListener(new StatsReportListener())
       hiveContext = new HiveContext(sparkContext)
 
+      hiveContext.metadataHive.setOut(new PrintStream(System.out, true, "UTF-8"))
```
Comment (vanzin) [inline sql/hive-thriftserver/src/main/scala/org/apache/spark/sql/hive/thriftserver/SparkSQLEnv.scala]: nit: is UTF-8 the right thing here? It's not the default encoding on all platforms. Maybe omit that argument (which probably means using the platform default, even though the javadocs don't explicitly mention that)?

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala [hunk 9]
```diff
@@ -93,9 +99,129 @@ class HiveContext(sc: SparkContext) extends SQLContext(sc) {
...
+   * this does not necessarily need to be the same version of Hive that is used internally by
+   * Spark SQL for execution.
+   */
+  protected[hive] def hiveMetastoreVersion: String =
+    getConf(HIVE_METASTORE_VERSION, "0.13.1")
+
+  /**
+   * The location of the jars that should be used to instantiate the HiveMetastoreClient.  This
+   * property can be one of three options:
+   *  - a colon-separated list of jar files or directories for hive and hadoop.
```
Comment (vanzin) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: Shouldn't this be just a classpath? Paths on Win32 are separated by semi-colons, and colons might behave differently there (aside from not being "natural" for Win32 users).

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala [hunk 10]
```diff
@@ -93,9 +99,129 @@ class HiveContext(sc: SparkContext) extends SQLContext(sc) {
...
+   */
+  protected[hive] def hiveMetastoreJars: String =
+    getConf(HIVE_METASTORE_JARS, "builtin")
+
   @transient
   protected[sql] lazy val substitutor = new VariableSubstitution()
 
+
+  /** A local instance of hive that is only used for execution. */
+  protected[hive] lazy val localMetastore = {
```
Comment (vanzin) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: Is there any way you can share this code with the CLI driver?

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala [hunk 11]
```diff
@@ -93,9 +99,129 @@ class HiveContext(sc: SparkContext) extends SQLContext(sc) {
...
+    temp
+  }
+
+  @transient
+  protected[hive] lazy val executionConf = new HiveConf()
+  executionConf.set(
+    "javax.jdo.option.ConnectionURL", s"jdbc:derby:;databaseName=$localMetastore;create=true")
+
+  /** The version of hive used internally by Spark SQL. */
+  lazy val hiveExecutionVersion: String = "0.13.1"
```
Comment (vanzin) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: Why lazy? I'm also seeing this string in a bunch of places, might be better to have a constant somewhere.

File: sql/hive-thriftserver/src/main/scala/org/apache/spark/sql/hive/thriftserver/SparkSQLEnv.scala (hunk 8 above)
Comment (yhuai) [inline sql/hive-thriftserver/src/main/scala/org/apache/spark/sql/hive/thriftserver/SparkSQLEnv.scala]: See https://github.com/apache/hive/blob/release-0.13.1/cli/src/java/org/apache/hadoop/hive/cli/CliDriver.java#L650-653

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala [hunk 12]
```diff
@@ -93,9 +99,129 @@ class HiveContext(sc: SparkContext) extends SQLContext(sc) {
...
+   * for storing peristent metadata, and only point to a dummy metastore in a temporary directory.
+   */
+  @transient
+  protected[hive] lazy val executionHive: ClientWrapper = {
+    logInfo(s"Initilizing execution hive, version $hiveExecutionVersion")
+    new ClientWrapper(
+      version = IsolatedClientLoader.hiveVersion(hiveExecutionVersion),
+      config = Map(
+        "javax.jdo.option.ConnectionURL" ->
+        s"jdbc:derby:;databaseName=$localMetastore;create=true"))
```
Comment (vanzin) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: Same similar code again... maybe have this map as a `lazy val` somewhere, and have the temp dir be created there too? Then reference that `val` from the (so far) 3 call sites.

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala [hunk 13]
```diff
@@ -93,9 +99,129 @@ class HiveContext(sc: SparkContext) extends SQLContext(sc) {
...
+   * The version of the Hive client that is used here must match the metastore that is configured
+   * in the hive-site.xml file.
+   */
+  @transient
+  protected[hive] lazy val metadataHive: ClientInterface = {
+    val metaVersion = IsolatedClientLoader.hiveVersion(hiveMetastoreVersion)
+
+    // We instantiate a HiveConf here to read in the hive-site.xml file and then pass the options
+    // into the isolated client loader
+    val metadataConf = new HiveConf()
```
Comment (vanzin) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: I think this should be:

    new HiveConf(SparkHadoopUtil.get.newConfiguration(sparkConf), classOf[HiveConf])

That would allow users to override configs using `spark.hadoop.*`.

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala [hunk 14]
```diff
@@ -93,9 +99,129 @@ class HiveContext(sc: SparkContext) extends SQLContext(sc) {
...
+    } else if (hiveMetastoreJars == "maven") {
+      // TODO: Support for loading the jars from an already downloaded location.
+      logInfo(
+        s"Initializing HiveMetastoreConnection version $hiveMetastoreVersion using maven.")
+      IsolatedClientLoader.forVersion(hiveMetastoreVersion, allConfig )
+    } else {
+      // Convert to files and expand any directories.
+      val jars =
+        hiveMetastoreJars
+          .split(":")
```
Comment (vanzin) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: Follow-up to previous comment: I think this should be `File.pathSeparator`.

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala [hunk 15]
```diff
@@ -93,9 +99,129 @@ class HiveContext(sc: SparkContext) extends SQLContext(sc) {
...
+          .map(new java.io.File(_))
+          .flatMap {
+            case f if f.isDirectory => f.listFiles()
```
Comment (vanzin) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: Hmmm... this is not how classpaths generally work. Directories are added directly to the classpath, not its children. This means that I can't add an exploded jar (i.e. a directory with a bunch of classes in it) using this config.

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/execution/CreateTableAsSelect.scala [hunk 16]
```diff
@@ -39,17 +39,34 @@ import org.apache.spark.sql.hive.MetastoreRelation
...
+      import org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
+      import org.apache.hadoop.io.Text
+      import org.apache.hadoop.mapred.TextInputFormat
+
+      val withSchema =
+        tableDesc.copy(
+          schema =
+            query.output.map(c =>
+              HiveColumn(c.name, HiveMetastoreTypes.toMetastoreType(c.dataType), null)),
+            inputFormat =
```
Comment (vanzin) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/execution/CreateTableAsSelect.scala]: indentation looks off here; shouldn't this be aligned with `schema =`?

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/test/TestHive.scala [hunk 17]
```diff
@@ -70,24 +71,22 @@ class TestHiveContext(sc: SparkContext) extends HiveContext(sc) {
...
   /** Sets up the system initially or after a RESET command */
-  protected def configure(): Unit = {
-    warehousePath.delete()
-    metastorePath.delete()
-    setConf("javax.jdo.option.ConnectionURL",
-      s"jdbc:derby:;databaseName=$metastorePath;create=true")
-    setConf("hive.metastore.warehouse.dir", warehousePath.toString)
-  }
+  protected override def configure(): Map[String, String] = Map(
+      "javax.jdo.option.ConnectionURL" -> s"jdbc:derby:;databaseName=$metastorePath;create=true",
```
Comment (vanzin) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/test/TestHive.scala]: 4th instance... but who's counting. :-)

**Comment by vanzin** [comment]
I left a few comments mostly around the configuration parts of the change. I'm not really familiar with the rest to comment.

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala (hunk 11 above)
Comment (marmbrus) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: Its lazy because it ends up getting invoked during the constructor before it can be initialized, but you make a good point.  I've moved it to the HiveContext singleton and replaced other usages.

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala (hunk 14 above)
Comment (marmbrus) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: Good call.

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala (hunk 15 above)
Comment (marmbrus) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: I guess I was trying to simplify the case where you want to include all the jars in a directory, but I think that you are right that deviation from standard classpath behavior is more confusing that its worth.

Comment (vanzin) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: If you want to implement that behavior, that's `directory/*` in classpath. That only adds files that end in `.jar`. From the [docs](https://docs.oracle.com/javase/6/docs/technotes/tools/windows/classpath.html):

    Class path entries can contain the basename wildcard character *, which is considered equivalent to specifying a list of all the files in the directory with the extension .jar or .JAR.

File: sql/hive-thriftserver/src/main/scala/org/apache/spark/sql/hive/thriftserver/SparkSQLCLIDriver.scala (hunk 6 above)
Comment (marmbrus) [inline sql/hive-thriftserver/src/main/scala/org/apache/spark/sql/hive/thriftserver/SparkSQLCLIDriver.scala]: Ah yes, that is much nicer :)

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala (hunk 13 above)
Comment (marmbrus) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: I'm less sure about this one.  You can already override config the standard way using `hive-site.xml`. what is the advantage of this way?  If we were to do this would we want it to be spark.hive.*?  I'm not really opposed, I'd just like to avoid having too many paths for configuration.

Comment (vanzin) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: It's more for consistency than anything else. It also allows you to easily override things in the `spark-submit` command line or in `spark-defaults.conf` if you need some Spark-specific configuration for Hive and don't want to change the global Hive configuration.

Comment (marmbrus) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: Okay, thats reasonable.  I'd like to defer that to a follow up though as we've never allowed overriding the hive conf like this in the past.

**Comment by marmbrus** [comment]
Thanks for the comments @vanzin, I think I have addressed everything except the ability to configure hive through `spark.hadoop.*`.

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala [hunk 18]
```diff
@@ -439,7 +455,21 @@ class HiveContext(sc: SparkContext) extends SQLContext(sc) {
...
-private object HiveContext {
+private[hive] object HiveContext {
+  /** The version of hive used internally by Spark SQL. */
+  val hiveExecutionVersion: String = "0.13.1"
+
+  val HIVE_METASTORE_VERSION: String = "spark.sql.hive.metastore.version"
+  val HIVE_METASTORE_JARS: String = "spark.sql.hive.metastore.jars"
+
+  /** Constructs a configuration for hive, where the metastore is located in a temp directory. */
+  def newTemporaryConfiguation(): Map[String, String] = {
```
Comment (vanzin) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: typo: Configuration

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala [hunk 19]
```diff
@@ -439,7 +455,21 @@ class HiveContext(sc: SparkContext) extends SQLContext(sc) {
...
+    val tempDir = Utils.createTempDir()
+    val localMetastore = new File(tempDir, "metastore")
```
Comment (vanzin) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: nit: `new File(tempDir, "metastore").getAbsolutePath`. Just in case.

File: sql/hive-thriftserver/src/main/scala/org/apache/spark/sql/hive/thriftserver/SparkSQLCLIDriver.scala [hunk 20]
```diff
@@ -74,7 +74,17 @@ private[hive] object SparkSQLCLIDriver {
       System.exit(1)
     }
 
-    val sessionState = new CliSessionState(new HiveConf(classOf[SessionState]))
+    val localMetastore = {
```
Comment (vanzin) [inline sql/hive-thriftserver/src/main/scala/org/apache/spark/sql/hive/thriftserver/SparkSQLCLIDriver.scala]: Use `newTemporaryConfiguation` [sic] here?

Comment (vanzin) [inline sql/hive-thriftserver/src/main/scala/org/apache/spark/sql/hive/thriftserver/SparkSQLCLIDriver.scala]: Actually, you already are, you just need to remove this block.

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala [hunk 21]
```diff
@@ -93,9 +100,113 @@ class HiveContext(sc: SparkContext) extends SQLContext(sc) {
...
+      // Convert to files and expand any directories.
+      val jars =
+        hiveMetastoreJars
+          .split(File.pathSeparator)
+          .flatMap {
+            case path if path.endsWith("*") =>
+              val directory = new File(path.dropRight(1))
+              directory.listFiles.filter(_.getName.endsWith("jar"))
+            case path =>
+              new File(path) :: Nil
```
Comment (vanzin) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: nit: this looks a little weird, why not `Some(new File(path))` or something equivalent?

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala [hunk 22]
```diff
@@ -93,9 +100,113 @@ class HiveContext(sc: SparkContext) extends SQLContext(sc) {
...
+      logInfo(
+        s"Initializing HiveMetastoreConnection version $hiveMetastoreVersion using maven.")
+      IsolatedClientLoader.forVersion(hiveMetastoreVersion, allConfig )
+    } else {
+      // Convert to files and expand any directories.
+      val jars =
+        hiveMetastoreJars
+          .split(File.pathSeparator)
+          .flatMap {
+            case path if path.endsWith("*") =>
```
Comment (vanzin) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: If you want to be really, really correct here, probably should be:

    case path if new File(path).getName() == "*" =>
      new File(path).getParentFile().listFiles().filter(_.getName().toLower().endsWith(".jar"))

Also, should probably check whether the parent directory actually exists, otherwise you'll get an NPE since `listFiles()` will return `null`.

**Comment by vanzin** [comment]
Just a couple of comments left, otherwise the parts I commented on look good. Thanks!

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala (hunk 22 above)
Comment (marmbrus) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: Out of curiosity, when would `if new File(path).getName() == "*"` and `path.endsWith("*")` be different?

Comment (vanzin) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: `/glob*`

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala (hunk 21 above)
Comment (marmbrus) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: This is the idomatic way to create lists.  After investigating it seems its somewhat isolated to `sql` but we do this ~700 other times in the codebase.

File: sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala (hunk 22 above)
Comment (marmbrus) [inline sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveContext.scala]: Oh, obviously.  Updated, with null checks and everything :)

**Comment by marmbrus** [comment]
test this please

**Comment by yhuai** [comment]
LGTM. I will merging it to master and branch 1.4.

**Comment by coderfi** [comment]
Has this been tested with mapr4?

When running under python, I am running into an exception

Caused by: java.lang.UnsatisfiedLinkError: Native Library /tmp/mapr-root-libMapRClient.4.0.2-mapr.so already loaded in another classloader
    at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1931)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
    at java.lang.Runtime.load0(Runtime.java:795)
    at java.lang.System.load(System.java:1062)
    at com.mapr.fs.shim.LibraryLoader.load(LibraryLoader.java:29)

This occurs under the following scenarios:
   create a spark context + hive context
   run a hive query
   stop the spark context
   create another spark context + hive context again
   run a hive query
   I get the Native Library exception

From what I can tell, when the ClassLoader is hitting a MAPR class which is attempting to load the native library (I presume, as part of a static initializer).
Unfortunately, the JVM prohibits this the second time around. :(

I could file a ticket with a full stack trace if you'd like.
   
thanks,
Fi

**Comment by marmbrus** [comment]
Yes, please file a JIRA.

**Comment by coderfi** [comment]
K. Filed as https://issues.apache.org/jira/browse/SPARK-7819

thank you for looking into this!

Fi

**Comment by jeanlyn** [comment]
I set the metastore to `0.12.0` by follow steps ,but get classnotdef exception:
* I chang the `spark.sql.hive.metastore.version` in `spark-defaults.conf` to `0.12.0`,i got
* set `spark.sql.hive.metastore.jars` to `maven`,or set `spark.sql.hive.metastore.jars` to classpath of hadoop and hive i got 
```
 java.lang.NoClassDefFoundError: com/google/common/base/Preconditions when creating Hive client using classpath
```
I am not sure i am understand correctly.

**Comment by jeanlyn** [comment]
I can use the build in class(0.13.1) to connect `0.12.0` metastore correctly except some warn and error which does not effect running
```
5/06/01 21:20:09 WARN metastore.RetryingMetaStoreClient: MetaStoreClient lost connection. Attempting to reconnect.
org.apache.thrift.TApplicationException: Invalid method name: 'get_functions'
       at org.apache.thrift.TApplicationException.read(TApplicationException.java:108)
       at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:71)
       at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_get_functions(ThriftHiveMetastore.java:2886)
       at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.get_functions(ThriftHiveMetastore.java:2872)
       at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getFunctions(HiveMetaStoreClient.java:1727)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
       at java.lang.reflect.Method.invoke(Method.java:597)
       at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:89)
       at $Proxy10.getFunctions(Unknown Source)
       at org.apache.hadoop.hive.ql.metadata.Hive.getFunctions(Hive.java:2670)
       at org.apache.hadoop.hive.ql.exec.FunctionRegistry.getFunctionNames(FunctionRegistry.java:674)
       at org.apache.hadoop.hive.ql.exec.FunctionRegistry.getFunctionNames(FunctionRegistry.java:662)
       at org.apache.hadoop.hive.cli.CliDriver.getCommandCompletor(CliDriver.java:540)
       at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver$.main(SparkSQLCLIDriver.scala:174)
       at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.main(SparkSQLCLIDriver.scala)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
       at java.lang.reflect.Method.invoke(Method.java:597)
       at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:664)
       at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:169)
       at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:192)
       at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:111)
       at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
15/06/01 21:20:10 INFO hive.metastore: Trying to connect to metastore with URI thrift://172.19.154.28:9084
15/06/01 21:20:10 INFO hive.metastore: Connected to metastore.
15/06/01 21:20:10 ERROR exec.FunctionRegistry: org.apache.hadoop.hive.ql.metadata.HiveException: org.apache.thrift.TApplicationException: Invalid method name: 'get_functions'
spark-sql>
```
Thanks

**Comment by yhuai** [comment]
@jeanlyn The warning message related `get_functions` is expected if you are using a Hive 0.13.1 metastore client to connect to a Hive 0.12.0 metastore server because `get_functions` was not in Hive 0.12.0. Regarding using Hive 0.12 metastore client, can you post the full stack trace? Also, we can move our discussion to user mailing list. So, people who may have the same question can see our thread.

**Comment by yhuai** [comment]
@jeanlyn I think you are hitting https://issues.apache.org/jira/browse/SPARK-8020.

**Comment by dougb** [comment]
FYI, this change broke getting a DF via `sqlContext.table("database.table")` 
which worked from `1.3.0` up until this pr.
