### PR TITLE
[SPARK-15334][SQL][HOTFIX] Fixes compilation error for Scala 2.10

### PR DESCRIPTION
**Pull request by liancheng**
## What changes were proposed in this pull request?

This PR fixes a Scala 2.10 compilation failure introduced in PR #13127.
## How was this patch tested?

Jenkins build.

### CODE REVIEW

**Comment by clockfly** [comment]
+1

**Comment by liancheng** [comment]
Merging to master and branch-2.0.
