### PR TITLE
[SPARK-43185][BUILD] Inline `hadoop-client` related properties in `pom.xml`

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
SPARK-36835 introduced `hadoop-client-api.artifact`, `adoop-client-runtime.artifact` and `hadoop-client-minicluster.artifact` to be compatible with the dependency definitions of Hadoop 2 and Hadoop 3. 

After [SPARK-42452](https://issues.apache.org/jira/browse/SPARK-42452), Spark no longer supports Hadoop 2, so this pr inline these properties to simplify the dependency definition.

### Why are the changes needed?
No longer requires compatibility with Hadoop 2

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
cc @sunchao

**Comment by pan3793** [comment]
Does it mean we drop support for building against vanilla Hadoop3 client?

https://github.com/apache/spark/blob/09a43531d30346bb7c8d213822513dc35c70f82e/sql/hive/src/main/scala/org/apache/spark/sql/hive/client/IsolatedClientLoader.scala#L118-L124

**Comment by LuciferYang** [comment]
> ~Does it mean we drop support for building against vanilla Hadoop3 client?~
> 
> https://github.com/apache/spark/blob/09a43531d30346bb7c8d213822513dc35c70f82e/sql/hive/src/main/scala/org/apache/spark/sql/hive/client/IsolatedClientLoader.scala#L118-L124
> 
> Update: leave it, #33160 didn't get in, Spark does not support for building against vanilla Hadoop3 client

friendly ping @sunchao

**Review by sunchao — APPROVED** [review]
LGTM.

Note this also makes it impossible for users to pick a Hadoop version without shaded client support, like Hadoop 3.1.x. Previous they can do:
```
./mvn package -Dhadoop.version=3.1.2 -Dhadoop-client-api.artifact=hadoop-client ...
```

cc @xkrogen too (I vaguely remember you did something similar).

**Comment by sunchao** [comment]
Some related JIRA: https://issues.apache.org/jira/browse/SPARK-37994

**Comment by pan3793** [comment]
@sunchao so the current supported Hadoop version is 3.2.2+ and 3.3.1+? there is some code for Hadoop 3.0 and 3.1, should we remove it then?

**Comment by sunchao** [comment]
yea, the shaded Hadoop client only work for Hadoop 3.2.2+ and 3.3.1+. I'm not sure if there're people that still use Hadoop 3.0/3.1 with Spark though.

I'm not aware of any code in Spark that specifically depend on Hadoop 3.0/3.1. Could you point to them for me?

**Comment by pan3793** [comment]
> I'm not aware of any code in Spark that specifically depend on Hadoop 3.0/3.1. Could you point to them for me?

@sunchao I find two examples

- SPARK-13704 added a workaround for [YARN-9332](https://issues.apache.org/jira/browse/YARN-9332) (fixed in Hadoop 3.2.1/3.3.0)
- SPARK-32256 added a workaround for [HADOOP-14067](https://issues.apache.org/jira/browse/HADOOP-14067) (fixed in Hadoop 3.1.0)

**Comment by xkrogen** [comment]
No strong opinion on this, but we should make it clear that this PR is explicitly dropping support for Hadoop 3.0/3.1 and earlier versions of 3.2

cc @mridulm

**Comment by LuciferYang** [comment]
@xkrogen @sunchao @pan3793 I would like to clarify, actually, no longer using Hadoop 3.0/3.1 support for compilation is not the original intention of this PR.

So if there is an way to build and test Hadoop 3.0/3.1 successfully before this pr, but it loses after this pr,  I think we should stop this work because Apache Spark has not previously stated on any occasion that it no longer supports Hadoop 3.0/3.1.


@xkrogen @sunchao @pan3793 Can you give a command that can be used for build & test with Hadoop 3.0/3.1? I want to manually check it, thanks ~

**Comment by sunchao** [comment]
> So if there is an way to build and test Hadoop 3.0/3.1 successfully before this pr, but it loses after this pr, I think we should stop this work because Apache Spark has not previously stated on any occasion that it no longer supports Hadoop 3.0/3.1, right ?

Yes, I think that's probably a sensible thing to do. 

> @xkrogen @sunchao @pan3793 Can you give a command that can be used for build & test with Hadoop 3.0/3.1? I want to manually check it, thanks ~

You can check this JIRA for the command to build: https://issues.apache.org/jira/browse/SPARK-37994

**Comment by LuciferYang** [comment]
> > So if there is an way to build and test Hadoop 3.0/3.1 successfully before this pr, but it loses after this pr, I think we should stop this work because Apache Spark has not previously stated on any occasion that it no longer supports Hadoop 3.0/3.1, right ?
> 
> Yes, I think that's probably a sensible thing to do.
> 
> > @xkrogen @sunchao @pan3793 Can you give a command that can be used for build & test with Hadoop 3.0/3.1? I want to manually check it, thanks ~
> 
> You can check this JIRA for the command to build: https://issues.apache.org/jira/browse/SPARK-37994

I encountered the following error while compiling `hadoop-cloud` module during build with hadoop 3.1.x:

```
[ERROR] [Error] /${spark-source-dir}/hadoop-cloud/src/hadoop-3/main/scala/org/apache/spark/internal/io/cloud/AbortableStreamBasedCheckpointFileManager.scala:34: value hasPathCapability is not a member of org.apache.hadoop.fs.FileContext
[ERROR] [Error] /${spark-source-dir}/hadoop-cloud/src/hadoop-3/main/scala/org/apache/spark/internal/io/cloud/AbortableStreamBasedCheckpointFileManager.scala:34: not found: value CommonPathCapabilities
[ERROR] [Error] /${spark-source-dir}/hadoop-cloud/src/hadoop-3/main/scala/org/apache/spark/internal/io/cloud/AbortableStreamBasedCheckpointFileManager.scala:52: value abort is not a member of org.apache.hadoop.fs.FSDataOutputStream
[ERROR] [Error] /${spark-source-dir}/hadoop-cloud/src/hadoop-3/main/scala/org/apache/spark/internal/io/cloud/AbortableStreamBasedCheckpointFileManager.scala:66: value abort is not a member of org.apache.hadoop.fs.FSDataOutputStream
```

Due to the fixed version of HADOOP-15691 being `
3.3.0, 3.2.2, 3.2.3` and the fixed version of HADOOP-16906 being `3.3.1`, so it is definitely not possible to build hadoop-cloud` module using Hadoop 3.1. x. I would like to remove this module to continue my experiment

**Comment by LuciferYang** [comment]
convert to draft to avoid accidental merging

**Comment by sunchao** [comment]
Interesting, thanks for the detailed analysis @LuciferYang !

> Use hadoop 3.2.x can't build hadoop-cloud module too

This is Hadoop 3.2.2 ? I remember at some point we started to enable `hadoop-cloud` in Spark release, so I wonder why this didn't cause any error back in the time ..

**Comment by LuciferYang** [comment]
> Interesting, thanks for the detailed analysis @LuciferYang !
> 
> > Use hadoop 3.2.x can't build hadoop-cloud module too
> 
> This is Hadoop 3.2.2 ? I remember at some point we started to enable `hadoop-cloud` in Spark release, so I wonder why this didn't cause any error back in the time ..

I test hadoop 3.2.4. `AbortableStreamBasedCheckpointFileManager` was introduced in SPARK-40039, and it uses APIs that are only available in Hadoop 3.3.1+([HADOOP-16906](https://issues.apache.org/jira/browse/HADOOP-16906)  `FSDataOutputStream#abort()`)

**Review by srowen — APPROVED** [review]

**Review by pan3793 — APPROVED** [review]
I think it's OK to get in, because

1. Spark does not claim to support building against vanilla Hadoop 3 client officially, and it does not work before this change, so this PR breaks nothing
2. before and after this PR, Spark supports building against Hadoop 3.3.1+ shaded client.
3. before and after this PR, Spark can NOT build against Hadoop 3.2.x shaded client because of SPARK-40039, it's another issue if we want to restore the support for Hadoop 3.2.x shaded client

**Comment by pan3793** [comment]
> No strong opinion on this, but we should make it clear that this PR is explicitly dropping support for Hadoop 3.0/3.1 and earlier versions of 3.2

@srowen I'm also +1 that we should document clearly the Hadoop client version support strategy

**Review by sunchao — APPROVED** [review]
I'm OK with the PR too given that Spark already doesn't support most of other Hadoop versions before 3.3.1.

**Comment by srowen** [comment]
Merged to master

**Review by dongjoon-hyun — COMMENTED** [review]
+1, LGTM.
