### PR TITLE
[SPARK-56089][SQL][FOLLOW-UP] Use ctx.freshName for codegen variables in Asinh/Acosh

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

Use `ctx.freshName()` for local variables in `Asinh` and `Acosh` codegen, and add test coverage.

### Why are the changes needed?

1. The fdlibm codegen introduced in https://github.com/apache/spark/pull/54912 uses hardcoded variable names (`ax`, `w`, `t`). When whole-stage codegen inlines multiple `Asinh`/`Acosh` expressions into the same method with non-nullable children, `nullSafeCodeGen` emits code without an `if`-block wrapper, so the hardcoded names cause `CompileException: Redefinition of local variable "ax"`.
2. Large negative values like -1E100 and -1E50 exercise the `log(|x|)+log(2)` branch with sign propagation via `copySign`, which was not covered.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

New test: `Add(Asinh(Literal(1.0)), Asinh(Literal(2.0)))` reproduces the codegen variable collision — non-nullable `Literal` children cause `nullSafeCodeGen` to emit code without scope-isolating `if` blocks, triggering `Redefinition of local variable "ax"` without the fix. Plus two new assertions for large negative asinh values.

### Was this patch authored or co-authored using generative AI tooling?

Yes

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @xiaoxuandev @peter-toth

**Review by peter-toth — APPROVED** [review]
Good catch.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
cc @sarutak and @mgaido91 , too.

**Review by xiaoxuandev — APPROVED** [review]

File: sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/mathExpressions.scala [hunk 1]
```diff
@@ -446,8 +447,8 @@ case class Acosh(child: Expression)
          |} else if ($c > 2.0) {
          |  ${ev.value} = $sm.log(2.0 * $c - 1.0 / ($c + java.lang.Math.sqrt($c * $c - 1.0)));
          |} else {
-         |  double t = $c - 1.0;
-         |  ${ev.value} = $sm.log1p(t + java.lang.Math.sqrt(2.0 * t + t * t));
+         |  double $t = $c - 1.0;
```
Comment (mgaido91) [inline sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/mathExpressions.scala:450]: nit: is this also needed? It is in the scope of the else statement, so no conflict should be possible here, unless there is a `t` defined in a global scope. However, it is probably better to just go with it to stay on the safe side.

**Review by mgaido91 — APPROVED** [review]
LGTM. Sorry, should have noticed in the previous review. Thank @cloud-fan for fixing this.

**Review by sarutak — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

File: sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/mathExpressions.scala (hunk 1 above)
Comment (cloud-fan) [reply sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/mathExpressions.scala:450]: oh this case is fine, but changing it is more future proof, in case we put child coddegen in the else branch and local variable `t` may shadow outer variables.

**Comment by cloud-fan** [comment]
thanks for the review, merging to master!
