### PR TITLE
[SPARK-29292][SPARK-30010][CORE] Let core compile for Scala 2.13

### PR DESCRIPTION
**Pull request by srowen**
### What changes were proposed in this pull request?

The purpose of this PR is to partly resolve SPARK-29292, and fully resolve SPARK-30010, which should allow Spark to compile vs Scala 2.13 in Spark Core and up through GraphX (not SQL, Streaming, etc).

Note that we are not trying to determine here whether this makes Spark work on 2.13 yet, just compile, as a prerequisite for assessing test outcomes. However, of course, we need to ensure that the change does not break 2.12.

The changes are, in the main, adding .toSeq and .toMap calls where mutable collections / maps are returned as Seq / Map, which are immutable by default in Scala 2.13. The theory is that it should be a no-op for Scala 2.12 (these return themselves), and required for 2.13.

There are a few non-trivial changes highlighted below.
In particular, to get Core to compile, we need to resolve SPARK-30010 which removes a deprecated SparkConf method

### Why are the changes needed?

Eventually, we need to support a Scala 2.13 build, perhaps in Spark 3.1. 

### Does this PR introduce _any_ user-facing change?

Yes, removal of the deprecated SparkConf.setAll overload, which isn't legal in Scala 2.13 anymore.

### How was this patch tested?

Existing tests. (2.13 was not _tested_; this is about getting it to compile without breaking 2.12)

### CODE REVIEW

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by srowen** [comment]
@shaneknapp I think we have the same corrupted .m2 repository issue again. Do I just keep retesting until it doesn't hit the worker?

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by dongjoon-hyun** [comment]
Retest this please.

File: core/src/main/scala/org/apache/spark/SparkConf.scala [hunk 1]
```diff
@@ -173,15 +173,6 @@ class SparkConf(loadDefaults: Boolean) extends Cloneable with Logging with Seria
...
 
-  /**
-   * Set multiple parameters together
-   */
-  @deprecated("Use setAll(Iterable) instead", "3.0.0")
-  def setAll(settings: Traversable[(String, String)]): SparkConf = {
-    settings.foreach { case (k, v) => set(k, v) }
-    this
-  }
-
```
Comment (dongjoon-hyun) [inline core/src/main/scala/org/apache/spark/SparkConf.scala:184]: I'm okay with this, but this might be not aligned with the latest community decision at `Cost of Breaking an API`.
cc @gatorsmile

**Comment by dongjoon-hyun** [comment]
Thank you so much, @srowen !

File: core/src/main/scala/org/apache/spark/deploy/FaultToleranceTest.scala [hunk 2]
```diff
@@ -279,7 +279,7 @@ private object FaultToleranceTest extends App with Logging {
     var liveWorkerIPs: Seq[String] = List()
 
     def stateValid(): Boolean = {
-      (workers.map(_.ip) -- liveWorkerIPs).isEmpty &&
+      workers.map(_.ip).forall(liveWorkerIPs.contains) &&
```
Comment (attilapiros) [inline core/src/main/scala/org/apache/spark/deploy/FaultToleranceTest.scala:282]: Nit: What about using `diff` here?
As I see `diff` is not deprecated: https://www.scala-lang.org/api/current/scala/collection/Seq.html#diff[B%3E:A](that:scala.collection.Seq[B]):C

 ```suggestion
      workers.map(_.ip).diff(liveWorkerIPs).isEmpty &&
```

File: core/src/main/scala/org/apache/spark/SparkConf.scala (hunk 1 above)
Comment (srowen) [reply core/src/main/scala/org/apache/spark/SparkConf.scala:184]: Yeah, tough call here. The method call is still source compatible in virtually all cases. It'll be binary compatible in most cases too because callers will bind to the more specific Iterable overload anyway if passing almost any normal collection. This is why I deprecated this method in 3.0.0. Still it's a tough call removing it, but I do not see any way around it given the changes in Scala 2.13 (well we can fork source trees, but that seems like a huge pain).

File: core/src/main/scala/org/apache/spark/rdd/ParallelCollectionRDD.scala [hunk 3]
```diff
@@ -135,10 +135,10 @@ private object ParallelCollectionRDD {
             new Range.Inclusive(r.start + start * r.step, r.end, r.step)
           }
           else {
-            new Range(r.start + start * r.step, r.start + end * r.step, r.step)
+            new Range.Inclusive(r.start + start * r.step, r.start + end * r.step - 1, r.step)
```
Comment (attilapiros) [inline core/src/main/scala/org/apache/spark/rdd/ParallelCollectionRDD.scala:138]: What about `Range.Exclusive`?

```suggestion
            new Range.Exclusive(r.start + start * r.step, r.start + end * r.step, r.step)
```

Comment (srowen) [reply core/src/main/scala/org/apache/spark/rdd/ParallelCollectionRDD.scala:138]: Range.Exclusive doesn't exist in 2.12, and Range() (exclusive in 2.12) doesn't exist in 2.13. :( I tried that initially. Because these are integers, I think we can get away with an Inclusive range that ends at end - 1 instead.

File: core/src/main/scala/org/apache/spark/deploy/FaultToleranceTest.scala (hunk 2 above)
Comment (srowen) [reply core/src/main/scala/org/apache/spark/deploy/FaultToleranceTest.scala:282]: diff would work too, I think. It has multiset semantics, and I thought it was not necessary here. I went for what I thought was simpler, but I am not 100% sure.

File: core/src/main/scala/org/apache/spark/rdd/ParallelCollectionRDD.scala (hunk 3 above)
Comment (attilapiros) [reply core/src/main/scala/org/apache/spark/rdd/ParallelCollectionRDD.scala:138]: I see. In this case this is totally fine.

Comment (attilapiros) [reply core/src/main/scala/org/apache/spark/rdd/ParallelCollectionRDD.scala:138]: One more question: what about using `until` and `by`?

Comment (srowen) [reply core/src/main/scala/org/apache/spark/rdd/ParallelCollectionRDD.scala:138]: It's probably equivalent, yeah. I was shooting for minimal change here, but there may be several solutions.

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by srowen** [comment]
Weird. I've seen the same test failure twice here, but it does not fail the normal 2.12 build for me locally. The order of test suite output seems ... intermingled? Kind of confused, I didn't think we had parallel execution enabled. It's a timeout error too. I'll try once again...

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by srowen** [comment]
Jenkins retest this please

File: core/src/main/scala/org/apache/spark/rdd/ParallelCollectionRDD.scala [hunk 4]
```diff
@@ -133,12 +133,11 @@ private object ParallelCollectionRDD {
           // If the range is inclusive, use inclusive range for the last slice
           if (r.isInclusive && index == numSlices - 1) {
             new Range.Inclusive(r.start + start * r.step, r.end, r.step)
-          }
-          else {
-            new Range(r.start + start * r.step, r.start + end * r.step, r.step)
+          } else {
+            new Range.Inclusive(r.start + start * r.step, r.start + (end - 1) * r.step, r.step)
```
Comment (srowen) [inline core/src/main/scala/org/apache/spark/rdd/ParallelCollectionRDD.scala:137]: For previous reviewers: I fixed a bug from my initial change here. The non-inclusive end is not 1 less than the exclusive end, but one less `r.step`

File: core/src/test/scala/org/apache/spark/HeartbeatReceiverSuite.scala [hunk 5]
```diff
@@ -287,6 +287,8 @@ private class FakeSchedulerBackend(
     resourceProfileManager: ResourceProfileManager)
   extends CoarseGrainedSchedulerBackend(scheduler, rpcEnv) {
 
+  def this() = this(null, null, null, null)
```
Comment (srowen) [inline core/src/test/scala/org/apache/spark/HeartbeatReceiverSuite.scala:290]: I still have no idea how this wasn't required in Scala 2.12, as it's used with a no-arg constructor but none existed ?!

File: core/src/test/scala/org/apache/spark/rdd/RDDSuite.scala [hunk 6]
```diff
@@ -656,7 +656,7 @@ class RDDSuite extends SparkFunSuite with SharedSparkContext with Eventually {
   }
 
   test("top with predefined ordering") {
-    val nums = Array.range(1, 100000)
+    val nums = Seq.range(1, 100000)
```
Comment (srowen) [inline core/src/test/scala/org/apache/spark/rdd/RDDSuite.scala:659]: Side comment: generally speaking Seq types have less weird generic type problems than Arrays. This is a good example

**Comment by dongjoon-hyun** [comment]
Great, @srowen !

**Comment by dongjoon-hyun** [comment]
Could you fix the following four instance together, @srowen ?
```
[ERROR] [Error] /Users/dongjoon/PRS/SPARK-PR-28971/core/src/main/scala/org/apache/spark/rdd/UnionRDD.scala:23: object parallel is not a member of package collection
[ERROR] [Error] /Users/dongjoon/PRS/SPARK-PR-28971/core/src/main/scala/org/apache/spark/rdd/UnionRDD.scala:24: object parallel is not a member of package collection
[ERROR] [Error] /Users/dongjoon/PRS/SPARK-PR-28971/core/src/main/scala/org/apache/spark/rdd/UnionRDD.scala:64: not found: type ForkJoinTaskSupport
[ERROR] [Error] /Users/dongjoon/PRS/SPARK-PR-28971/core/src/main/scala/org/apache/spark/rdd/UnionRDD.scala:79: not found: type ParVector
```

**Comment by srowen** [comment]
Oh where do you see that? I can't find it in the test logs. That should be fine on 2.12 but is also working on my local 2.13 compilation.

**Comment by dongjoon-hyun** [comment]
I built with 2.13.3 like the following to verify this PR.
```
$ dev/change-scala-version.sh 2.13

$ ...
-    <scala.version>2.12.10</scala.version>
-    <scala.binary.version>2.12</scala.binary.version>
+    <scala.version>2.13.3</scala.version>
+    <scala.binary.version>2.13</scala.binary.version>

$ build/mvn package -DskipTests -pl core --am
```

**Comment by srowen** [comment]
Oh, you have to build with `-Pscala-2.13` too

**Comment by dongjoon-hyun** [comment]
Oh. Got it. Thanks!

**Comment by srowen** [comment]
Oh, I did miss one necessary change. The room pom has to update to scala 2.13.3, yes. Let me get that part of the change in here.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Everything works. Thank you so much, @srowen .
Merged to master for Apache Spark 3.1.0.

**Comment by srowen** [comment]
Oh OK I wanted to make sure everyone was OK with the approach, but I think so as it's been the plan for a long time AFAICT. I will start making other similar PRs (this one does not resolved SPARK-29292 by itself)

**Comment by dongjoon-hyun** [comment]
Sorry for the rush. If needed, we are able to switch our approaches during Apache Spark 3.1.0 timeline. I believe this healthy `core` module will unlock Scala-2.13 progress as a baseline toward other modules and Scala 2.13 testing stage.

File: core/src/main/scala/org/apache/spark/SparkConf.scala [hunk 7]
```diff
@@ -173,15 +173,6 @@ class SparkConf(loadDefaults: Boolean) extends Cloneable with Logging with Seria
     this
   }
 
-  /**
-   * Set multiple parameters together
-   */
-  @deprecated("Use setAll(Iterable) instead", "3.0.0")
-  def setAll(settings: Traversable[(String, String)]): SparkConf = {
```
Comment (HyukjinKwon) [inline core/src/main/scala/org/apache/spark/SparkConf.scala:180]: @srowen, BTW, it might be best to file a JIRA as a reminder to keep this API back if we can't make Scala 2.13 in Spark 3.1.

I believe it is legitimate and inevitable to remove this because of Scala 2.13 but it might be problematic if we can't make it in Spark 3.1, and have a release out only with Scala 2.12.

Comment (srowen) [reply core/src/main/scala/org/apache/spark/SparkConf.scala:180]: Yeah if the whole thing doesn't make it for 3.1, I'd leave this method in 3.1.
