### PR TITLE
[SPARK-37412][PYTHON][ML] Inline typehints for pyspark.ml.stat

### PR DESCRIPTION
**Pull request by zero323**
### What changes were proposed in this pull request?

This PR migrates type `pyspark.ml.stat` annotations from stub file to inline type hints.

### Why are the changes needed?

Part of ongoing migration of type hints.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by zero323** [comment]
Merged into master.

Thanks @HyukjinKwon!

**Comment by HyukjinKwon** [comment]
Uhoh, I think there was a logical conflict with another commit:

```
starting mypy annotations test...
annotations failed mypy checks:
python/pyspark/ml/stat.py:478: error: Item "None" of "Optional[Any]" has no attribute "summary"  [union-attr]
Found 1 error in 1 file (checked 3[24](https://github.com/apache/spark/runs/5103080884?check_suite_focus=true#step:15:24) source files)
1
```

I reverted this for now. @zero323 mind creating a PR again? 🙏

**Comment by zero323** [comment]
Thanks @HyukjinKwon for handling this and sorry for the mess.
