### PR TITLE
[SPARK-16939][SQL] Fix build error by using `Tuple1` explicitly in StringFunctionsSuite

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

This PR aims to fix a build error on branch 1.6 at https://github.com/apache/spark/commit/8d8725208771a8815a60160a5a30dc6ea87a7e6a, but I think we had better have this consistently in master branch, too. It's because there exist other ongoing PR (https://github.com/apache/spark/pull/14525) about this.

https://amplab.cs.berkeley.edu/jenkins/job/spark-branch-1.6-compile-maven-with-yarn-2.3/286/console

``` scala
[error] /home/jenkins/workspace/spark-branch-1.6-compile-maven-with-yarn-2.3/sql/core/src/test/scala/org/apache/spark/sql/StringFunctionsSuite.scala:82: value toDF is not a member of Seq[String]
[error]     val df = Seq("aaaac").toDF("s")
[error]                           ^
```
## How was this patch tested?

After passing Jenkins, run compilation test on branch 1.6.

```
build/mvn -DskipTests -Pyarn -Phadoop-2.3 -Pkinesis-asl -Phive -Phive-thriftserver install
```

### CODE REVIEW

**Comment by srowen** [comment]
Ah, shoot, that would be my fault. I am not sure why it would only fail for 1.6? let me also look into it. Thanks for the catch.

**Comment by dongjoon-hyun** [comment]
Oh, thank you, @srowen !

**Comment by dongjoon-hyun** [comment]
Until today, I also guessed that master branch does not handle this.

File: sql/core/src/test/scala/org/apache/spark/sql/StringFunctionsSuite.scala [hunk 1]
```diff
@@ -95,7 +95,7 @@ class StringFunctionsSuite extends QueryTest with SharedSQLContext {
   }
 
   test("non-matching optional group") {
-    val df = Seq("aaaac").toDF("s")
+    val df = Seq(Tuple1("aaaac")).toDF("s")
```
Comment (srowen) [inline sql/core/src/test/scala/org/apache/spark/sql/StringFunctionsSuite.scala]: OK, I guess that Scala 2.11 has an implicit conversion that Scala 2.10 does not that would make this conversion automatically, hence the PR builder succeeded. We could also just add a dummy column in the example, but I suppose this is the best way to ensure that the fix works in 1.6, and also makes the test a little more robust. LGTM, thanks.

Comment (dongjoon-hyun) [inline sql/core/src/test/scala/org/apache/spark/sql/StringFunctionsSuite.scala]: Thank you, @srowen .

**Comment by srowen** [comment]
Merged to master/2.0/1.6

**Comment by dongjoon-hyun** [comment]
Thank you for merging, @srowen !
