### PR TITLE
[SPARK-31655][BUILD] Upgrade snappy-java to 1.1.7.5

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?

snappy-java have release v1.1.7.5, upgrade to latest version.

Fixed in v1.1.7.4
- Caching internal buffers for SnappyFramed streams #234
- Fixed the native lib for ppc64le to work with glibc 2.17 (Previously it depended on 2.22)

Fixed in v1.1.7.5
- Fixes java.lang.NoClassDefFoundError: org/xerial/snappy/pool/DefaultPoolFactory in 1.1.7.4

https://github.com/xerial/snappy-java/compare/1.1.7.3...1.1.7.5

v 1.1.7.5 release note:
https://github.com/xerial/snappy-java/commit/edc4ec28bdb15a32b6c41ca9e8b195e635bec3a3
### Why are the changes needed?
Fix bug 

### Does this PR introduce _any_ user-facing change?
No 

### How was this patch tested?
No need

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
cc @HeartSaVioR

**Review by maropu — APPROVED** [review]

**Comment by maropu** [comment]
retest this please

**Comment by HeartSaVioR** [comment]
retest this, please

**Review by HeartSaVioR — APPROVED** [review]
LGTM.

**Comment by yaooqinn** [comment]
> **[Test build #122389 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/122389/testReport)** for PR 28472 at commit [`ff742f5`](https://github.com/apache/spark/commit/ff742f587887eea1e314e9de8c53f776af07f9ad).
> 
> * This patch **fails Spark unit tests**.
> * This patch merges cleanly.
> * This patch adds no public classes.

cc @gaborgsomogyi, KafkaDelegationTokenSuite seems still flaky setting up Kerberos

**Comment by AngersZhuuuu** [comment]
retest this please

**Review by HyukjinKwon — APPROVED** [review]

**Comment by gaborgsomogyi** [comment]
> > **[Test build #122389 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/122389/testReport)** for PR 28472 at commit [`ff742f5`](https://github.com/apache/spark/commit/ff742f587887eea1e314e9de8c53f776af07f9ad).
> > 
> > * This patch **fails Spark unit tests**.
> > * This patch merges cleanly.
> > * This patch adds no public classes.
> 
> cc @gaborgsomogyi, KafkaDelegationTokenSuite seems still flaky for setting up Kerberos

I'll check whether it's possible to move setup into the test itself...

**Comment by HeartSaVioR** [comment]
I've taken a look at the failure before - that's a weird situation, as it succeeded to create `client/localhost@EXAMPLE.COM` principal and keytab, but failed to authenticate.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master for Apache Spark 3.1.0.
Thank you all.

**Comment by gaborgsomogyi** [comment]
Guys, I've taken a look at the possibilities how to solve the mentioned `KafkaDelegationTokenSuite` issue and found a new approach. Going to file a jira + PR probably next week...

**Comment by nblxa** [comment]
Hello. What is necessary to have this fix packported to 2.4.x?

**Comment by dongjoon-hyun** [comment]
Hi, @nblxa . Do you hit any snappy issue in Apache Spark 2.4.5?

**Comment by nblxa** [comment]
Hi @dongjoon-hyun I’m hitting the glibc-2.22 issue with 2.4.3 on RHEL7 on Power due to the snappy-java dependency. I guess the same version of snappy-java is used in 2.4.5?

**Comment by HeartSaVioR** [comment]
It may be a regression for such architecture (RHEL7 & IBM power) starting from Spark 2.4.0 where snappy-java 1.1.7.1 is being introduced. What I heard is that snappy-java 1.1.2.6 (Spark 2.3.x) doesn't have a reference of glibc-2.22.

I'm not sure the architecture is in official support range, hence can't say whether it's a regression or not. It'd be nice to have this in Spark 3.0.0 at least even it doesn't belong to the official support.

**Comment by maropu** [comment]
Hi, @nblxa  Thanks for the report. [The bug](https://github.com/xerial/snappy-java/issues/220) should have been fixed in `snappy-java v1.1.7.4`, but `branch-2.4` still uses `1.1.7.3`. https://github.com/apache/spark/blob/branch-2.4/pom.xml#L164 .
I think it might be worth bumping up the version. cc: @dongjoon-hyun @holdenk

**Comment by AngersZhuuuu** [comment]
> Hi, @nblxa Thanks for the report. [The bug](https://github.com/xerial/snappy-java/issues/220) should have been fixed in `snappy-java v1.1.7.4`, but `branch-2.4` still uses `1.1.7.3`. https://github.com/apache/spark/blob/branch-2.4/pom.xml#L164 .
> I think it might be worth bumping up the version. cc: @dongjoon-hyun @holdenk

Raise a pr later.

**Comment by dongjoon-hyun** [comment]
Got it. Thanks.
