### PR TITLE
[SPARK-25408] Move to mode ideomatic Java8

### PR DESCRIPTION
**Pull request by Fokko**
While working on another PR, I noticed that there is quite some legacy Java in there that can be beautified. For example the use og features from Java8, such as:
- Collection libraries
- Try-with-resource blocks

No code has been changed

What are your thoughts on this?

This makes code easier to read, and using try-with-resource makes is less likely to forget to close something.

## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

File: common/kvstore/src/test/java/org/apache/spark/util/kvstore/DBIteratorSuite.java [hunk 1]
```diff
@@ -383,7 +383,7 @@ public void testRefWithIntNaturalKey() throws Exception {
     LevelDBSuite.IntKeyType i = new LevelDBSuite.IntKeyType();
     i.key = 1;
     i.id = "1";
-    i.values = Arrays.asList("1");
+    i.values = Collections.singletonList("1");
```
Comment (TomaszGaweda) [inline common/kvstore/src/test/java/org/apache/spark/util/kvstore/DBIteratorSuite.java]: If you are already changing this, I would  also suggest to add static imports to shorten the code

**Comment by TomaszGaweda** [comment]
I like this idea :) +1 as it's only refactor, without logic change

File: common/kvstore/src/test/java/org/apache/spark/util/kvstore/DBIteratorSuite.java (hunk 1 above)
Comment (srowen) [reply common/kvstore/src/test/java/org/apache/spark/util/kvstore/DBIteratorSuite.java]: I don't think this sort of thing is worth changing. I know, IntelliJ suggests it. Unless the mutability is an issue, I'd leave it as a shorter idiom. I wouldn't use static imports here personally.

there's also a very small cost of changes in that they create potential merge conflicts for other changes later, so I tend to have a very low but finite minimum bar for value of code scrubbing like this.

File: common/network-common/src/test/java/org/apache/spark/network/ChunkFetchIntegrationSuite.java [hunk 2]
```diff
@@ -143,61 +143,62 @@ public void releaseBuffers() {
...
 
-    ChunkReceivedCallback callback = new ChunkReceivedCallback() {
-      @Override
-      public void onSuccess(int chunkIndex, ManagedBuffer buffer) {
-        buffer.retain();
-        res.successChunks.add(chunkIndex);
-        res.buffers.add(buffer);
-        sem.release();
-      }
+    try(TransportClient client = clientFactory.createClient(TestUtils.getLocalHost(), server.getPort())) {
```
Comment (srowen) [inline common/network-common/src/test/java/org/apache/spark/network/ChunkFetchIntegrationSuite.java]: Nit: space after try

File: common/network-shuffle/src/test/java/org/apache/spark/network/shuffle/ExternalShuffleBlockResolverSuite.java [hunk 3]
```diff
@@ -98,19 +98,19 @@ public void testSortShuffleBlocks() throws IOException {
...
-    assertEquals(sortBlock0, block0);
-
-    InputStream block1Stream =
-      resolver.getBlockData("app0", "exec0", 0, 0, 1).createInputStream();
-    String block1 = CharStreams.toString(
-        new InputStreamReader(block1Stream, StandardCharsets.UTF_8));
-    block1Stream.close();
-    assertEquals(sortBlock1, block1);
+    try(InputStream block0Stream =
+      resolver.getBlockData("app0", "exec0", 0, 0, 0).createInputStream()) {
```
Comment (srowen) [inline common/network-shuffle/src/test/java/org/apache/spark/network/shuffle/ExternalShuffleBlockResolverSuite.java]: Same comment about space above; I'd also indent the continuation 4 spaces for clarity

File: common/network-shuffle/src/test/java/org/apache/spark/network/shuffle/ExternalShuffleIntegrationSuite.java [hunk 4]
```diff
@@ -133,37 +133,37 @@ private FetchResult fetchBlocks(
...
-          }
-        }
-      }, null);
-
-    if (!requestsRemaining.tryAcquire(blockIds.length, 5, TimeUnit.SECONDS)) {
-      fail("Timeout getting response from the server");
+    try(ExternalShuffleClient client = new ExternalShuffleClient(clientConf, null, false, 5000)) {
+      client.init(APP_ID);
+      client.fetchBlocks(TestUtils.getLocalHost(), port, execId, blockIds,
+              new BlockFetchingListener() {
```
Comment (srowen) [inline common/network-shuffle/src/test/java/org/apache/spark/network/shuffle/ExternalShuffleIntegrationSuite.java]: Indent is now too deep here. I have the same general kind of doubt here.. it's touching a lot of lines for little actual gain. Still, I'd like to be able to improve code a bit here and there. If this is only going to master and Spark 3, the back-port issue lessens, because it's more unlikely to backport from 3.x to 2.x.

File: core/src/test/java/org/apache/spark/launcher/SparkLauncherSuite.java [hunk 5]
```diff
@@ -18,12 +18,7 @@
 package org.apache.spark.launcher;
 
 import java.time.Duration;
-import java.util.Arrays;
-import java.util.ArrayList;
-import java.util.HashMap;
-import java.util.List;
-import java.util.Map;
-import java.util.Properties;
+import java.util.*;
```
Comment (srowen) [inline core/src/test/java/org/apache/spark/launcher/SparkLauncherSuite.java]: Don't collapse these

File: launcher/src/main/java/org/apache/spark/launcher/AbstractAppHandle.java [hunk 6]
```diff
@@ -72,11 +74,7 @@ public void stop() {
   @Override
   public synchronized void disconnect() {
     if (connection != null && connection.isOpen()) {
-      try {
-        connection.close();
-      } catch (IOException ioe) {
-        // no-op.
-      }
+      IOUtils.closeQuietly(connection);
```
Comment (srowen) [inline launcher/src/main/java/org/apache/spark/launcher/AbstractAppHandle.java]: I wouldn't bother with this; we don't really do it consistently, it's not a JDK standard class, and it doesn't really save much, while adding to the dependency on commons/io

**Review by srowen — CHANGES_REQUESTED** [review]

File: launcher/src/main/java/org/apache/spark/launcher/AbstractAppHandle.java (hunk 6 above)
Comment (vanzin) [reply launcher/src/main/java/org/apache/spark/launcher/AbstractAppHandle.java]: This library should not have any non-JRE dependencies.

File: common/kvstore/src/test/java/org/apache/spark/util/kvstore/DBIteratorSuite.java (hunk 1 above)
Comment (Fokko) [reply common/kvstore/src/test/java/org/apache/spark/util/kvstore/DBIteratorSuite.java]: I agree, I don't really care about moving to `Collections`.

File: launcher/src/main/java/org/apache/spark/launcher/AbstractAppHandle.java (hunk 6 above)
Comment (Fokko) [reply launcher/src/main/java/org/apache/spark/launcher/AbstractAppHandle.java]: I wan't aware of this requirement, reverted the change.

File: common/network-shuffle/src/test/java/org/apache/spark/network/shuffle/ExternalShuffleIntegrationSuite.java [hunk 7]
```diff
@@ -133,37 +133,37 @@ private FetchResult fetchBlocks(
...
-          }
-        }
-      }, null);
-
-    if (!requestsRemaining.tryAcquire(blockIds.length, 5, TimeUnit.SECONDS)) {
-      fail("Timeout getting response from the server");
+    try (ExternalShuffleClient client = new ExternalShuffleClient(clientConf, null, false, 5000)) {
+      client.init(APP_ID);
+      client.fetchBlocks(TestUtils.getLocalHost(), port, execId, blockIds,
+              new BlockFetchingListener() {
```
Comment (HyukjinKwon) [inline common/network-shuffle/src/test/java/org/apache/spark/network/shuffle/ExternalShuffleIntegrationSuite.java]: Shell we stick to 2spaced indentation?

File: common/network-shuffle/src/test/java/org/apache/spark/network/shuffle/ExternalShuffleSecuritySuite.java [hunk 8]
```diff
@@ -96,14 +96,14 @@ private void validate(String appId, String secretKey, boolean encrypt)
...
-    client.registerWithShuffleServer(TestUtils.getLocalHost(), server.getPort(), "exec0",
-      new ExecutorShuffleInfo(new String[0], 0,
-        "org.apache.spark.shuffle.sort.SortShuffleManager"));
-    client.close();
+    try (ExternalShuffleClient client =
+        new ExternalShuffleClient(testConf, new TestSecretKeyHolder(appId, secretKey), true, 5000)) {
+      client.init(appId);
+      // Registration either succeeds or throws an exception.
+      client.registerWithShuffleServer(TestUtils.getLocalHost(), server.getPort(), "exec0",
+              new ExecutorShuffleInfo(new String[0], 0,
```
Comment (HyukjinKwon) [inline common/network-shuffle/src/test/java/org/apache/spark/network/shuffle/ExternalShuffleSecuritySuite.java]: ditto for indentation

File: core/src/test/java/org/apache/spark/JavaJdbcRDDSuite.java [hunk 9]
```diff
@@ -39,30 +39,27 @@ public void setUp() throws ClassNotFoundException, SQLException {
...
-        "ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1)," +
-        "DATA INTEGER)");
-      create.close();
+    try (Connection connection = DriverManager.getConnection("jdbc:derby:target/JavaJdbcRDDSuiteDb;create=true")) {
+
+      try(Statement create = connection.createStatement()) {
+        create.execute(
+                "CREATE TABLE FOO(" +
+                        "ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1)," +
+                        "DATA INTEGER)");
```
Comment (HyukjinKwon) [inline core/src/test/java/org/apache/spark/JavaJdbcRDDSuite.java]: indentation ..

File: common/network-shuffle/src/test/java/org/apache/spark/network/sasl/SaslIntegrationSuite.java [hunk 10]
```diff
@@ -21,6 +21,7 @@
 import java.nio.ByteBuffer;
 import java.util.ArrayList;
 import java.util.Arrays;
+import java.util.Collections;
```
Comment (HyukjinKwon) [inline common/network-shuffle/src/test/java/org/apache/spark/network/sasl/SaslIntegrationSuite.java]: Looks unused.

**Review by HyukjinKwon — COMMENTED** [review]
was just looking through this out of curiosity. just few nits.

File: common/network-shuffle/src/test/java/org/apache/spark/network/shuffle/ExternalShuffleBlockResolverSuite.java [hunk 11]
```diff
@@ -98,19 +98,19 @@ public void testSortShuffleBlocks() throws IOException {
...
-    block0Stream.close();
-    assertEquals(sortBlock0, block0);
-
-    InputStream block1Stream =
-      resolver.getBlockData("app0", "exec0", 0, 0, 1).createInputStream();
-    String block1 = CharStreams.toString(
-        new InputStreamReader(block1Stream, StandardCharsets.UTF_8));
-    block1Stream.close();
-    assertEquals(sortBlock1, block1);
+    try(InputStream block0Stream =
```
Comment (kiszk) [inline common/network-shuffle/src/test/java/org/apache/spark/network/shuffle/ExternalShuffleBlockResolverSuite.java]: Would it be possible to add a space after `try`?

File: common/network-shuffle/src/test/java/org/apache/spark/network/shuffle/ExternalShuffleBlockResolverSuite.java [hunk 12]
```diff
@@ -98,19 +98,19 @@ public void testSortShuffleBlocks() throws IOException {
...
+        resolver.getBlockData("app0", "exec0", 0, 0, 0).createInputStream()) {
+      String block0 = CharStreams.toString(
+              new InputStreamReader(block0Stream, StandardCharsets.UTF_8));
+      assertEquals(sortBlock0, block0);
+    }
+
+    try(InputStream block1Stream =
```
Comment (kiszk) [inline common/network-shuffle/src/test/java/org/apache/spark/network/shuffle/ExternalShuffleBlockResolverSuite.java]: ditto

File: core/src/main/java/org/apache/spark/shuffle/sort/ShuffleExternalSorter.java [hunk 13]
```diff
@@ -181,42 +181,43 @@ private void writeSortedFile(boolean isLastFile) {
...
-        dataRemaining -= toTransfer;
+        final long recordPointer = sortedRecords.packedRecordPointer.getRecordPointer();
+        final Object recordPage = taskMemoryManager.getPage(recordPointer);
+        final long recordOffsetInPage = taskMemoryManager.getOffsetInPage(recordPointer);
+        int dataRemaining = UnsafeAlignedOffset.getSize(recordPage, recordOffsetInPage);
+        long recordReadPosition = recordOffsetInPage + uaoSize; // skip over record length
+        while (dataRemaining > 0) {
+          final int toTransfer = Math.min(diskWriteBufferSize, dataRemaining);
+          Platform.copyMemory(
+                  recordPage, recordReadPosition, writeBuffer, Platform.BYTE_ARRAY_OFFSET, toTransfer);
```
Comment (kiszk) [inline core/src/main/java/org/apache/spark/shuffle/sort/ShuffleExternalSorter.java]: nit: fix indentation

File: core/src/test/java/org/apache/spark/JavaJdbcRDDSuite.java (hunk 9 above)
Comment (Fokko) [reply core/src/test/java/org/apache/spark/JavaJdbcRDDSuite.java]: This one is horrible yes

File: core/src/test/java/test/org/apache/spark/JavaAPISuite.java [hunk 14]
```diff
@@ -997,10 +997,10 @@ public void binaryFiles() throws Exception {
 
     FileOutputStream fos1 = new FileOutputStream(file1);
 
-    FileChannel channel1 = fos1.getChannel();
-    ByteBuffer bbuf = ByteBuffer.wrap(content1);
-    channel1.write(bbuf);
-    channel1.close();
+    try(FileChannel channel1 = fos1.getChannel()) {
```
Comment (kiszk) [inline core/src/test/java/test/org/apache/spark/JavaAPISuite.java]: nit: space after `try`

File: core/src/test/java/test/org/apache/spark/JavaAPISuite.java [hunk 15]
```diff
@@ -1018,10 +1018,10 @@ public void binaryFilesCaching() throws Exception {
...
```
Comment (kiszk) [inline core/src/test/java/test/org/apache/spark/JavaAPISuite.java]: ditto

**Comment by Fokko** [comment]
Thanks for the feedback guys, I was relying too much on Scalastyle :)

File: sql/hive-thriftserver/src/main/java/org/apache/hive/service/cli/CLIService.java [hunk 16]
```diff
@@ -146,16 +146,11 @@ public UserGroupInformation getHttpUGI() {
...
     try {
-      metastoreClient = new HiveMetaStoreClient(hiveConf);
-      metastoreClient.getDatabases("default");
-    } catch (Exception e) {
-      throw new ServiceException("Unable to connect to MetaStore!", e);
-    }
-    finally {
-      if (metastoreClient != null) {
-        metastoreClient.close();
+      try (IMetaStoreClient metastoreClient = new HiveMetaStoreClient(hiveConf)) {
```
Comment (kiszk) [inline sql/hive-thriftserver/src/main/java/org/apache/hive/service/cli/CLIService.java]: Do we need `try` at line 149?

File: sql/catalyst/src/test/java/org/apache/spark/sql/catalyst/expressions/RowBasedKeyValueBatchSuite.java [hunk 17]
```diff
@@ -356,49 +335,45 @@ public void appendRowUntilExceedingPageSize() throws Exception {
...
-      long v1 = rand.nextLong();
-      long v2 = rand.nextLong();
-      appendRow(batch, makeKeyRow(k1, k2), makeValueRow(v1, v2));
-      expectedK1[i] = k1;
-      expectedK2[i] = k2;
-      expectedV1[i] = v1;
-      expectedV2[i] = v2;
-    }
-    try {
+
```
Comment (kiszk) [inline sql/catalyst/src/test/java/org/apache/spark/sql/catalyst/expressions/RowBasedKeyValueBatchSuite.java]: nit: it would be good to delete this brank line.

File: sql/catalyst/src/test/java/org/apache/spark/sql/catalyst/expressions/RowBasedKeyValueBatchSuite.java [hunk 18]
```diff
@@ -293,18 +276,16 @@ public void fixedLengthTest() throws Exception {
...
   }
 
   @Test
   public void appendRowUntilExceedingCapacity() throws Exception {
-    RowBasedKeyValueBatch batch = RowBasedKeyValueBatch.allocate(keySchema,
-            valueSchema, taskMemoryManager, 10);
-    try {
-      UnsafeRow key = makeKeyRow(1, "A");
-      UnsafeRow value = makeValueRow(1, 1);
+    UnsafeRow key = makeKeyRow(1, "A");
```
Comment (kiszk) [inline sql/catalyst/src/test/java/org/apache/spark/sql/catalyst/expressions/RowBasedKeyValueBatchSuite.java]: Can we put `key` and `value` inside `try`?

File: sql/catalyst/src/test/java/org/apache/spark/sql/catalyst/expressions/RowBasedKeyValueBatchSuite.java [hunk 19]
```diff
@@ -321,20 +302,18 @@ public void appendRowUntilExceedingCapacity() throws Exception {
...
   @Test
   public void appendRowUntilExceedingPageSize() throws Exception {
     // Use default size or spark.buffer.pageSize if specified
     int pageSizeToUse = (int) memoryManager.pageSizeBytes();
-    RowBasedKeyValueBatch batch = RowBasedKeyValueBatch.allocate(keySchema,
-            valueSchema, taskMemoryManager, pageSizeToUse); //enough capacity
-    try {
-      UnsafeRow key = makeKeyRow(1, "A");
-      UnsafeRow value = makeValueRow(1, 1);
+    UnsafeRow key = makeKeyRow(1, "A");
```
Comment (kiszk) [inline sql/catalyst/src/test/java/org/apache/spark/sql/catalyst/expressions/RowBasedKeyValueBatchSuite.java]: ditto

File: common/network-shuffle/src/test/java/org/apache/spark/network/shuffle/ExternalShuffleIntegrationSuite.java (hunk 4 above)
Comment (srowen) [reply common/network-shuffle/src/test/java/org/apache/spark/network/shuffle/ExternalShuffleIntegrationSuite.java]: The scenario is something like: later, a line or two in this block is changed. That change is cherry-picked to a branch before this change here. It's a merge conflict, and choosing "theirs" overwrites your change here. It would have to be manually merged. If you know that this is all that has happened, sure, not hard. But it relies on the committer figuring that out and not missing another subtle change during the manual merge. That's definitely the most time-consuming part for me. For Spark 3.x vs 2.x I am less worried, and would like a freer hand to make small improvements. Within a major release I am reluctant.

File: sql/catalyst/src/test/java/org/apache/spark/sql/catalyst/expressions/RowBasedKeyValueBatchSuite.java (hunk 17 above)
Comment (Fokko) [reply sql/catalyst/src/test/java/org/apache/spark/sql/catalyst/expressions/RowBasedKeyValueBatchSuite.java]: Good one

**Comment by Fokko** [comment]
Addressed comments and rebased onto master, no merge conflicts.

File: common/network-common/src/test/java/org/apache/spark/network/ChunkFetchIntegrationSuite.java [hunk 20]
```diff
@@ -143,37 +143,38 @@ public void releaseBuffers() {
   }
 
   private FetchResult fetchChunks(List<Integer> chunkIndices) throws Exception {
-    TransportClient client = clientFactory.createClient(TestUtils.getLocalHost(), server.getPort());
-    final Semaphore sem = new Semaphore(0);
-
     final FetchResult res = new FetchResult();
```
Comment (kiszk) [inline common/network-common/src/test/java/org/apache/spark/network/ChunkFetchIntegrationSuite.java]: nit: Can we put this line into `try` since this line was originally executed after `clientFactory.createClient`.

File: sql/hive-thriftserver/src/main/java/org/apache/hive/service/cli/CLIService.java (hunk 16 above)
Comment (kiszk) [reply sql/hive-thriftserver/src/main/java/org/apache/hive/service/cli/CLIService.java]: Do we need `try` at line 149?

File: common/network-common/src/test/java/org/apache/spark/network/ChunkFetchIntegrationSuite.java (hunk 20 above)
Comment (Fokko) [reply common/network-common/src/test/java/org/apache/spark/network/ChunkFetchIntegrationSuite.java]: No we can't, since the `res` is returned by the function :-)

Comment (Fokko) [reply common/network-common/src/test/java/org/apache/spark/network/ChunkFetchIntegrationSuite.java]: Any time

**Comment by Fokko** [comment]
@srowen Any incentive to move this forward? Or are PR's like these not appreciated? Let me know.

Most of the changes are cosmetic, but having <Java8 in the codebase give a bad example to newcomers to the Spark project. Also adding the `Closeable` to the `RowBasedKeyValueBatchSuite.java`:
https://github.com/apache/spark/pull/22399/files#diff-6c2c45f79666e2e52eb9f9411fa8b4baR49
makes the codebase a bit nicer in my opinion, since the class already has a `.close()` method, it makes sense to also implement the `Closeable` interface.

**Comment by srowen** [comment]
I think this is fine (though see https://github.com/apache/spark/pull/22399/files#r218121426 ). As a practical matter I might wait until we're done with the 2.4 release to start a lot of changes like this. It isn't tied to Spark 2.5 or 3.0 but might just be simpler to hold this for a bit, while we might be wanting to quickly backport a few changes from master to 2.4.

**Comment by Fokko** [comment]
Cool, makes sense. Thanks for the clarification @srowen

File: sql/hive-thriftserver/src/main/java/org/apache/hive/service/cli/CLIService.java (hunk 16 above)
Comment (Fokko) [reply sql/hive-thriftserver/src/main/java/org/apache/hive/service/cli/CLIService.java]: Good one, thanks

**Comment by Fokko** [comment]
Rebased onto master

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Comment by gatorsmile** [comment]
It sounds like the build is broken after merging this PR

**Comment by gatorsmile** [comment]
https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Compile/job/spark-master-compile-maven-hadoop-2.6/8432/

**Comment by gatorsmile** [comment]
https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Compile/job/spark-master-compile-maven-hadoop-2.7/8521/

**Comment by cloud-fan** [comment]
Jenkins was not triggered in this PR, I'm reverting it. Please re-open it and make sure jenkins pass, thanks!

**Comment by srowen** [comment]
Oh no, I got mixed up and didn't realize this one hadn't actually had a jenkins run. Sorry about this, that is my mistake. I will follow up.

**Comment by srowen** [comment]
Sorry @Fokko can you recreate this change in a new PR, after addressing...
```
[error] /home/jenkins/workspace/spark-master-compile-maven-hadoop-2.6/sql/hive-thriftserver/src/main/java/org/apache/hive/service/cli/CLIService.java:149: error: incompatible types: try-with-resources not applicable to variable type
[error]     try (IMetaStoreClient metastoreClient = new HiveMetaStoreClient(hiveConf)) {
[error]                           ^
[error]     (IMetaStoreClient cannot be converted to AutoCloseable)
[error] /home/jenkins/workspace/spark-master-compile-maven-hadoop-2.6/sql/hive-thriftserver/src/main/java/org/apache/hive/service/cli/operation/OperationManager.java:200: error: incompatible types: try-with-resources not applicable to variable type
[error]     try (Operation operation = removeOperation(opHandle)) {
[error]                    ^
[error]     (Operation cannot be converted to AutoCloseable)
```

**Comment by Fokko** [comment]
Thanks @srowen for pointing out the errors. Weird that it did not come up as a merge conflict. Let me open a new PR.

**Comment by Fokko** [comment]
The tests passed earlier, how would it be possible that it would fail on master?

**Comment by HyukjinKwon** [comment]
Let me trigger it in the next PR.

**Comment by Fokko** [comment]
@HyukjinKwon I've opened a new PR under https://github.com/apache/spark/pull/22637. Would be nice if you can trigger Travis 👍
